### ISSUE TITLE
DCEVM build

### ISSUE THREAD

**Issue by edudant** [AdoptOpenJDK/TSC#10]
We are looking for a build farm for an OpenJDK fork for with advanced hotswap features. We have merged original [Dynamic Code Evaluation VM (DCEVM)](http://dcevm.github.io/) JVM patch onto openjdk branch. In contrast to standard Java, where the hotswap is limited to in-body code changes, the DCEVM + HotswapAgent allow almost all code changes at runtime (add/remove fields, methods, interfaces, ...). For more info see [Hotswap Agent](http://hotswapagent.org/).

Adopt OpenJDK build configuration works fine for our project. See repos:
- [openjdk-jdk9 repo](https://github.com/HotswapProjects/openjdk-jdk9)
- [openjdk-jdk8u repo](https://github.com/HotswapProjects/openjdk-jdk8u)

We want the build for as many configurations as possible. New version is released only several times a year and the build may be run manually only for the release - this could reduce required resources significantly. Requirements for the build are similar to build clean JDK.

We may find a donor for founding, if required. Thank you.

**Comment by gdams** [comment]
thanks for moving this issue @edudant! I'm +1 on adding nightly `DCEVM` builds to our build farm! especially if you may be able to find a donor to help with funding some of the machines. I have three main questions for you:

1. What platforms does this variant currently build on? (also what platforms do you wish to build on in the future)
2. What sort of access would you require to build this variant? I assume that you'd need jenkins access but would machine access also be required?
3. Are there any other dependencies required to build this (other than the default openjdk hotspot dependencies)?

**Comment by edudant** [comment]
Hi, thank you! 

1. In the past we had a jenkins build farm for several build setups, but the company who hosted it stoped the support. Currently we are able to build binary image only from a development machine - for our team it means only Windows and Linux x86_64.  We need at least build for MacOS and JDK8/9/10. 

2. There is nothing special for the build - it is just a clone of Adopt OpenJDK JDK8/9 repo with several modifications to Hotspot sources. It might be only copy of existing jenkins job with new repository source. Jenkins access should be sufficient.

3. Not that I’m aware of.

**Comment by gdams** [comment]
okay so you are ideally looking for `JDK8/9/10` builds on MacOS, Linux x86_64 and Windows? 

You mentioned that you may be able to get some funding... Linux x86_64 builds generally aren't an issue for us as we have plenty of machines and they are cheap to source. My initial concern might be MacOS machine time as we only have two macs for building OpenJDK in the farm at the moment. If you had any funding available to help that would probably make adding this variant to the farm a little easier to justify.

Thoughts @karianna ?

**Comment by edudant** [comment]
Yes, DCEVM is currently used mostly by developers (it speeds up development by avoiding restarts) and I suppose that these platforms cover vast majority of developers. _Ideally_ all setups should be available :).

As we were looking for a build farm, we have found a Czech company who was interested in the project and was considenring to pay for the hosting. Beause our build is just a fork of standard JDK, it makes sense to use your setup. I will ask the company for this kind of foundig. How much do we need?

**Comment by gdams** [comment]
So I would reccomend that you take a look at https://github.com/AdoptOpenJDK/TSC/blob/master/PLATFORM_COSTS.md. It's just a very rough guide right now but it gives you an idea of how much it "costs" to build a nightly build every day. Ofcourse, you'd be welcome to bring your own kit into the project as well if you can source things cheaper yourselves!

**Comment by karianna** [comment]
@edudant We're just investigating a donate or pay by paypal option for this.  If there is a regular donation you could make would that work for you?

**Comment by gdams** [comment]
@edudant how does that sound to you?

**Comment by edudant** [comment]
The pricing sounds reasonable. If I understand it correctly, for Windows/Mac/Linux x64 and JDK 8/9/10 it is approximately £20 per month.

I am checking with the company if paypal works for them, but this amount should be Ok...

**Comment by centi** [comment]
Hi. I work for the company mentioned in the comments. I checked with my colleagues and paypal is not a preferred payment method for us. Is there a possibility to use a standard invoice/bank transfer method?

**Comment by karianna** [comment]
@centi Are you able to make international bank transfers (to the UK in particular)?

**Comment by centi** [comment]
@karianna Yes, this should not be a problem. May I contact you on your email so we can sort out the details?

**Comment by karianna** [comment]
yes I'm martijn AT londonjavacommunity DOT co DOT uk

**Comment by gdams** [comment]
@karianna any progress with this?

**Comment by centi** [comment]
HI @gdams,

everything is prepared (at least at our side in Etnetera), we are waiting only for the invoice from @karianna . We agreed on a yearly payment (12 * £21), so as soon as we receive the invoice, we will resolve this.

@karianna Any update on when we could get the invoice?

**Comment by gdams** [comment]
ping @karianna ?

**Comment by karianna** [comment]
@centi - Unfortunately we will no longer be able to support these builds at Eclipse Adoptium.  You're still more than welcome to use the scripts at temurin-build repo.  Closing this for now but please do feel free to reopen if you want to discuss further.
