### ISSUE TITLE
Provide cost reporting per OS/Architecture and download

### ISSUE THREAD

**Issue by jerboaa** [AdoptOpenJDK/TSC#100]
Considering that the downloads are a reasonable metric for "in-use" of AdoptOpenJDK binaries, it would be useful to get a cost-per-download metric added to the dashboards.

Base metrics:

- A: Running total of downloads per release (8, 11, 12, ...) and per OS/architecture per month
- B: Running total of infra cost per OS and architecture per month

Then take the sum of all downloads and realeases available on that OS/architecture over the infra costs of OS/architecture per month.

Knowing this will help guide the TSC in their decisions making process (e.g. for new infrastructure, sponsorship needed, etc).

**Comment by karianna** [comment]
Now done by the Eclipse Foundation
