### ISSUE TITLE
Promote AdoptOpenJDK Version 11.0.4+11.2 (Rebuild), 12.0.2+10.2 (Rebuild)

### ISSUE THREAD

**Issue by gdams** [AdoptOpenJDK/TSC#102]
Java Version:
11.0.4+11.2

JVM:
- [x] OpenJ9 - macOS https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk11-pipeline/538/
- [x] Hotspot - macOS https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk11-pipeline/535/

Java Version:
12.0.2+10.2

JVM:
- [x] OpenJ9 - macOS https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk12-pipeline/254/
- [x] Hotspot - macOS https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk12-pipeline/252/

@AdoptOpenJDK/tsc please can somebody +1 this request?

**Comment by lumpfish** [comment]
openj9 builds (completed):
jdk12: https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk12-pipeline/254
jdk11: https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk11-pipeline/538

**Comment by gdams** [comment]
promoted closing
