### ISSUE TITLE
Promote AdoptOpenJDK Version 11.0.4+11.3 (Rebuild), 12.0.2+10.3 (Rebuild)

### ISSUE THREAD

**Issue by gdams** [AdoptOpenJDK/TSC#103]
Java Version:
11.0.4+11.3

JVM:
- [ ] OpenJ9 - macOS https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk11-pipeline/544/
- [ ] Hotspot - macOS https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk11-pipeline/542/

Java Version:
12.0.2+10.3

JVM:
- [ ] OpenJ9 - macOS https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk12-pipeline/260/
- [ ] Hotspot - macOS https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk12-pipeline/257/

@AdoptOpenJDK/tsc please can somebody +1 this request?

**Comment by gdams** [comment]
## Test Results:

#### JDK11 Hotspot
https://ci.adoptopenjdk.net/job/Test_openjdk11_hs_sanity.system_x86-64_mac/25/
https://ci.adoptopenjdk.net/job/Test_openjdk11_hs_sanity.openjdk_x86-64_mac/25/
https://ci.adoptopenjdk.net/job/Test_openjdk11_hs_extended.system_x86-64_mac/19/
https://ci.adoptopenjdk.net/job/Test_openjdk11_hs_sanity.perf_x86-64_mac/26/

#### JDK11 OpenJ9
https://ci.adoptopenjdk.net/job/Test_openjdk11_j9_sanity.system_x86-64_mac/18/
https://ci.adoptopenjdk.net/job/Test_openjdk11_j9_extended.system_x86-64_mac/12/
https://ci.adoptopenjdk.net/job/Test_openjdk11_j9_sanity.openjdk_x86-64_mac/18/

#### JDK12 Hotspot
https://ci.adoptopenjdk.net/job/Test_openjdk12_hs_sanity.openjdk_x86-64_mac/16/
https://ci.adoptopenjdk.net/job/Test_openjdk12_hs_sanity.system_x86-64_mac/16/
https://ci.adoptopenjdk.net/job/Test_openjdk12_hs_extended.system_x86-64_mac/16/

#### JDK12 OpenJ9

**Comment by lumpfish** [comment]
Note that the system tests (links above) have JLINK failures with messages like:
```
09:25:34  STF 01:25:34.054 - Monitoring processes: JLNK
09:25:35  JLNK stderr Resources tree, invalid data structure, skipping /java.base/
09:25:35  JLNK stderr Resources tree, invalid data structure, skipping /java.base/META-INF/services/
09:25:35  JLNK stderr Resources tree, invalid data structure, skipping /java.base/META-INF/services/java.nio.file.spi.FileSystemProvider
09:25:35  JLNK stderr Resources tree, invalid data structure, skipping /java.base/META-INF/services/java.nio.file.spi.FileSystemProvider
09:25:35  JLNK stderr Resources tree, invalid data structure, skipping /java.base/apple/security/
09:25:35  JLNK stderr Resources tree, invalid data structure, skipping /java.base/apple/security/AppleProvider$1.class
09:25:35  JLNK stderr Resources tree, invalid data structure, skipping /java.base/apple/security/AppleProvider$1.class
```

**Comment by sxa** [comment]
I reject the request to promtote this now in light of the JLINK issues - requesting formal rollback of the notarization  changes in #107 until we can resolve this properly (possibly for the next quarterly release)

**Comment by aahlenst** [comment]
There won't happen anything here anymore. 11.0.4 and 12 are history.
