### ISSUE TITLE
Rollback 11.0.4+11.2 to resolve macos breakage

### ISSUE THREAD

**Issue by sxa** [AdoptOpenJDK/TSC#107]
The release promoted in https://github.com/AdoptOpenJDK/TSC/issues/102 has introduced some bad regressions as covered in https://github.com/AdoptOpenJDK/openjdk-build/issues/1211 and https://github.com/AdoptOpenJDK/openjdk-build/issues/1214 (and maybe elsewhere).

On this basis, despite that fact that this will undo the work which was implemented to assist with issue https://github.com/AdoptOpenJDK/openjdk-build/issues/1130 which was implemented under https://github.com/AdoptOpenJDK/openjdk-build/pull/1199 I believe the best approach is to roll back these changes to resolve the regressions the updated release has introduced. 11.0.3 did not have the hardend runtime support so this will not result in any regression relative to `11.0.3`.

We built a `11.0.4+11.3` (Sent for approval under https://github.com/AdoptOpenJDK/TSC/issues/103) but I would propose backing out all the changes and, in effect, release the original`11.0.4+11` as `11.0.4+11.4` to avoid naming confusion (I'm not sure where `.1` went in the history but I'm sure there was a reason for avoiding it.

@AdoptOpenJDK/tsc please we have approvals please?

**Comment by gdams** [comment]
+1

**Comment by lumpfish** [comment]
If we build an 11.0.4+11.4, what packaging code will be run?  Do we need to back out any installer code changes first?

**Comment by gdams** [comment]
I think the easiest approach would be to manually copy the binaries from the working release and just edit the json file in the process. That way we don't need to rebuild.

**Comment by sxa** [comment]
While it might be easier I'm not such a fan of "hacking" this and would prefer to have it done cleanly

**Comment by johnoliver** [comment]
yeah, if anything its good practice at doing this as this wont be the last time

**Comment by gdams** [comment]
okay, @sxa555 just remember to rollback the OpenJDK-installer and openjdk-build repo commits.

**Comment by lumpfish** [comment]
Which commits need to be backed out?
When we tested the 11.0.4+11 were we then still testing unsigned code?  If we back out all the installer and build changes does that mean we'll go back to testing unsigned code?

**Comment by sxa** [comment]
Rollbacks being done under:
- https://github.com/AdoptOpenJDK/openjdk-build/pull/1230
- https://github.com/AdoptOpenJDK/openjdk-installer/pull/154

**Comment by sxa** [comment]
Unanimous agreement in today's TSC call. Tests executing at the moment and awaiting finalisation in https://github.com/AdoptOpenJDK/TSC/issues/108
