### ISSUE TITLE
Promote AdoptOpenJDK Version 11.0.4+11.4 (macos only)

### ISSUE THREAD

**Issue by sxa** [AdoptOpenJDK/TSC#108]
Java Version:
11.0.4+11.4

JVM:
- [ ] OpenJ9
- [ ] Hotspot

@AdoptOpenJDK/tsc please can somebody +1 this request?

Related: https://github.com/AdoptOpenJDK/TSC/issues/107
HotSpot [Pipeline](https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk11-pipeline/558) - [Build](https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-mac-x64-hotspot/287/)
OpenJ9: [Pipeline](https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk11-pipeline/559) - [Normal](https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-mac-x64-openj9/324/) -  [Large Heap](https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-mac-x64-openj9-macosXL/286/)

**Comment by sxa** [comment]
HotSpot:
- [Sanity.openjdk](https://ci.adoptopenjdk.net/job/Test_openjdk11_j9_sanity.openjdk_x86-64_mac/31/consoleFull) - known issue, fixed in 11.0.5
- [sanity.system](https://ci.adoptopenjdk.net/job/Test_openjdk11_hs_sanity.system_x86-64_mac/38/) - Green
- [extended.system](https://ci.adoptopenjdk.net/job/Test_openjdk11_j9_extended.system_x86-64_mac/25/consoleFull) - Test harness (STF) failure - [issue raised](https://github.com/AdoptOpenJDK/openjdk-tests/issues/1294)

OpenJ9 normal:
- [sanity.openjdk](https://ci.adoptopenjdk.net/job/Test_openjdk11_j9_sanity.openjdk_x86-64_mac/31/) - known issue, fixed in 11.0.5
- [sanity.systemtest](https://ci.adoptopenjdk.net/job/Test_openjdk11_j9_sanity.system_x86-64_mac/31/) - Green :-)
- [extended.systemtest](https://ci.adoptopenjdk.net/job/Test_openjdk11_j9_extended.system_x86-64_mac/25/) - Test harness (STF) failure - [issue raised](https://github.com/AdoptOpenJDK/openjdk-tests/issues/1294)

OpenJ9 LH:
- [sanity.openjdk](https://ci.adoptopenjdk.net/job/Test_openjdk11_j9_sanity.openjdk_x86-64_mac_xl/30/) - Crash in `jdk_rmi_0` [Re-run](https://ci.adoptopenjdk.net/job/Test_openjdk11_j9_sanity.openjdk_x86-64_mac_xl/35/)
- [sanity.system](https://ci.adoptopenjdk.net/job/Test_openjdk11_j9_sanity.system_x86-64_mac_xl/30/) - Green
- [extended.system](https://ci.adoptopenjdk.net/job/Test_openjdk11_j9_extended.system_x86-64_mac_xl/24/console) - Machine connection died ...

**Comment by sxa** [comment]
I think we've lost the builds as the artifacts aren't in github and our retention policy of only one build with artifacts means they are no longer in jenkins. Starting again:
Top level pipelines: [HotSpot](https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk11-pipeline/563) - [OpenJ9](https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk11-pipeline/564)

| Build        |  Build  | sanity.openjdk | sanity.system | extended.system
| ------------- | ------------- | ----- | ---- | ---
| HotSpot      | [290](https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-mac-x64-hotspot/) | [40](https://ci.adoptopenjdk.net/job/Test_openjdk11_hs_sanity.openjdk_x86-64_mac/40/) PASS | [40](https://ci.adoptopenjdk.net/job/Test_openjdk11_hs_sanity.system_x86-64_mac/40/) LOST CONNECTION [41](https://ci.adoptopenjdk.net/job/Test_openjdk11_hs_sanity.system_x86-64_mac/41)| [34](https://ci.adoptopenjdk.net/job/Test_openjdk11_hs_extended.system_x86-64_mac/34/) HCRLateAttachWorkload_0 fail
| OpenJ9      | [327](https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-mac-x64-openj9/327/) | [34](https://ci.adoptopenjdk.net/job/Test_openjdk11_j9_sanity.openjdk_x86-64_mac/34/) PASS | [34](https://ci.adoptopenjdk.net/job/Test_openjdk11_j9_sanity.system_x86-64_mac/34/) PASS | [29](https://ci.adoptopenjdk.net/job/Test_openjdk11_j9_extended.system_x86-64_mac/29/)
| OpenJ9 LH | [289](https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-mac-x64-openj9-macosXL/289/) | [36](https://ci.adoptopenjdk.net/job/Test_openjdk11_j9_sanity.openjdk_x86-64_mac_xl/36/console)  BitSetStreamTest fail | [32](https://ci.adoptopenjdk.net/job/Test_openjdk11_j9_sanity.system_x86-64_mac_xl/32/console) PASS | [28](https://ci.adoptopenjdk.net/job/Test_openjdk11_j9_extended.system_x86-64_mac_xl/28/console)

**Comment by sxa** [comment]
- `HCRLateAttachWorkload_0` is a known issue covered in https://github.com/AdoptOpenJDK/openjdk-tests/issues/1267
- BitSetStreamTest NPM also seen in https://github.com/AdoptOpenJDK/openjdk-tests/issues/1229 so an intermittent failure that was previously there so should not hold up the release

**Comment by karianna** [comment]
@sxa555 I'm happy with the failure rate - it's on par with the other releases.

**Comment by sxa** [comment]
Attempted to promote it but doesn't appear to have worked so far

**Comment by sxa** [comment]
Completed
