### ISSUE TITLE
Promote AdoptOpenJDK Version jdk-12.0.2+10_openj9-0.15.1  AIX

### ISSUE THREAD

**Issue by andrew-m-leonard** [AdoptOpenJDK/TSC#109]
Java Version: jdk-12.0.2+10_openj9-0.15.1  AIX
Includes SAP's patch for AIX => 8228466: Fix build on AIX and with Solaris Studio 12u4 in 12u after HarfBuzz 2.3.1 upgrade

JVM:
- [ ] OpenJ9
https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk12-pipeline/279/

@AdoptOpenJDK/tsc please can somebody +1 this request?

**Comment by sxa** [comment]
Have the failures been triaged? https://github.com/AdoptOpenJDK/TSC/issues/99 suggests AIX passed ok at the time of the original JDK12 release, but [sanity.openjdk](https://ci.adoptopenjdk.net/job/Test_openjdk12_j9_sanity.openjdk_ppc64_aix/1/) is showing failures in `jdk_lang`, `jdk_net` and `jdk_nio` and neither [sanity.system](https://ci.adoptopenjdk.net/job/Test_openjdk12_j9_sanity.system_ppc64_aix/1/) nor [extended.system](https://ci.adoptopenjdk.net/job/Test_openjdk12_j9_extended.system_ppc64_aix/1/) seemed to run

**Comment by andrew-m-leonard** [comment]
re-running sanity.openjdk https://ci.adoptopenjdk.net/view/Test_openjdk/job/Test_openjdk12_j9_sanity.openjdk_ppc64_aix/2/console

**Comment by andrew-m-leonard** [comment]
there are 6 failures in the sanity.openjdk suite, with at least one crash:
https://ci.adoptopenjdk.net/view/Test_openjdk/job/Test_openjdk12_j9_sanity.openjdk_ppc64_aix/2/

Going to abandon publishing this til we get these sorted, probably best to look at jdk13.
