### ISSUE TITLE
Policy for retiring nightly builds

### ISSUE THREAD

**Issue by karianna** [AdoptOpenJDK/TSC#112]
https://github.com/AdoptOpenJDK/openjdk-installer/pull/127 raised the discussion of how long we should keep nightlies (raw binaries and/or installers).

At present, we keep forever.  One proposal is to keep the last 7 days + 1 from each preceding month.

**Comment by tresf** [comment]
From a bug-reporting perspective, I feel a week is fair as long as the OP is clearly instructed to grab a copy of the nightly before it expires.

Reason: A week isn't always long enough to completely finish a bug's unit tests.  The way other projects generally handle this is, the one-off-fix will be attached/linked in binary form to the bug report.  Assuming this redundant exercise is to be avoided for efficiency purposes, OPs need to be told to save the binaries before they expire.  It could be argued that any nightly would have the patch for unit testing -- and that's usually true -- but regressions exist, so having someone snag it ensures they're going up against the minimal amount of variance.

**Comment by karianna** [comment]
> From a bug-reporting perspective, I feel a week is fair as long as the OP is clearly instructed to grab a copy of the nightly before it expires.
> 
> Reason: A week isn't always long enough to completely finish a bug's unit tests. The way other projects generally handle this is, the one-off-fix will be attached/linked in binary form to the bug report. Assuming this redundant exercise is to be avoided for efficiency purposes, OPs need to be told to save the binaries before they expire. It could be argued that any nightly would have the patch for unit testing -- and that's usually true -- but regressions exist, so having someone snag it ensures they're going up against the minimal amount of variance.

That's a fair call - I suspect given the OSS/Community nature of this project that 7 days is a little aggressive.  I'm wondering if a whole month's worth is more realistic.

**Comment by smlambert** [comment]
A month is my preference.

**Comment by karianna** [comment]
Adoptium decision
