### ISSUE TITLE
OpenJDK 13 release on ~17th of Sept

### ISSUE THREAD

**Issue by karianna** [AdoptOpenJDK/TSC#113]
We will need to find a facilitator and a team as many folks will be at OC1

**Comment by karianna** [comment]
@johnoliver @smlambert and @andrew-m-leonard have volunteered !

**Comment by andrew-m-leonard** [comment]
Preliminary jdk-13+33_openj9-0.16.0 build kicked off: https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk13-pipeline/77/

**Comment by sxa** [comment]
OpenJ9 builds from Andrew's pipeline have been built and triaged with only known failures that we have shipped with previously, so it's ready to go on all platforms we've built on (All except Linux/ppc64le and AIX/ppc64 which have other issues)

**Comment by andrew-m-leonard** [comment]
jdk-13+33_openj9-0.16.0 is now available on all the usual platforms except pLinux & AIX.

**Comment by sxa** [comment]
(Note for reference: I approved this release via slack last night)

**Comment by andrew-m-leonard** [comment]
Can I get approval to publish jdk13 for openj9 on pLinux please ?

**Comment by smlambert** [comment]
+1 for publishing the jdk13 openj9 pLinux build

**Comment by jerboaa** [comment]
Should we close this issue? Released long since.
