### ISSUE TITLE
Promote AdoptOpenJDK Version 13+33 Hotspot

### ISSUE THREAD

**Issue by johnoliver** [AdoptOpenJDK/TSC#114]
Java Version:
13+33

JVM:
- [x] Hotspot

Platforms
- [x] Linux x86
- [x] Mac x86
- [x] Windows x86

https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk13-pipeline/80/

@AdoptOpenJDK/tsc please can somebody +1 this request?

**Comment by sxa** [comment]
Have the tests been fully triaged?

**Comment by johnoliver** [comment]
- Linux `java/net/SocketImpl/BadUsages.java` failure: https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/897

- Mac "well-known file is not secure" failure that seems to happen intermittently on a number of tests https://github.com/AdoptOpenJDK/openjdk-tests/issues/1353

A heart beat failure caused mac sanity to fail, this seems to be moderately common, happened 3 times in the last 10 builds:

- https://github.com/AdoptOpenJDK/openjdk-tests/issues/474
- https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/941

Re running those tests to see if we can get that suit to pass.

**Comment by johnoliver** [comment]
After getting mac sanity to rerun. There were a few test failures:

- https://github.com/AdoptOpenJDK/openjdk-tests/issues/1356
- https://github.com/AdoptOpenJDK/openjdk-tests/issues/1355
- https://github.com/AdoptOpenJDK/openjdk-tests/issues/1354

**Comment by johnoliver** [comment]
looks like failures were caused by a bug and almost certainly not the Mac binary itself, waiting on https://github.com/AdoptOpenJDK/openjdk-tests/pull/1357

**Comment by johnoliver** [comment]
Mac tests finally pass https://ci.adoptopenjdk.net/job/Test_openjdk13_hs_sanity.openjdk_x86-64_mac/57/
