### ISSUE TITLE
Promote AdoptOpenJDK Version 13+33 Hospot additional platforms

### ISSUE THREAD

**Issue by johnoliver** [AdoptOpenJDK/TSC#115]
Java Version: 13+33

JVM:
- [x] Hotspot

Platforms
- [x] Aix ppc64
- [x] Linux arm
- [x] Linux s390x
- [x] Windows x86-32
- [x] Windows aarch64

Test Issues

- AIX tests failed, seems in line with other platforms where they are not run.
- Other failures similar to openj9, triaged in https://github.com/AdoptOpenJDK/openjdk-tests/pull/1358

https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk13-pipeline/81/
 

@AdoptOpenJDK/tsc please can somebody +1 this request?

**Comment by smlambert** [comment]
+1
