### ISSUE TITLE
Contribute IBM TimeZoneUpdater tool for JDK8+

### ISSUE THREAD

**Issue by andrew-m-leonard** [AdoptOpenJDK/TSC#123]
We would like to contribute a fully functioning JDK Timezone updater to AdoptOpenJDK, along with supporting build&test pipelines for it. In summary the tool provides the following:

- Supports JDK tzdb.dat standard format for JDK8,11,13+, both Hotspot and OpenJ9
- Build pipeline automatically downloads the latest IANA data into the packaged tool.
- The built standard-alone tool has multiple modes of operation:
  - Using an interactive GUI:
    - Select to update a specific JDK home
    - Scan and update all JDKs found
  - From command line, Interactively or Silent/Automated:
    - Scan and update all JDKs found
    - Scan and update all JDKs based on a selective search configuration
    - Scan and discover what JDKs need updating (no update performed)
    - Scan and update specific JDK locations

Updater tool is pure java and runs with any JDK8+.

**Comment by andrew-m-leonard** [comment]
@karianna fyi

**Comment by jerboaa** [comment]
Has it been considered to contribute this to OpenJDK upstream?

**Comment by andrew-m-leonard** [comment]
No, Interesting point, but wondering why Oracle, Azul, et al have not contributed their ones....?

**Comment by jerboaa** [comment]
Not sure why this hasn't been done by others, yet. Getting a discussion started could potentially answer some of those questions. I'd encourage you to start a discussion about this upstream and get some opinions. Perhaps [jdk-dev](https://mail.openjdk.java.net/mailman/listinfo/jdk-dev) would be a good place? Failing upstream acceptance would make a better case for contributing it to AdoptOpenJDK, fwiw.

**Comment by andrew-m-leonard** [comment]
i'll give it a go on jdk-dev and see what response I get...

**Comment by jerboaa** [comment]
Thanks, @andrew-m-leonard!

**Comment by hendrikebbers** [comment]
@andrew-m-leonard is the code already available somewhere? I would love to see how you do the JDK scan since we create similar functionality in https://github.com/AdoptOpenJDK/IcedTea-Web and https://github.com/karakun/OpenWebStart

**Comment by andrew-m-leonard** [comment]
@hendrikebbers not yet... we have to do the due diligence on scanning and licensing etc beforehand

**Comment by andrew-m-leonard** [comment]
jdk-dev thread: 
https://mail.openjdk.java.net/pipermail/jdk-dev/2019-November/003622.html
http://mail.openjdk.java.net/pipermail/jdk-dev/2019-December/003677.html

**Comment by andrew-m-leonard** [comment]
So as was highlightd in the openjdk jdk-dev thread there are several issues with the above approach, in particular:
- The IBM TZUP tool is based on jdk8, whose runtime is more adaptable to "patching" and simple tzdb.dat replacement. With jdk11+ modularized approach this is not necessarily the same, the tzdb.dat can be replaced in an installed jdk, however the tzdb.dat is also present in the java.base.jmod, which means any Jlink'd runtime would not have the new tzdb. The jmod can not be patched as it stands either due to hashing.
- It was also suggested a user could build their own java.time.zone.DefaultZoneRulesProvider
- Sometimes tzdb updates do require other class library changes

**Comment by andrew-m-leonard** [comment]
OpenJDK is currently at the latest IANA release 2019c.
As an alternative approach, I would like to suggest the idea of doing ".1" releases with updated IANA data, via an AdoptOpenJDK patch, if a scheduled Qtrly release is say over 1 month away(?)..
The patch can then be contributed upstream, if not already been done.
In this way we can "react" quickly to a new IANA release, just like if a sev1 security update might be...

**Comment by andrew-m-leonard** [comment]
Raised TSC issue to discuss proposal: https://github.com/AdoptOpenJDK/TSC/issues/156

**Comment by smlambert** [comment]
Am presuming that this can be closed in favour of #156
