### ISSUE TITLE
Review openjdk javadoc page footer

### ISSUE THREAD

**Issue by lumpfish** [AdoptOpenJDK/TSC#124]
There is an openjdk-build issue open to publish the jdk javadoc at AdoptOpenJDK: https://github.com/AdoptOpenJDK/openjdk-build/issues/695

I have built the jdk8 javadoc locally and notice that the pages generated for the coreapi packages include the following text:

```
Submit a bug or feature
For further API reference and developer documentation, see Java SE Documentation. That documentation contains more detailed, developer-targeted descriptions, with conceptual overviews, definitions of terms, workarounds, and working code examples.
Copyright © 1993, 2019, Oracle and/or its affiliates. All rights reserved. Use is subject to license terms. Also see the documentation redistribution policy. 
```

"Submit a bug or feature" is a link to http://bugreport.sun.com/bugreport/
"Java SE Documentation" is a link to https://docs.oracle.com/javase/8/docs/index.html
"Copyright" is a link to https://docs.oracle.com/javase/7/docs/legal/cpyr.html
"documentation redistribution policy" is a link to http://www.oracle.com/technetwork/java/redist-137594.html

The text is defined in the build makefiles via make macros (so can be overridden at build time).

Please could the TSC advise on whether this documentation can be published at the AdoptOpenJDK website, or whether the project is able to modify the page footers to enable it to be published.

**Comment by lumpfish** [comment]
The openjdk8 javadoc is being hosted at https://devdocs.io/openjdk~8_gui/.
The page footer on those pages is different from those produced by the default openjdk8 build.

**Comment by lumpfish** [comment]
This site is hosting the javadoc with the default footer: https://javadoc.scijava.org/Java/

**Comment by karianna** [comment]
Taking this to various advisors

**Comment by karianna** [comment]
**From an advisor:**

If this is in response to a requirement to have to log in to download the Javadoc API for older releases - that was a bug and is now fixed.

**The download pages for JDK 11 docs:**

https://www.oracle.com/technetwork/java/javase/documentation/jdk11-doc-downloads-5097203.html 

**and JDK 8 docs:**

https://www.oracle.com/technetwork/java/javase/documentation/jdk8-doc-downloads-2133158.html

No login required.

As for changing footers, I'd have to refer you to your own legal department on that front.  I would never recommend modifying any legal notices and I would not use what you may see elsewhere as an example that can be replicated without exception -- you should defer to your own legal team on the obligations here.

**Comment by karianna** [comment]
@lumpfish - Is there a strong requirement to make this footer change?  If so we can engage some legal advice (at a cost).

**Comment by lumpfish** [comment]
The javadoc pages produced by the openjdk build contain the page footer pasted in the comment above (https://github.com/AdoptOpenJDK/TSC/issues/124#issue-526561076).  That footer contains several links, also pasted in the comment above.
One of the links points to https://www.oracle.com/technetwork/java/redist-137594.html.
Does that document effectively prevent the javadoc generated by the openjdk build being hosted at the AdoptOpenJDK website (we have open issues requesting that that be done)?
1. If it does:
   1. If that restriction is intended by the openjdk project, then I guess AdoptOpenJDK cannot publish the javadoc and cannot satisfy AdoptOpenJDK/openjdk-build#695
   2. If the openjdk project is actually happy for people who build the openjdk source to publish the documentation (which is after all an artefact of the build) then the footer added to the javadoc pages by the build does not appear to be appropriate.
1. If it does not (mean that AdoptOpenJDK is restricted from publishing the javadoc) then there is no issue, but it is not obvious to me that that is the case.

**Comment by lumpfish** [comment]
I should add that this impacts openjdk-openj9 releases more than openjdk-hotspot releases.
Users of openjdk-hotspot can currently view the jdk javadoc at the Oracle web site.  Eclipse openj9 adds additional classes to the jdk, and reimplements some of the openjdk classes for the purposes of integration with the openj9 virtual machine.
The openjdk-openj9 build creates the correct javadoc for the openjdk-openj9 jdk, but if the page footers added to the pages of the openjdk originating classes prevent the publishing of those pages then a user cannot be provided with a web site containing the full javadoc for that jdk.

**Comment by sxa** [comment]
While we could engage a legal team on this, I think we need to start by engaging the openjdk project to understand which of the three possible interpretations enumerated by Simon is correct first. i.e. is the interpretation of the OTN document correct, and would prevent us posting the javadoc associated with our builds? It likely depends on whether any of the documents described in the OTN doc cover "javadoc" which isn't explicitly mentioned in there.

**Comment by karianna** [comment]
> While we could engage a legal team on this, I think we need to start by engaging the openjdk project to understand which of the three possible interpretations enumerated by Simon is correct first. i.e. is the interpretation of the OTN document correct, and would prevent us posting the javadoc associated with our builds? It likely depends on whether any of the documents described in the OTN doc cover "javadoc" which isn't explicitly mentioned in there.

Taking this to TSC

**Comment by lumpfish** [comment]
@karianna - any update?

**Comment by karianna** [comment]
> @karianna - any update?

No sorry, I'll have to dig out this thread again.

**Comment by gdams** [comment]
@karianna any update on this?

**Comment by karianna** [comment]
My interpretation is that we'll need legal advice here, taking it to the TSC to see what next steps are

**Comment by lumpfish** [comment]
The openjdk-openj9 build has been enhanced so that javadoc can be created for only those classes added or replaced by openj9, and that javadoc is now published at the eclipse/openj9 project - e.g. see https://www.eclipse.org/openj9/docs/api-jdk11/.

So it is no longer true that eclipse/openj9 are not able to provide javadoc for their jdk extensions without also needing to publish pages containing the openjdk page footers for the openjdk classes.

**Comment by smlambert** [comment]
Based on https://github.com/AdoptOpenJDK/TSC/issues/124#issuecomment-725349029 and discussions with a few other folks, we will close this issue.
