### ISSUE TITLE
Extend the functionality of the dashboard to track statistics over time

### ISSUE THREAD

**Issue by adam-thorpe** [AdoptOpenJDK/TSC#126]
Hi there, 

Myself, @m-davies, @willsparker and @haroon-khel are looking to extend the functionality of the AdoptOpenJDK Dashboard: https://dash.adoptopenjdk.net/ so that it can track the downloads of our binaries over time, to show trends and compare between different versions and platforms.

For this, we would develop a back-end hosted by Adopt to pull data from our various download sources (Adopt API and Docker), which could run daily for example and store the results into a database. The dashboard would then use the data from the database to handle requests made by the user to display on graphs, which could support filters (such as version, implementation, download site etc). 

We have a couple design choices in mind for this, InfluxDB could be used for the database as it is optimised for time-based data and Graphana allows us to create professional-looking graphs while also supporting InfluxDB and an API for HTML. These are both leading open source technologies, but we are open to hearing about other suggestions that may be more suited to the needs of this project.

The maintenance involved should be minimal and be dealt with by us or the community as a whole, similarly to how the current dashboard is handled. We would look to create it in a dynamic way, such that new releases and versions are automatically added to the system.

We'd like your thoughts on whether you would be interested in this type of enhancement or not and any other suggestions you have. Thank you for your time.

**Comment by tellison** [comment]
Sounds great.  As well as the dashboard you should also take a look at the [project download tracker](https://download-tracker.adoptopenjdk.net/), which is a poor version of what you are proposing. 

Is there anything you need immediately from us to get going with this idea?  As I'm sure you know our [dash code](https://github.com/AdoptOpenJDK/openjdk-dashboard) is already available for you to study.

There may be people willing to help and give feedback if you chat about your work on Slack.  I look forward to seeing progress!

**Comment by M-Davies** [comment]
We're proposing this as we feel it would be a useful resource for the community to show adoption trends (ie: at conferences / to executives) and demonstrate how Adopt and the community have grown over time.

**Comment by adam-thorpe** [comment]
> Is there anything you need immediately from us to get going with this idea?

I believe we're good to go, we've already played around with the different components to come up with this solution, we just want to get the community's thoughts on the project to see if there are any other suggestions or insights that we could use.

**Comment by tellison** [comment]
Ok.  I suggest you engage with people via Slack (#website channel) for chat and collaboration, and when you get to the point of having code to discuss, resolve any technical points via issues on the website repo.

Thanks for heads-up to the TSC.

**Comment by karianna** [comment]
Paging @gdams as he led the code on the dashboard.

**Comment by M-Davies** [comment]
Work is continuing on this at: 
- https://github.com/AdoptOpenJDK/openjdk-api-v3/issues/44
- https://github.com/AdoptOpenJDK/openjdk-dashboard/issues/18

**Comment by smlambert** [comment]
Closing as any remaining related activity is tracked in other repos now.
