### ISSUE TITLE
October 2019 Release Retrospective

### ISSUE THREAD

**Issue by sxa** [AdoptOpenJDK/TSC#128]
Ref: https://github.com/AdoptOpenJDK/TSC/issues/113 https://github.com/AdoptOpenJDK/TSC/issues/119 https://github.com/AdoptOpenJDK/TSC/issues/120
I believe AIX is still outstanding due to some test case issue with math functions.

**Comment by smlambert** [comment]
**Post-mortem notes**
Things that went well:
- major platforms - pipelines ran well (xlinux, windows, mac)
- daily release calls & slack discussion helpful
- having a central issue to track release https://github.com/AdoptOpenJDK/TSC/issues/119 is good

Things that hindered release:
- loss of AIX machines (down to 1 for build and test during this period)
- only build team knows how to launch build pipelines (no doc, unclear how openjdk mirrors and tags work)
- not everyone puts links or build IDs to builds or tests in the central issue, hard to track down jobs later

Suggestions for improvement:
- machine audit a few days ahead of the release (know how many machines are healthy, fill gaps where needed if possible)
- document how to launch build pipelines (how to determine what tags to use, etc)
- ensure tests are triaged fully prior to the release so it is clear if new failures arise
- add [annotation feature to trss ](https://github.com/AdoptOpenJDK/openjdk-test-tools/issues/163)(to indicate which are the candidate and real pipeline jobs for releases)
- create an 'executive summary' view of a release in trss or refer to the trss grid view that can be linked to from the central issue 
- create tutorial on how to use trss for triaging releases

**Comment by sxa** [comment]
Doc issue (ref build pipelines) is something I'm working to address - hope to make more progress on that over the next week as I already have a draft kicking around but particularly for point releases it's not clear what options to use. Alsothe OpenJ9 side of it that's a bit problematic to cover - HotSpot is fairly easy to explain from that perspective ;-) The doc I have is based on one that was written purely for OpenJ9 so I've had to do a bit of refactoring on it.

Hopefully AIX will be assisted in some capacity by us having two providers now for AIX to give us a bit more redundancy (although a bit more setup is still required)

And yep ensuring links are in the "main" release issue should be heavily encouraged / mandated unless impractical for some reason.

**Comment by andrew-m-leonard** [comment]
When is the latest Release Retrospective going to be scheduled?

**Comment by andrew-m-leonard** [comment]
We've come up with these ideas to address known issues with releasing:
- Investigate & implement "concurrent" AdoptOpenJDK "build pipeline" support
- Investigate/pursue "in-progress" TRSS view for build pipeline status
- Grinder Slack notify support at AdoptOpenJDK
- Review Adopt Nightly Build+platform and tests+platform scheduling for optimum execution

**Comment by lumpfish** [comment]
>     * Investigate/pursue "in-progress" TRSS view for build pipeline status

Created https://github.com/AdoptOpenJDK/openjdk-test-tools/issues/174

**Comment by adamfarley** [comment]
All remaining actions here appear resolved, as discussed in the [2021 January retrospective](https://github.com/AdoptOpenJDK/TSC/issues/195#issuecomment-763762204).

@sxa - Please close.
