### ISSUE TITLE
Create openjdk-support release

### ISSUE THREAD

**Issue by sxa** [AdoptOpenJDK/TSC#129]
Our `java.vendor.url.bug` property in the adoptopenjdk builds points to the https://github.com/adoptopenjdk/openjdk-build for people to raise bugs. That doesn't feel like  the right place for them as very few end-user raised bugs are in fact things that are relevant for that repository.

In order to "declutter" the openjdk-build repository, and after a discussion in #build we have decided to create https://github.com/adoptopenjdk/openjdk-support which will have all the end-user raised issues.

This was agreed on this week's TSC call.

- [x] - Create release
- [x] - Transfer issues across (may have missed some - feel free to migrate more but be careful not to lose tags
- [x] - Add new tag `AdoptOpenJDK only`
- [x] - Update code to point people at the new repository going forward - https://github.com/AdoptOpenJDK/openjdk-build/pull/1432
- [x] - Add templates based on [the one already in build](https://github.com/AdoptOpenJDK/openjdk-build/blob/master/.github/ISSUE_TEMPLATE/binary-issue.md) (or [website](https://github.com/AdoptOpenJDK/openjdk-build/blob/master/.github/ISSUE_TEMPLATE/installer-issues.md)
- [x] - Add a suitable README.md
- [ ] - Add links to this from any other parts of the website etc. where appropriate

**Comment by gdams** [comment]
@sxa555 is there any remaining website work or can this be closed?

**Comment by sxa555** [comment]
I think that's up to us to discuss as a TSC - at the moment i don't think it's too easy to find

**Comment by sxa** [comment]
No I think we're good with this
