### ISSUE TITLE
Update Documentation for latest new repos added

### ISSUE THREAD

**Issue by karianna** [AdoptOpenJDK/TSC#133]
Dashboard v2
jdk14
jdk15
graphql api
TKG

**Comment by tellison** [comment]
Is the [repos diagram](https://docs.google.com/drawings/d/1h2YzP1zAUsYku8sFbx5xP2mTe1DFVx-6NOHzQ3Hso5w/edit?usp=sharing) in the AdoptOpenJDK drive area?
Seems I need to request edit access explicitly, which is fine but I wasn't expecting to need to do so.

**Comment by karianna** [comment]
> Is the [repos diagram](https://docs.google.com/drawings/d/1h2YzP1zAUsYku8sFbx5xP2mTe1DFVx-6NOHzQ3Hso5w/edit?usp=sharing) in the AdoptOpenJDK drive area?
> Seems I need to request edit access explicitly, which is fine but I wasn't expecting to need to do so.

I'll look into that - I think we can loosen the restrictions there.

**Comment by karianna** [comment]
Done at Adoptium
