### ISSUE TITLE
Building graal/svm master at AdoptOpenJDK

### ISSUE THREAD

**Issue by jerboaa** [AdoptOpenJDK/TSC#138]
I've been working on getting [OpenJDK HEAD](http://hg.openjdk.java.net/jdk/jdk/) building at [AdoptOpenJDK](https://github.com/AdoptOpenJDK/openjdk-build/issues/1467) That's one prerequisite for building graal and particularly Substrate VM at AdoptOpenJDK using only open source code. No proprietary binary blobs needed.

Proposed steps are:

- [x] Build `graal-builder-image` target of HotSpot OpenJDK HEAD. See: https://ci.adoptopenjdk.net/job/jdk-15-gaovm-builder-x86_64_linux/
- [x] Use the resulting builder image to build graal/svm master from AdoptOpenJDK mirror. See: https://ci.adoptopenjdk.net/job/jdk-15-gaovm-x86-64_linux/

@AdoptOpenJDK/tsc  OK to proceed with this?

**Comment by tellison** [comment]
yes, though we should consider the resource requirements on infrastructure for build/test

**Comment by jerboaa** [comment]
Absolutely. Perhaps we could set up dedicated infra for this work?

Also, it could be a manual build once a week for a start. Usually graal sources need patching for recent JDK HEAD changes quite frequently. It's not clear to me how we'll set this up. I'm not sure about testing as well. Especially SVM's native-image testing will be interesting as to how to set this up.

**Comment by sxa** [comment]
Manual build once a week shouldn't be a problem so I'm personally ok with that for now :-)
For reference we had [these jobs](https://ci.adoptopenjdk.net/search/?q=graal) building graal a while back but they haven't been actively maintained by anyone. I beleive @neomatrix369 set them up

**Comment by jerboaa** [comment]
Thanks for the references @sxa555!

**Comment by karianna** [comment]
I'm OK with this.

**Comment by jerboaa** [comment]
This got approved in principle by the TSC on the call today. I'll move forward with this.

**Comment by jerboaa** [comment]
Closing this issue as it's now built at AdoptOpenJDK here:
https://ci.adoptopenjdk.net/job/jdk-15-gaovm-x86-64_linux/

Example as to how this can be used is:
```
$ wget https://ci.adoptopenjdk.net/job/jdk-15-gaovm-x86-64_linux/lastSuccessfulBuild/artifact/results/substrate/svm.tar.gz
$ tar -xf svm.tar.gz
$ ./svm/bin/java -version
OpenJDK 64-Bit Server VM warning: -XX:ThreadPriorityPolicy=1 may require system level permission, e.g., being the root user. If the necessary permission is not possessed, changes to priority will be silently ignored.
openjdk version "15-internal" 2020-09-15
OpenJDK Runtime Environment GaoVM 20.1.0-dev (build 15-internal+0-adhoc.jenkins.openjdk)
OpenJDK 64-Bit Server VM GaoVM 20.1.0-dev (build 15-internal+0-adhoc.jenkins.openjdk, mixed mode, sharing)
$ cat > HelloWorld.java <<EOF
public class HelloWorld {
  public static void main(String[] args) {
    System.out.println("Hello World!");
  }
}
EOF
$ ./svm/bin/javac HelloWorld.java
$ ./svm/bin/native-image HelloWorld testme-helloworld
OpenJDK 64-Bit Server VM warning: -XX:ThreadPriorityPolicy=1 may require system level permission, e.g., being the root user. If the necessary permission is not possessed, changes to priority will be silently ignored.
OpenJDK 64-Bit Server VM warning: -XX:ThreadPriorityPolicy=1 may require system level permission, e.g., being the root user. If the necessary permission is not possessed, changes to priority will be silently ignored.
[testme-helloworld:172293]    classlist:   3,966.91 ms,  1.21 GB
[testme-helloworld:172293]        (cap):     691.65 ms,  1.68 GB
[testme-helloworld:172293]        setup:   1,915.86 ms,  1.68 GB
[testme-helloworld:172293]   (typeflow):   4,709.92 ms,  1.69 GB
[testme-helloworld:172293]    (objects):   4,092.38 ms,  1.69 GB
[testme-helloworld:172293]   (features):     237.30 ms,  1.69 GB
[testme-helloworld:172293]     analysis:   9,385.11 ms,  1.69 GB
[testme-helloworld:172293]     (clinit):     176.33 ms,  1.69 GB
[testme-helloworld:172293]     universe:     489.47 ms,  1.69 GB
[testme-helloworld:172293]      (parse):   1,129.01 ms,  1.69 GB
[testme-helloworld:172293]     (inline):   1,961.50 ms,  2.71 GB
[testme-helloworld:172293]    (compile):  10,073.05 ms,  2.74 GB
[testme-helloworld:172293]      compile:  13,861.18 ms,  2.74 GB
[testme-helloworld:172293]        image:   1,634.22 ms,  3.93 GB
[testme-helloworld:172293]        write:     196.73 ms,  3.93 GB
[testme-helloworld:172293]      [total]:  31,680.21 ms,  3.93 GB
$ ./testme-helloworld
Hello World!
```
