### ISSUE TITLE
HotSpot support for Arm32 Architecture

### ISSUE THREAD

**Issue by dinogun** [AdoptOpenJDK/TSC#140]
Are we going to continue to support `arm32` Architecture for HotSpot builds ? Current status

| arm32 Build Status | 8u242-b08 | 11.0.6+10 | 13.0.2+8 | 14+36 |
| :----------: | :-------------: | :------------: | :---------: | :-------: |
| **Hotspot JDK** | A | A | A | A |
| **Hotspot JRE** | A | NA | NA | NA |

**Comment by sxa** [comment]
Yes - I'm working on 8u242-b08 now so hope to have it soon (ideally this week)

**Comment by sxa** [comment]
Related: https://github.com/AdoptOpenJDK/openjdk-build/issues/1531

**Comment by gdams** [comment]
@dinogun can this be closed now?

**Comment by karianna** [comment]
@gdams - let's keep this open until we get more hardware.

**Comment by sxa** [comment]
@karianna Are we short of hardware here? This wasn't caused by a lack of hardware, only the lack of ability to build the GA level due to the aarch32 mirror not having valid tags in it

**Comment by karianna** [comment]
> @karianna Are we short of hardware here? This wasn't caused by a lack of hardware, only the lack of ability to build the GA level due to the aarch32 mirror not having valid tags in it

I thought we were but I know you're retrying on our existing so let's see!

**Comment by sxa** [comment]
Assigning Martijn as I believe he volunteered to look into the mirroring for us (We had a discussion with @jerboaa and @andrew-m-leonard on slack, but no-one had any solution)

**Comment by karianna** [comment]
The mirroring seems to be fine now.

**Comment by gdams** [comment]
looks like we should use `jdk8u242-ga-aarch32-200120`

**Comment by karianna** [comment]
@gdams - want to kick off a release build just for that?  Hmm that might then override the non JIT binary that we have there.

**Comment by gdams** [comment]
yeah I'll give it a go

**Comment by gdams** [comment]
triggered: https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk8-pipeline/938/

**Comment by gdams** [comment]
looks like the mirroring is still broken:

```bash
## Starting langtools
/bin/sh: 1: cd: can't cd to /home/jenkins/workspace/build-scripts/jobs/jdk8u/jdk8u-linux-arm-hotspot/workspace/build/src/langtools/make
/home/jenkins/workspace/build-scripts/jobs/jdk8u/jdk8u-linux-arm-hotspot/workspace/build/src//make/Main.gmk:84: recipe for target 'langtools-only' failed
```

Suggests that there isn't even a langtools directory for that tag

**Comment by karianna** [comment]
Yep, confirmed it in our GitHub source.  Common to all tags

**Comment by sxa** [comment]
Yep - exactly the same issue I was having when trying to use the normal `jdk8uXXX` tags

**Comment by dinogun** [comment]
Just updated the status in the description above, so I see we have JDK's for 8, 11, 13 and 14 (Thanks !). The JRE however is only available for `8u242-b08`. Is this expected ?

**Comment by karianna** [comment]
I think we should have JREs for those others.

**Comment by karianna** [comment]
This was resolved some time ago
