### ISSUE TITLE
Promote AdoptOpenJDK Version -> Windows ARM64

### ISSUE THREAD

**Issue by eklipse2k8** [AdoptOpenJDK/TSC#141]
Java Version:
Version 8/11/12

JVM:
- [ ] OpenJ9
- [ X] Hotspot

@AdoptOpenJDK/tsc please can somebody +1 this request?

**Comment by sxa** [comment]
At the moment we do not have any suitable machines in our infrastructure so we cannot build, let alone promote, builds for this architecture, although I'm quite interested in having it myself ;-)

@eklipse2k8 Have you tried our Linux/aarch64 builds under WSL? :-)

**Comment by karianna** [comment]
I'll see if the hardware can be procured through Azure (CC @gdams )

**Comment by gdams** [comment]
The Node.js folks have been doing windows arm64 builds. I'm not sure if this is cross-compiled or if they have dedicated hardware? Ping @rvagg to see if he can help.

**Comment by rvagg** [comment]
Dedicated, but not very _serious_ hardware, it's early days. Ping @joaocgreis for an explanation.

**Comment by tresf** [comment]
I've snagged a maxed-out Surface Pro X for testing purposes.  I'd happily lend remote access to it as a build machine to an AdoptOpenJDK developer, or help sponsor procurement, etc.

**Comment by sxa** [comment]
So @karianna's question still stands - can we get such systems through Azure so we could have something in our CI @gdams?

**Comment by sxa** [comment]
I also have an aarch64 Windows machine myself, but am a bit short on time for working on getting a port running on it :-)

**Comment by gdams** [comment]
There are multiple people who have managed to get windows 10 running on a pi 4. I'm going to investigate further.

**Comment by gdams** [comment]
>can we get such systems through Azure 

@sxa555 there is currently no commercially available option in Azure.

**Comment by karianna** [comment]
We'll need to purchase rent hardware from elsewhere for now (I'm trying to avoid using any fully locked down Windows Azure hosts, let's wait until they have a public offering there)

**Comment by tresf** [comment]
> There are multiple people who have managed to get windows 10 running on a pi 4. I'm going to investigate further.

I completely forgot about this.  That makes the build very affordable too.  Can we send a few devices your way?  I see Microsoft has an official Pi 3B+ technical preview, would that be good hardware?  Of course, at this price, you may choose to just buy one for yourselves, but at that price you can likely get 2 Pis + storage for < £85 (USD 100).

**Comment by joaocgreis** [comment]
For Node.js we have a couple of Asus NovaGo laptops running in my office connected directly to CI. We plan to move to Azure when ARM64 machines become available there.

Note that Visual Studio does not support native compilation on ARM64, but only cross-compilation from x86 or x64. So, since ARM64 Windows has emulation for x86, when compiling on an ARM64 machine the x86 version of Visual Studio is used.

**Comment by tresf** [comment]
> Note that Visual Studio does not support native compilation on ARM64, but only cross-compilation from x86 or x64. So, since ARM64 Windows has emulation for x86, when compiling on an ARM64 machine the x86 version of Visual Studio is used.

@joaocgreis thanks for this information.  Are the cross-compilers only available to ARM64 Operating Systems?  If not, do we need ARM64 at all?  (e.g., Is this just for the unit tests to pass?)

**Comment by karianna** [comment]
We need ARM to pass the tests and should we ever need to natively compile, then one to build as well.

**Comment by joaocgreis** [comment]
@tresf the cross compilers are available on any installation of Visual Studio. So, you should only need real hardware to run the tests.

To install the cross compilers, you need Visual Studio 15.9.0 or newer with the following components installed:
- Visual C++ compilers and libraries for ARM64
- Visual C++ ATL for ARM64
- Windows 10 SDK 10.0.17763.0 or newer

Note that the process might be a little tricky if you need to compile and run tools during the build process. We can't cross-compile Node.js for ARM64 because we need this and the V8 build files haven't been adjusted to build the tools for the host architecture yet.

**Comment by tresf** [comment]
Status update, @gdams was able to get Windows 10 ARM64 running on a Pi 4B.  Two more Pi 4B kits are heading his way. 📦

**Comment by tresf** [comment]
FYI, I've been using the ARM64 HotSpot build from Microsoft and it works very well on the Surface Pro X, well enough to contribute to this PR: https://github.com/java-native-access/jna/pull/1264.  I realize this is a TSC thread, but wanted to share my success story.

**Comment by aahlenst** [comment]
@tresf Input is always welcome. Progress is very slow in this area at the moment because I'm struggling to purchase suitable hardware that we can put into a rack. I'm still optimistic that we can resolve it until the release of 16.

**Comment by tresf** [comment]
> @tresf Input is always welcome. 

Well, you guys were one step ahead of me.  The only bug I've found so far in my specific use-case was patched on the new version before I could report it.  I don't personally use Windows on ARM64 as a daily workstation, but I have a strong feeling that this use-case will start to grow exponentially [if/once the M1 virtualization is more viable](https://9to5mac.com/2020/12/02/windows-on-m1-macs-run-arm-virtualization/) combined with the [up-and-coming 64-bit Intel emulation](https://www.theverge.com/2020/9/30/21495510/microsoft-windows-on-arm-x64-app-emulation).

**Comment by karianna** [comment]
Moved to Adoptium
