### ISSUE TITLE
Update end of building OpenJDK 8u date

### ISSUE THREAD

**Issue by tellison** [AdoptOpenJDK/TSC#142]
[Red Hat have declared](https://access.redhat.com/articles/1299013) that they will continue supporting the upstream OpenJDK 8u source stream until May 2026.

This issue is to propose that we continue to build that code stream and distribute binaries beyond our current sated date of ["At least Sept 2023"](https://adoptopenjdk.net/support.html), and set a new date to match the Red Hat supported date of "May 2026".

This would be reflected by an [update to our website](https://github.com/AdoptOpenJDK/openjdk-website/pull/686).

**Comment by jerboaa** [comment]
Seems fine to me. +1.

**Comment by gdams** [comment]
+1

**Comment by karianna** [comment]
+1
