### ISSUE TITLE
Promote AdoptOpenJDK Version 14+36

### ISSUE THREAD

**Issue by karianna** [AdoptOpenJDK/TSC#143]
jdk-14+36_openj9-0.19.0 :
https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk14-pipeline/58

- [x] pLinux
- [x] pLinuxXL
- [x] zLinuxXL
- [x] xLinux
- [x] xLinuxXL
- [x] windows
- [x] windowsXL
- [x] zLinux
- [x] macOS
- [x] macOSXL
- [x] AIX

jdk-14+36

- [x] pLinux
- [x] xLinux
- [x] windows
- [x] zLinux
- [x] macOS
- [x] AIX
- [x] aarch64

**Comment by lumpfish** [comment]
@karianna, initial jdk14 release I expect to be jdk-14+36 (no ".0.0") - see https://adoptopenjdk.net/archive.html?variant=openjdk13&jvmVariant=hotspot for reference

So jdk-14+36 for hotspot.

For openj9,  jdk-14+36_openj9-0.19.0  (not openj9-0.20.0, that is destined for the Apr quarterly updates).  The platform list is correct.

**Comment by andrew-m-leonard** [comment]
https://mail.openjdk.java.net/pipermail/jdk-dev/2020-March/004089.html

**Comment by lumpfish** [comment]
Test triage for openj9-openjdk14 builds: https://github.com/AdoptOpenJDK/openjdk-tests/issues/1676.  The two test failures have been reviewed by the eclipse/openj9 community and are not stop ship issues.

**Comment by karianna** [comment]
OpenJ9 release is effectively done.  We have a source code tag issue for Hotspot repo - @gdams is investigating

**Comment by karianna** [comment]
Hotspot builds are on their way.

**Comment by gdams** [comment]
**Test Failures:**
**Linux - x64**
**special.functional**
MBCS_Tests_formatter_ko_KR_linux_0  => been failing long term [deep history](https://trss.adoptopenjdk.net/deepHistory?testId=5e714e68214b905e3b0c4505)
MBCS_Tests_formatter_zh_CN_linux_0  => been failing long term [deep history](https://trss.adoptopenjdk.net/deepHistory?testId=5e714e68214b905e3b0c454d)
MBCS_Tests_formatter_zh_TW_linux_0  => been failing long term [deep history](https://trss.adoptopenjdk.net/deepHistory?testId=5e714e68214b905e3b0c4594)
MBCS_Tests_formatter_ja_JP_linux_0  => been failing long term [deep history](https://trss.adoptopenjdk.net/deepHistory?testId=5e714e68214b905e3b0c45db)

**extended.system**
MathLoadTest_all_0   => intermittent failure [deep history](https://trss.adoptopenjdk.net/deepHistory?testId=5e714e64214b905e3b0c42bf)

**Linux - aarch64**
**extended.system**
MathLoadTest_all_0  => been failing long term [deep history](https://trss.adoptopenjdk.net/deepHistory?testId=5e7144d9214b905e3b0c15ed)
LockingLoadTest_0  => been failing long term [deep history](https://trss.adoptopenjdk.net/deepHistory?testId=5e7144d9214b905e3b0c15f3)

**sanity.system** => non blockers (see #134 (comment))
MauveSingleThreadLoadTest_HotSpot_0
MauveMultiThreadLoadTest_0
MauveSingleInvocationLoadTest_HotSpot_0

**Comment by gdams** [comment]
@tsc can I get a +1 to ship hotspot

**Comment by smlambert** [comment]
+1

Going through each of the failures listed above, we have indeed seen and marked most of them non-blocking (though I think we need to further investigate the MathLoadTest_all to make sure its reported to the correct repo for fixing).

**Comment by gdams** [comment]
thanks @smlambert I will run the release job now

**Comment by gdams** [comment]
Windows x86 and Linux arm32 builds complete: https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk14-pipeline/75/

No test failures.

@tsc can I publish?

**Comment by smlambert** [comment]
+1 to publish win32/arm32 builds

**Comment by gdams** [comment]
Published
