### ISSUE TITLE
Remove JRE Docker images for 11+

### ISSUE THREAD

**Issue by brunoborges** [AdoptOpenJDK/TSC#144]
It is well known that Oracle no longer builds and ships a JRE post Java 11+. Other vendors follow the same approach, including AdoptOpenJDK that does not include any JRE in its download page:

https://adoptopenjdk.net/releases.html?variant=openjdk13&jvmVariant=hotspot

To eliminate confusion, I suggest AdoptOpenJDK to unpublish the JRE images on Docker Hub and stop generating them.

- https://github.com/AdoptOpenJDK/openjdk-docker/tree/master/11/jre
- https://github.com/AdoptOpenJDK/openjdk-docker/tree/master/12/jre
- https://github.com/AdoptOpenJDK/openjdk-docker/tree/master/13/jre
- https://github.com/AdoptOpenJDK/openjdk-docker/tree/master/14/jre

**Comment by karianna** [comment]
This is a TSC Agenda item.  Last time we discussed this our user base strongly indicated that they still preferred a legacy JRE package to be made available to them.  But that may now have changed

We do have a separate jlink.online project at adopt which is looking at allowing users to build custom jlinked binaries.  At some stage, I could imagine that taking over.

**Comment by tellison** [comment]
> To eliminate confusion, ...

Are people confused?

**Comment by gdams** [comment]
> including AdoptOpenJDK that does not include any JRE in its download page:

@brunoborges we continue to ship JRE's for all versions on the website as well as docker images. There is still a very high demand for JRE's (particularly on windows)

**Comment by dinogun** [comment]
I see issues being raised against JRE docker images and people still asking for it, so definitely there is demand for them. Should we be pushing people towards jlink, definitely yes, however IMO, having JRE images is a temporary arrangement, until people fully migrate to using jlink.

**Comment by cilki** [comment]
Agreed that JRE builds are temporarily useful, but could eventually be replaced by jlinked runtimes. The biggest obstacle with jlink.online right now is that it takes about 60 seconds to generate a runtime in the worst case. I’m still working on reducing that number.

Once jlink.online is fast enough, I can certainly imagine it replacing the JRE builds (and surpassing their utility).

**Comment by karianna** [comment]
> Agreed that JRE builds are temporarily useful, but could eventually be replaced by jlinked runtimes. The biggest obstacle with jlink.online right now is that it takes about 60 seconds to generate a runtime in the worst case. I’m still working on reducing that number.
> 
> Once jlink.online is fast enough, I can certainly imagine it replacing the JRE builds (and surpassing their utility).

I could see a wonderful world where through an API we could provide 'JDK profiles' like legacy JRE, FaaS, Desktop, Server Only etc.

Also through a website and API we could let users totally customize.  Of course, the support burden then gets interesting :-)

**Comment by tellison** [comment]
> Also through a website and API we could let users totally customize. Of course, the support burden then gets interesting :-)

More so than today, where end users can run jlink themselves?  Provided the served-up runtimes are the honest output of the jlink tool then I don't see the difference about where it happens.

**Comment by cilki** [comment]
I really like the idea of JDK profiles. We could even sensibly include modules from Maven Central in the runtimes (which wouldn’t be a big security risk since we wouldn’t allow users to explicitly specify those).

**Comment by aahlenst** [comment]
The plan is to keep the JRE around for 8 and 11, add a jlinked bundle for 11 and higher. Work is happening in https://github.com/AdoptOpenJDK/openjdk-build/pull/1812.
