### ISSUE TITLE
Update end of building OpenJDK 11u date

### ISSUE THREAD

**Issue by tellison** [AdoptOpenJDK/TSC#145]
A follow-on to #142 , and apologies for not doing both at the same time.

[Red Hat have declared](https://access.redhat.com/articles/1299013) that they will continue supporting the upstream OpenJDK 11u source stream until October 2024.

This issue is to propose that we continue to build that code stream and distribute binaries beyond our current sated date of "At least Sept 2022", and set a new date to match the Red Hat supported date.

This would be reflected by an update to our website.

**Comment by karianna** [comment]
The website is already updated.  I'll label this as done (after scratching my head to try and figure out the scenario where we'd support 8 to 2026 but not 11 to 2024 ;-))

**Comment by tellison** [comment]
@karianna 
> after scratching my head to try and figure out the scenario where we'd support 8 to 2026 but not 11 to 2024

Well, there is a body of code that is likely never moving off Java 8 due to the impact of changes introduced in Java 9 onwards.  For them we'd need to keep building Java 8u to the natural end of life of their applications.

However, for those applications that have moved to Java 11 LTS they are arguably more likely to be able to move up from Java 11 LTS to Java 17 LTS (due Sept 2021) and onwards, hence we can drop support for Java 11 sooner.
