### ISSUE TITLE
Keep building JDK 13 as supported version

### ISSUE THREAD

**Issue by ggam** [AdoptOpenJDK/TSC#147]
Oracle JDK 13 support ends next month, but Azul was successfully elected as new maintainer:
* https://mail.openjdk.java.net/pipermail/jdk-updates-dev/2020-February/002535.html
* https://mail.openjdk.java.net/pipermail/jdk-updates-dev/2020-March/002669.html

From their roadmap, their idea is to support intermediate releases at least until the next LTS is released. They call this "Medium Term Support" releases: https://www.azul.com/products/azul-support-roadmap/

Intermediate releases see low adoption because of their short term support. People are generally confused about the concept of what LTS is. They tend to think only 11 (and presumably 17) is LTS because "Java devs have decided it". But OpenJDK doesn't have the notion of LTS, it's vendors that provide or not that extended support.

Until now, only 11 saw general extended support, with RedHat leading the effort. Now that Azul plans to do the same with 13, the message needs to change.

There are two things Adopt I see Adopt can do about this:
* If there's enough resources, keep building JDK 13 as supported builds (although with only one vendor maintaining them). Instead of "LTS" releases, which os not a feature of the Java version itself, but a decision from some vendor to provide extended support, I'd call them "Currently supported".
* Reach an agreement with Azul for them to provide "upstream builds" at https://adoptopenjdk.net/upstream.html in the same way RedHat is already doing. This makes AdoptOpenJDK the canonical place for upstream OpenJDK builds once Oracle stops providing them at https://jdk.java.net/

**Comment by tellison** [comment]
Thanks for the suggestion @ggam, a good topic for discussion.

It would require a non-trivial amount of resource in terms of machines and people (to manage, triage tests, and build images/installers etc).  Of course, hosting "upstream" builds would expected to be done in collaboration with Yuri.  These would have to be balanced against the expected demand for JDK 13, and the people who show up to help make it happen.

**Comment by ggam** [comment]
Thanks @tellison for considering this. For me this event opens some philosophical questions:
* What can users expect when they read some version is "LTS"? Even if Azul provides support for JDK 13, that means only Hotspot, not OpenJ9. So there aren't LTS *Java* versions, but LTS *builds* or *variants*.
* What quality level can we expect from those builds? I don't doubt Azul's team capacity for doing this (they already handle Java 6 and 7 update projects), but every vendor happened to agree on supporting Java, while this time this will be a single vendor effort. Perhaps instead of saying "LTS" or "non LTS", the page should list the maintainer, or the companies providing support.

IMHO, this is something to consider regardless builds are distributed via Adopt or not. The fact is that I still meet people who think Oracle made Java a paid product and that only 11 is safe to use because newer versions won't have support. This is now clearly not the case and so I think the wording can be improved.

**Comment by tellison** [comment]
I understand your concerns @ggam, and they are at the core of the AdoptOpenJDK mission.  We saw some builders producing OpenJDKs labelled as JDK 11 from unstable code streams so collaborated on a shared build definition; and we saw the need for defining a new high bar quality test for builders, so produced the [AQA definition](https://blog.adoptopenjdk.net/2019/07/the-first-drop-introducing-adoptopenjdk-quality-assurance-aqa-v1-0).

Producing ongoing OpenJDK 13 builds at AdoptOpenJDK would be a statement of community support for the update project.  We need to judge the level of that interest for such an investment.

**Comment by grzesuav** [comment]
Maybe dull question, but if fixes will be put to source code of jdk13, what stops adoptopenjdk from keeping build on their side with fixes in source ?

edit: Except resources usage of course.

**Comment by karianna** [comment]
> Maybe dull question, but if fixes will be put to source code of jdk13, what stops adoptopenjdk from keeping build on their side with fixes in source?
> 
> edit: Except resources usage of course.

Its machine resource to do the builds and people resource to triage bugs + extra code kept for API, website etc

**Comment by ggam** [comment]
I just saw there are some thumbs down on my original post on this issue. No offense of course, but I'm sincerely curious about it. Would you please, people who downvoted, give your opinion about this request?

**Comment by l2dy** [comment]
> I just saw there are some thumbs down on my original post on this issue. No offense of course, but I'm sincerely curious about it. Would you please, people who downvoted, give your opinion about this request?

Expect more votes coming:

> "Please chime in and either 👍 or 👎 the request for AdoptOpenJDK to continue providing OpenJDK 13." https://blog.adoptopenjdk.net/2020/04/adoptopenjdk-8u252-1107-and-1401-available/

---

My opinion: I would stick to LTS releases for enterprise use and the latest release for personal use, so I think supported builds for MTS releases would not be much appreciated.

Providing "upstream builds" sounds good to me though, because we don't have to maintain the infrastructure.

**Comment by vveider** [comment]
So this is the reason of missing 13.0.3 in Releases ad AdoptOpenJDK?

**Comment by karianna** [comment]
> So this is the reason of missing 13.0.3 in Releases ad AdoptOpenJDK?

Correct.  If we had more people and infra resources we would revisit this.

**Comment by vveider** [comment]
Thanks for update.
Also, I wonder where are old released binaries, i. e. 13.0.2 — did not found anywhere on site...

**Comment by aahlenst** [comment]
@vveider For old releases, please see https://adoptopenjdk.net/archive.html.

**Comment by vveider** [comment]
Brilliant, thanks!

**Comment by aahlenst** [comment]
Now that the 2nd quarterly patch update passed with 13 being in MTS mode, I've checked the state of affairs. Azul is the only vendor I found offering anything newer than 13.0.2 (they provide 13.0.4) and they only do so for x86, x86_64 and ARM64 on Linux, Windows and macOS (obviously, not all architectures are supported for all operating systems).

Other vendors I checked: Red Hat, Bell Soft, SAP, Amazon, Alibaba.

**Comment by aahlenst** [comment]
The TSC discussed the topic yesterday again and the verdict is that we don't intend to provide MTS releases, at least for now. Reasons:

* Interest from end-users is low to non-existent.
* It would be a significant additional burden on the project (starting next March, we'd have to build/test 5 versions in parallel).

We'll reconsider if interest grows significantly.

**Comment by ggam** [comment]
Thanks for the update and for considering my suggestion!
