### ISSUE TITLE
Move default API to v3 and address earlier deprecations

### ISSUE THREAD

**Issue by tellison** [AdoptOpenJDK/TSC#148]
This TSC issue covers a move to API v3 as the principal API route for users.

Now that v3 is stable and has been in use for a while it is time to make it mainstream by:

-  routing `api.adoptopenjdk.net` to the v3 server to serve up the v3 documentation page.  This will encourage new users to switch to the v3 API.
 - updating the v1/v2 repository documentation to declare both are deprecated (https://github.com/AdoptOpenJDK/openjdk-api/pull/196)
 - discuss removing the v1 API as it has been deprecated for a long time (https://github.com/AdoptOpenJDK/openjdk-api/pull/192)
 - enhancing the v3 readme documentation?

**Comment by karianna** [comment]
https://github.com/AdoptOpenJDK/openjdk-api/pull/196 has landed.

**Comment by gdams** [comment]
Before we migrate to v3 as default I suggest that we add a note about V1 and V2 to the description of the swagger doc

**Comment by gdams** [comment]
Description PR https://github.com/AdoptOpenJDK/openjdk-api-v3/pull/131

**Comment by gdams** [comment]
Next steps in my opinion:

- [x] Merge https://github.com/AdoptOpenJDK/openjdk-api-v3/pull/131
- [x] Switch Routing in OpenShift for `/` to v3
- [x] Create route in OpenShift for `/Readme` to V2
- [x] Remove any other routes in OpenShift

**Comment by gdams** [comment]
@tsc has voted and approves making V3 the default.

**Comment by gdams** [comment]
final PR https://github.com/AdoptOpenJDK/openjdk-api-v3/pull/132

**Comment by gdams** [comment]
v3 has now been marked as default, v2 remains usable, v1 is removed
