### ISSUE TITLE
Promote AdoptOpenJDK Version jdk8u252-b09

### ISSUE THREAD

**Issue by smlambert** [AdoptOpenJDK/TSC#153]
Java Version:
jdk8u252-b09

JVM:
- [x] OpenJ9
- [x] Hotspot

@AdoptOpenJDK/tsc please can somebody +1 this request?

**Comment by smlambert** [comment]
OpenJ9: 
TRSS links: [AIX](https://trss.adoptopenjdk.net/resultSummary?parentId=5e977fe40833d14bd52f3f9c) and [other platforms](https://trss.adoptopenjdk.net/resultSummary?parentId=5e977fe40833d14bd52f3f9e)

Test_openjdk8_j9_sanity.external_x86-64_linux #266: [3 failures](https://trss.adoptopenjdk.net/buildDetail?parentId=5e97b9610833d14bd5304fda) - these are non-blocking, they should get fixed, some are failures related to recent changes to external test targets

**Comment by andrew-m-leonard** [comment]
**OpenJ9:**
**jdk8:**
- pLinuxXL build failure: machine build-osuosl-centos74-ppc64le-1
- pLinux build failure: machine build-osuosl-centos74-ppc64le-2
https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-linux-ppc64le-openj9-linuxXL/141/console
https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-linux-ppc64le-openj9/567/consoleFull
```
checking for protoc... no
configure: error: jitserver requires protoc
configure exiting with result code 1
```
- xLinux : Test_openjdk8_j9_sanity.external_x86-64_linux #266: 3 failures - these are non-blocking, they should get fixed, some are failures related to recent changes to external test targets

**Comment by andrew-m-leonard** [comment]
OpenJ9:
jdk11:
- aarch64:
https://ci.adoptopenjdk.net/job/Test_openjdk11_j9_sanity.openjdk_aarch64_linux/114/testReport/
java/lang/reflect/callerCache/ReflectionCallerCacheTest.java.ReflectionCallerCacheTest
```
00:05:40  test ReflectionCallerCacheTest.load("AccessTest$PublicFinalField"): failure
00:05:40  java.lang.AssertionError: failed to satisfy condition
00:05:40  	at ReflectionCallerCacheTest$ForceGC.await(ReflectionCallerCacheTest.java:174)
00:05:40  	at ReflectionCallerCacheTest.load(ReflectionCallerCacheTest.java:113)
00:05:40  test ReflectionCallerCacheTest.load("AccessTest$PrivateFinalField"): failure
00:05:40  java.lang.AssertionError: failed to satisfy condition
00:05:40  	at ReflectionCallerCacheTest$ForceGC.await(ReflectionCallerCacheTest.java:174)
00:05:40  	at ReflectionCallerCacheTest.load(ReflectionCallerCacheTest.java:113)
00:05:40  test ReflectionCallerCacheTest.load("AccessTest$PublicStaticFinalField"): failure
00:05:40  java.lang.AssertionError: failed to satisfy condition
00:05:40  	at ReflectionCallerCacheTest$ForceGC.await(ReflectionCallerCacheTest.java:174)
00:05:40  	at ReflectionCallerCacheTest.load(ReflectionCallerCacheTest.java:113)
00:05:40  test ReflectionCallerCacheTest.load("AccessTest$PrivateStaticFinalField"): failure
00:05:40  java.lang.AssertionError: failed to satisfy condition
00:05:40  	at ReflectionCallerCacheTest$ForceGC.await(ReflectionCallerCacheTest.java:174)
00:05:40  	at ReflectionCallerCacheTest.load(ReflectionCallerCacheTest.java:113)
```

**Comment by andrew-m-leonard** [comment]
**OpenJ9:**
**jdk14:**
- pLinux:
com/sun/crypto/provider/Cipher/ChaCha20/OutputSizeTest.java.OutputSizeTest
https://ci.adoptopenjdk.net/job/Test_openjdk14_j9_sanity.openjdk_ppc64le_linux_xl/58/testReport/junit/com_sun_crypto_provider_Cipher_ChaCha20_OutputSizeTest/java/OutputSizeTest/
```
java.lang.RuntimeException: Cipher Cipher.ChaCha20-Poly1305, mode: decryption, algorithm from: SunJCE, in: 1024, expOut: 6128, actual: 1008
	at OutputSizeTest.testOutLen(OutputSizeTest.java:170)
```

**Comment by gdams** [comment]
HotSpot: TRSS Link: https://trss.adoptopenjdk.net/buildDetail?parentId=5e96f8790833d14bd52ea14b&testSummaryResult=failed&buildNameRegex=%5ETest.*

**Comment by gdams** [comment]
Hotspot JDK8u Failures:

**Test_openjdk8_hs_extended.system_x86-64_mac**
HCRLateAttachWorkload_0 => long term failure [deep history](https://trss.adoptopenjdk.net/deepHistory?testId=5e970d320833d14bd52ead7d)

**Test_openjdk8_hs_sanity.openjdk_s390x_linux**
jdk_jdi_0 => long term failure [deep history](https://trss.adoptopenjdk.net/deepHistory?testId=5e97a8c50833d14bd53001a7) - [test issue](https://github.com/AdoptOpenJDK/openjdk-tests/issues/1731) for further triage (did this occur in last release?)
jdk_lang_0 => intermittent failure [deep history](https://trss.adoptopenjdk.net/deepHistory?testId=5e97a8c50833d14bd53001a3)
jdk_util_0 => intermittent failure [deep history](https://trss.adoptopenjdk.net/deepHistory?testId=5e97a8c50833d14bd53001a6) 

**Test_openjdk8_hs_sanity.external_x86-64_linux_tomee**
tomee_test_0 => long term failure [deep history](https://trss.adoptopenjdk.net/deepHistory?testId=5e9709d90833d14bd52eab34) Non-Blocking https://github.com/AdoptOpenJDK/TSC/issues/153#issuecomment-614390641 - (still considered non-blocking, but created [test issue](https://github.com/AdoptOpenJDK/openjdk-tests/issues/1730) for triage/fixing)

**Test_openjdk8_hs_sanity.system_x86-64_linux**
TestJlmRemoteMemoryAuth_SE80_Linux_0 => passed in [grinder](https://ci.adoptopenjdk.net/job/Grinder/2836/console)

**Test_openjdk8_hs_sanity.external_x86-64_linux_openliberty-mp-tck**
openliberty_microprofile_tck_0 => long term failure [deep history](https://trss.adoptopenjdk.net/deepHistory?testId=5e9709d70833d14bd52eab25) Non-Blocking https://github.com/AdoptOpenJDK/TSC/issues/153#issuecomment-614390641

**Test_openjdk8_hs_sanity.openjdk_x86-32_windows**
jdk_jdi_0 => long term failure [deep history](https://trss.adoptopenjdk.net/deepHistory?testId=5e9707710833d14bd52ea81c)

**Test_openjdk8_hs_sanity.openjdk_x86-64_mac**
jdk_jdi_0 => long term failure [deep history](https://trss.adoptopenjdk.net/deepHistory?testId=5e970d330833d14bd52ead88)

**Test_openjdk8_hs_sanity.external_x86-64_linux_thorntail-mp-tck**
thorntail_microprofile_tck_0 => long term failure [deep history](https://trss.adoptopenjdk.net/deepHistory?testId=5e9709d70833d14bd52eab2c) Non-Blocking https://github.com/AdoptOpenJDK/TSC/issues/153#issuecomment-614390641

**Test_openjdk8_hs_sanity.openjdk_x86-64_windows**
jdk_jdi_0 => long term failure [deep history](https://trss.adoptopenjdk.net/deepHistory?testId=5e97067b0833d14bd52ea77d)

**Comment by lumpfish** [comment]
Regarding failure
> pLinuxXL build failure: machine build-osuosl-centos74-ppc64le-1
> ```
> checking for protoc... no
> configure: error: jitserver requires protoc
> configure exiting with result code 1
> ```

It looks like pLinux openj9 built successfully on that machine on 10th April: https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-linux-ppc64le-openj9/558/

**Comment by andrew-m-leonard** [comment]
pLinux when it worked:
```
checking for jitserver... yes (explicitly enabled)
checking checking that '/home/jenkins/workspace/build-scripts/jobs/jdk8u/jdk8u-linux-ppc64le-openj9/workspace/./build//freemarker-2.3.30/freemarker.jar' exists... yes
checking for sysroot... 
```
when it failed:
```
checking for jitserver... yes (explicitly enabled)
checking for protoc... no
configure: error: jitserver requires protoc
```
Seems the check for protoc has been added?

**Comment by lumpfish** [comment]
openj9 release builds resubmitted following fix for the ppcle build issue (https://github.com/ibmruntimes/openj9-openjdk-jdk8/pull/403)

New pipeline: https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk8-pipeline/990

**Comment by lumpfish** [comment]
TRSS link to openj9 respin pipeline: https://trss.adoptopenjdk.net/resultSummary?parentId=5e9855cd0833d14bd533b9d2

**Comment by andrew-m-leonard** [comment]
**OpenJ9:**
- xLinux: **known issue with docker container**
https://ci.adoptopenjdk.net/job/Test_openjdk8_j9_sanity.external_x86-64_linux_openliberty-mp-tck/262/console
```
14:49:26  	/home/jenkins/workspace/Test_openjdk8_j9_sanity.external_x86-64_linux_openliberty-mp-tck/openjdk-tests/TKG/../external/external.sh --clean --tag ubuntu --version 8 --impl openj9 --dir openliberty-mp-tck; } 2>&1 | tee -a "/home/jenkins/workspace/Test_openjdk8_j9_sanity.external_x86-64_linux_openliberty-mp-tck/openjdk-tests/TKG/../TKG/test_output_15870449669653/TestTargetResult";
14:49:26  No EXTRA_DOCKER_ARGS set
14:49:26  docker: Error response from daemon: Conflict. The container name "/openliberty-mp-tck-test" is already in use by container "81e7baff80acd9dae4af7f7c69e7443b452fbf63076800b0fd4d7415dc07437d". You have to remove (or rename) that container to be able to reuse that name.
```

**Comment by andrew-m-leonard** [comment]
@AdoptOpenJDK/tsc request to publish OpenJ9 jdk8u252-b09 please?

**Comment by karianna** [comment]
+1

**Comment by smlambert** [comment]
+1 to publishing both openj9 and hotspot

Speaking to @gdams - we will plan to release hotspot also.  Note on QA: I am working through the list of test failures and creating independent issues for each of the remaining failures so they can be properly triaged.  For the release retrospective, I recommend this activity happen more regularly or at minimum the week before release so that we enter the release with a clean slate.

**Comment by gdams** [comment]
jdk8u252-b09 hotspot released on all platforms except for aarch64

**Comment by gdams** [comment]
jdk8u252-09 aarch64 https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk8-pipeline/993/ 

No Test Failures! 🎉 

https://trss.adoptopenjdk.net/buildDetail?parentId=5e99b7674b7a9f456900fd75&testSummaryResult=passed&buildNameRegex=%5ETest.*

@tsc request to publish

**Comment by sxa** [comment]
+1 to aarch64/HotSpot

**Comment by gdams** [comment]
Notarized `jdk8u252-b09` build is complete: https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk8-pipeline/1001/

Test Failures:

**Test_openjdk8_hs_extended.system_x86-64_mac**
HCRLateAttachWorkload_0 => long term failure [deep history](https://trss.adoptopenjdk.net/deepHistory?testId=5e970d320833d14bd52ead7d) - Failed in previous release as well

**Test_openjdk8_hs_sanity.system_x86-64_mac**
TestJlmRemoteMemoryAuth_SE80_0 => passed on re-run [grinder](https://ci.adoptopenjdk.net/job/Grinder/2893/)

**Comment by gdams** [comment]
@tsc request to publish Notarized JDK8u build

**Comment by karianna** [comment]
+1

**Comment by lumpfish** [comment]
Windows and Mac openj9 releases have been rebuilt to:
1. Upgrade the bundled OpenSSL to the latest level (1.1.1g)
2. Include the fix for https://github.com/AdoptOpenJDK/openjdk-build/issues/1694 (Windows binaries signing)
3. Add Mac notarization support.

Build pipeline: https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk8-pipeline/1003/
TRSS: https://trss.adoptopenjdk.net/resultSummary?parentId=5ea054e04b7a9f45690d6150 (no failures)

Windows X64 build has been downloaded from the job and checked for 'Digital Signatures' tab in Properties.

**Comment by gdams** [comment]
hotspot win rebuild:

https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk8-pipeline/1002/
TRSS: https://trss.adoptopenjdk.net/buildDetail?parentId=5ea011374b7a9f45690d4d29

Failures:

**Test_openjdk8_hs_sanity.openjdk_x86-64_windows**
jdk_util_0 => passed in [grinder](https://ci.adoptopenjdk.net/job/Grinder/2920/)
jdk_jdi_0 => long term failure [deep history](https://trss.adoptopenjdk.net/deepHistory?testId=5e97067b0833d14bd52ea77d)

**Test_openjdk8_hs_sanity.openjdk_x86-32_windows**
jdk_jdi_0 => long term failure [deep history](https://trss.adoptopenjdk.net/deepHistory?testId=5e9707710833d14bd52ea81c)

**Comment by lumpfish** [comment]
@tsc - request to publish the openj9 release rebuilds as jdk8u252-b09.1_openj9-0.20.0.

**Comment by gdams** [comment]
@lumpfish +1 (note that `@tsc` is a user not `@AdoptOpenJDK/tsc` I noticed I was doing the same thing earlier

**Comment by lumpfish** [comment]
You mean I should use tag @AdoptOpenJDK/tsc to alert tsc members?

**Comment by gdams** [comment]
correct 👍

**Comment by gdams** [comment]
@AdoptOpenJDK/tsc request to publish hotspot win rebuild

**Comment by sxa** [comment]
Approved - go for it

**Comment by lumpfish** [comment]
openj9 rebuilds published: https://github.com/AdoptOpenJDK/openjdk8-binaries/releases/tag/jdk8u252-b09.1_openj9-0.20.0
