### ISSUE TITLE
Create a new repo for build-jdk Github action

### ISSUE THREAD

**Issue by smlambert** [AdoptOpenJDK/TSC#159]
Just as we have created a [run-aqa github action](https://github.com/AdoptOpenJDK/run-aqa) that can run our AQA tests, we now have a build-jdk action that use the Adopt build scripts and can build the same things that we do out of pipelines in the openjdk-build repo.

Once its own repo, we will create a release and example workflow files to aid others in its use.

Does the TSC support the creation of a https://github.com/AdoptOpenJDK/build-jdk repo ?

**Comment by gdams** [comment]
+1

**Comment by smlambert** [comment]
As discussed in the weeks TSC call, we will proceed (I will create the new repo and @sophia-guo will populate it with the action code).  Cheers!

**Comment by smlambert** [comment]
Thanks @sophia-guo : https://github.com/AdoptOpenJDK/build-jdk !
