### ISSUE TITLE
Public Feedback on Move to Eclipse

### ISSUE THREAD

**Issue by gdams** [AdoptOpenJDK/TSC#160]
Background article: https://blog.adoptopenjdk.net/2020/06/adoptopenjdk-to-join-the-eclipse-foundation/

**Comment by avermeer** [comment]
Great news!

By the way, when will `java -version` output and `java.vendor` system property be updated to reflect the _Adoptium_ new name ?

Will Eclipse IDE be shipped with Adoptium OpenJ9 by default?

**Comment by akuckartz** [comment]
Background article: https://blog.adoptopenjdk.net/2020/06/adoptopenjdk-to-join-the-eclipse-foundation/

**Comment by alblue** [comment]
Congratulations everyone on making this happen! It's a great place for ~~AdoptOpenJDK~~ Adoptium to live.

**Comment by Dragas** [comment]
Why change the name at all? It's already going to be confusing, like with every name change prior.

**Comment by alblue** [comment]
> Why change the name at all? It's already going to be confusing, like with every name change prior.

As I wrote on InfoQ, essentially it’s a trademark issue. 

https://www.infoq.com/news/2020/06/adoptopenjdk-eclipse-adoptium/

Oracle owns the trademark for OpenJDK (as with javax) and to avoid any possible trademark issues it has to be renamed. I got confirmation from Mike, who is the executive director of the Eclipse Foundation.

**Comment by gdams** [comment]
> Why change the name at all? It's already going to be confusing, like with every name change prior.

As mentioned in the blog post, there is a trademark issue which we wanted to resolve. Trademarks are important and we want to be respectful of that!

**Comment by tellison** [comment]
> Great news!
> 
> By the way, when will `java -version` output and `java.vendor` system property be updated to reflect the _Adoptium_ new name ?
> 
> Will Eclipse IDE be shipped with Adoptium OpenJ9 by default?

@avermeer good questions.  I expect the name will change to reflect the new name, and don't know about what other projects plan to do.  It is very early days for Adoptium and we'll work through all the questions with people as openly as possible on Slack / issues / email.

**Comment by AleksNo** [comment]
Hi, and this is great news. 

But how about the Java SE TCK? Is there an agreement with Oracle that the EF can use those TCKs? On the AdoptopenJdk-website stands that there is no agreement with 'Oracle.

https://adoptopenjdk.net/quality.html

Cheers

**Comment by Vishnu05** [comment]
Great news🎉

**Comment by aahlenst** [comment]
@AleksNo https://projects.eclipse.org/projects/adoptium/governance

**Comment by avermeer** [comment]
Java and Java EE were created by Sun Microsystems, both are moving to Eclipse fundation, otherwise said:

> ### Eclipse
> is the new **Sun**

**Comment by Phillipus** [comment]
"Adoptium"? Sorry, but it sounds like something Lex Luthor would have dreamed up.

**Comment by JacksonBailey** [comment]
> > Why change the name at all? [...]
> 
> [...]there is a trademark issue which we wanted to resolve.[...]

@gdams, is it fair to say that if *(the project formerly known as)* AdoptOpenJDK wasn't moving to the Eclipse Foundation that this was still something coming, at least at some point?

**Comment by aahlenst** [comment]
@JacksonBailey Yes

**Comment by gdams** [comment]
> @gdams, is it fair to say that if (the project formerly known as) AdoptOpenJDK wasn't moving to the Eclipse Foundation that this was still something coming, at least at some point?

Yes 100%, the project has needed to change it's name for a long time.

**Comment by AleksNo** [comment]
Here is an interesting discussion about the "LTS" of the Adoptopenjdk-project:
https://www.reddit.com/r/java/comments/hbywy1/adoptopenjdk_to_join_the_eclipse_foundation/fvbugv8/

Cheers

**Comment by matpag** [comment]
If you are forced to change the name, I think you should at least conserve the "JDK" part somewhere, otherwise a lot of people will be confused.
Something like "AdoptiumJDK"?

**Comment by Phillipus** [comment]
> If you are forced to change the name, I think you should at least conserve the "JDK" part somewhere, otherwise a lot of people will be confused.
> Something like "AdoptiumJDK"?

How about "Eclipsium Adoptium JDKium"? ;-)

**Comment by yamadamn** [comment]
@matpag @Phillipus "JDK" is Oracle's trademark.[1] It's inherited from Sun. So, I think Adoptium can't use the name.
[1] http://tsdr.uspto.gov/#caseNumber=75695723&caseType=SERIAL_NO&searchType=statusSearch

**Comment by smlambert** [comment]
Given the move is nearing completion, will close this issue.  Repository transfer info can be found in: https://github.com/AdoptOpenJDK/TSC/issues/205

**Comment by 0x7d7b** [comment]
> @matpag @Phillipus "JDK" is Oracle's trademark.[1] It's inherited from Sun. So, I think Adoptium can't use the name.
> [1] http://tsdr.uspto.gov/#caseNumber=75695723&caseType=SERIAL_NO&searchType=statusSearch

The official Docker Hub project description still contains the term "OpenJDK": [https://hub.docker.com/_/eclipse-temurin](url)

**Comment by karianna** [comment]
> > @matpag @Phillipus "JDK" is Oracle's trademark.[1] It's inherited from Sun. So, I think Adoptium can't use the name.
> > [1] http://tsdr.uspto.gov/#caseNumber=75695723&caseType=SERIAL_NO&searchType=statusSearch
> 
> The official Docker Hub project description still contains the term "OpenJDK": [https://hub.docker.com/_/eclipse-temurin](url)

We can use the term OpenJDK as our build is a direct derivative (this is deemed fair use)
