### ISSUE TITLE
Promote AdoptOpenJDK Version 14.0.2+12 (GA)

### ISSUE THREAD

**Issue by gdams** [AdoptOpenJDK/TSC#162]
Java Version:
14.0.2+12

JVM:
- [x] OpenJ9
- [x] Hotspot

@AdoptOpenJDK/tsc please can somebody +1 this request?

**Comment by gdams** [comment]
TRSS Link: https://trss.adoptopenjdk.net/buildDetail?parentId=5f0ec52d7eaab3443ca83234&testSummaryResult=failed&buildNameRegex=%5ETest.*

### Test Failures - Hotspot

**Test_openjdk14_hs_sanity.external_x86-64_linux_openliberty-mp-tck**
openliberty_microprofile_tck_0 => long term failure [deep history](https://trss.adoptopenjdk.net/deepHistory?testId=5f0ed8fd7eaab3443ca83f8c) 
Non-blocking, we need to fix external tests (see https://github.com/AdoptOpenJDK/openjdk-tests/issues/1677)

**Test_openjdk14_hs_sanity.openjdk_ppc64_aix**
jdk_util_0 => passed on re-run (see https://github.com/AdoptOpenJDK/TSC/issues/162#issuecomment-658837868)

**Test_openjdk14_hs_sanity.system_aarch64_linux**
MauveMultiThreadLoadTest_0 => long term failure [deep history](https://trss.adoptopenjdk.net/deepHistory?testId=5f0edf597eaab3443ca8494c)
MauveSingleInvocationLoadTest_HotSpot_0 => long term failure [deep history](https://trss.adoptopenjdk.net/deepHistory?testId=5f0edf597eaab3443ca8495f)
MauveSingleThreadLoadTest_HotSpot_0 => long term failure [deep history](https://trss.adoptopenjdk.net/deepHistory?testId=5f0edf597eaab3443ca84938)

**Test_openjdk14_hs_sanity.openjdk_aarch64_linux**
jdk_util_0 => flaky [deep history](https://trss.adoptopenjdk.net/deepHistory?testId=5f0edf567eaab3443ca848de)
jdk_lang_0 => flaky [deep history](https://trss.adoptopenjdk.net/deepHistory?testId=5f0edf567eaab3443ca848e3)

**Test_openjdk14_hs_special.functional_x86-64_linux**
MBCS_Tests_formatter_zh_CN_linux_0 => long term failure [deep history](https://trss.adoptopenjdk.net/deepHistory?testId=5f0ed87a7eaab3443ca83d58)
MBCS_Tests_formatter_ko_KR_linux_0 => long term failure [deep history](https://trss.adoptopenjdk.net/deepHistory?testId=5f0ed87a7eaab3443ca83d11)
MBCS_Tests_formatter_zh_TW_linux_0 => long term failure [deep history](https://trss.adoptopenjdk.net/deepHistory?testId=5f0ed87a7eaab3443ca83d9f)
MBCS_Tests_formatter_ja_JP_linux_0 => long term failure [deep history](https://trss.adoptopenjdk.net/deepHistory?testId=5f0ed87a7eaab3443ca83de6)
Non-blocking, 2 are new tests, opened https://github.com/AdoptOpenJDK/openjdk-tests/issues/1732 for further triage

**Test_openjdk14_hs_extended.system_aarch64_linux** => failed in previous release https://github.com/AdoptOpenJDK/TSC/issues/143#issuecomment-600521715
MathLoadTest_all_0 => long term failure [deep history](https://trss.adoptopenjdk.net/deepHistory?testId=5f0edf557eaab3443ca848c4)
LockingLoadTest_0 => long term failure [deep history](https://trss.adoptopenjdk.net/deepHistory?testId=5f0edf557eaab3443ca848c3)

**Comment by smlambert** [comment]
Created https://github.com/AdoptOpenJDK/openjdk-tests/issues/1891 for Mauve failures (and added to top priorities), we should also do same for any other failures that do not already have an issue (jdk_util/MathLoadTest_all/LockingLoadTest failures).

jdk_lang issue on aarch64: https://github.com/AdoptOpenJDK/openjdk-tests/issues/1878 
jdk_util / Zip64SizeTest on aix: https://github.com/AdoptOpenJDK/openjdk-tests/issues/1879

**Comment by smlambert** [comment]
Rerun grinder for jdk_util / FJExceptionTableLeak on AIX failure is here: https://ci.adoptopenjdk.net/job/Grinder/3593 (10x running just that test class), no issue created for this failure yet. **Update**: all 10 test runs pass in the Grinder job, so its either a one-off or very intermittent failure.

Still need to create issues for longstanding failures MathLoadTest_all (also fails on jdk11, so can share an issue, if its same failure expression) and LockingLoadTest.  **Update**: thanks @d3r3kk for creating issues for these long-standing failures (see [LockingLoadTest failure issue](https://github.com/AdoptOpenJDK/openjdk-tests/issues/1892) and [MathLoadTest_all failure issue](https://github.com/AdoptOpenJDK/openjdk-tests/issues/1893) respectively.

**Comment by smlambert** [comment]
Build 261 / OpenJ9 [jdk-14.0.2+12_openj9-0.21.0 pipeline link](https://trss.adoptopenjdk.net/buildDetail?parentId=5f0f115e7eaab3443ca86a6a) and [Grid view](https://trss.adoptopenjdk.net/resultSummary?parentId=5f0f115e7eaab3443ca86a6a)

Failed jobs/tests:

**Test_openjdk14_j9_sanity.external_x86-64_linux_openliberty-mp-tck**
openliberty_microprofile_tck_0 => long term failure [deep history](https://trss.adoptopenjdk.net/deepHistory?testId=5f0f3f107eaab3443ca8c7eb)
Non-blocking, we need to fix external tests (see https://github.com/AdoptOpenJDK/openjdk-tests/issues/1858)

**Test_openjdk14_j9_sanity.perf_x86-64_windows** - https://ci.adoptopenjdk.net/job/Test_openjdk14_j9_sanity.perf_x86-64_windows/135/console - machine in bad state, workspace either not cleaned up or has processes left on it, as test job is unable to clone test material (as 15:20:00  mv: cannot move 'openj9/test/functional/CacheManagement' to 'functional/CacheManagement': Directory not empty messages) - will rerun on different machine here: https://ci.adoptopenjdk.net/job/Test_openjdk14_j9_sanity.perf_x86-64_windows/138/ - all pass

**Comment by sxa** [comment]
I think we can safely close this instead of bumping it between iterations since we're not going to be doing any more work on JDK14
