### ISSUE TITLE
Promote AdoptOpenJDK Version jdk8u262-b10

### ISSUE THREAD

**Issue by smlambert** [AdoptOpenJDK/TSC#163]
Java Version:
jdk8u262-b10

JVM:
- [x] OpenJ9
- [x] Hotspot

@AdoptOpenJDK/tsc please can somebody +1 this request?

**Comment by smlambert** [comment]
OpenJ9 jdk8u262-b10_openj9-0.21.0 (pipeline [1172](https://trss.adoptopenjdk.net/buildDetail?parentId=5f0f11507eaab3443ca86a68)):

Test_openjdk8_j9_special.openjdk_ppc64le_linux - fails with https://github.com/AdoptOpenJDK/openjdk-tests/issues/1894, rerun of job here: https://ci.adoptopenjdk.net/job/Test_openjdk8_j9_special.openjdk_ppc64le_linux/179/ - all pass

Test_openjdk8_j9_extended.system_x86-64_windows - 1 failure / [ConcurrentLoadTest_0 fails](https://trss.adoptopenjdk.net/output/test?id=5f0f8b777eaab3443caa1c5d) - known issue considered test issue https://github.com/AdoptOpenJDK/openjdk-tests/issues/1881, investigation in https://github.com/eclipse/openj9/issues/4277, non-blocking

**Comment by gdams** [comment]
TRSS Link: https://trss.adoptopenjdk.net/buildDetail?parentId=5f0ee2267eaab3443ca84fc5&testSummaryResult=failed&buildNameRegex=%5ETest.*

### Test Failures - Hotspot

**Test_openjdk8_hs_sanity.external_x86-64_linux_openliberty-mp-tck**
openliberty_microprofile_tck_0 => long term failure [deep history](https://trss.adoptopenjdk.net/deepHistory?testId=5f0f67b07eaab3443ca96847) Non-Blocking https://github.com/AdoptOpenJDK/TSC/issues/153#issuecomment-614390641

**Test_openjdk8_hs_extended.system_x86-64_linux**
HCRLateAttachWorkload_0 => Passed on [re-run](https://ci.adoptopenjdk.net/job/Grinder/3601/console)

**Test_openjdk8_hs_extended.system_s390x_linux**
UtilLoadTest_0  => long term failure [deep history](https://trss.adoptopenjdk.net/deepHistory?testId=5f0f1bc97eaab3443ca8738b)

**Test_openjdk8_hs_extended.system_ppc64_aix**
HCRLateAttachWorkload_0 => Passed on [re-run](https://ci.adoptopenjdk.net/job/Grinder/3596/console)

**Test_openjdk8_hs_sanity.system_ppc64_aix**
TestJlmRemoteMemoryNoAuth_SE80_0 => Passed on [re-run](https://ci.adoptopenjdk.net/job/Grinder/3599/console)

**Test_openjdk8_hs_sanity.external_x86-64_linux_thorntail-mp-tck**
thorntail_microprofile_tck_0 => long term failure [deep history](https://trss.adoptopenjdk.net/deepHistory?testId=5f0f67bd7eaab3443ca968b8) Non-Blocking https://github.com/AdoptOpenJDK/TSC/issues/153#issuecomment-614390641

**Test_openjdk8_hs_extended.system_x86-64_mac**
HCRLateAttachWorkload_0 => long term failure [deep history](https://trss.adoptopenjdk.net/deepHistory?testId=5f0efbc77eaab3443ca861da)

**Comment by smlambert** [comment]
+1 to publish, created https://github.com/AdoptOpenJDK/openjdk-tests/issues/1897 to capture UtilLoadTest failure in an issue.

**Comment by gdams** [comment]
aarch64 linux:

TRSS Link: https://trss.adoptopenjdk.net/buildDetail?parentId=5f1099157eaab3443caaffca&testSummaryResult=failed&buildNameRegex=%5ETest.*

**Test_openjdk8_hs_extended.system_aarch64_linux**
HCRLateAttachWorkload_0 => long term flaky failure

**Comment by smlambert** [comment]
+1 to publish
