### ISSUE TITLE
Retrospective for July 2020 releases

### ISSUE THREAD

**Issue by gdams** [AdoptOpenJDK/TSC#164]

**Comment by karianna** [comment]
aarch git mirror jobs still fail due to shenandoah tags coming in and need a manual tidy up each time

**Comment by adamfarley** [comment]
Note: Any unresolved actions have been folded into the next retrospective for review. [Link.](https://github.com/adoptium/adoptium/issues/77)

If any have been unintentionally missed, feel free to add them.
