### ISSUE TITLE
Add OpenJDK port for Linux/x64 with musl

### ISSUE THREAD

**Issue by aahlenst** [AdoptOpenJDK/TSC#168]
[Portola](https://openjdk.java.net/projects/portola/) (porting OpenJDK to Linux/x64 with musl instead of glibc) seems to approach the finish line: [JEP 386](https://openjdk.java.net/jeps/386) is now a candidate and [Oracle/OpenJDK has started to offer builds for Alpine beginning with 16](http://jdk.java.net/16/). This means it is (a) time for the TSC to formally vote whether we want to add that port and (b) start coordinating the work to get it done (under the provision that the TSC approves).

Required work:

* [x] Build and produce binary tarballs of 16 and newer on Alpine/x64 with musl https://github.com/AdoptOpenJDK/openjdk-build/pull/2026
* [x] Mirror https://github.com/openjdk/portola into AdoptOpenJDK
* [x] Create docker image for build/test https://github.com/AdoptOpenJDK/openjdk-infrastructure/pull/1496
* [ ] Test 16 and newer on Alpine/x64
* [ ] Add separate Docker images of Alpine/x64 with OpenJDK with musl (we already have a version with glibc) 
* [ ] Create APK for Alpine/x64
* [ ] Create package repository for Alpine/x64 if package cannot be integrated into [Alpine's community repository](https://wiki.alpinelinux.org/wiki/Enable_Community_Repository)

**Comment by gdams** [comment]
Mirrored into https://github.com/AdoptOpenJDK/openjdk-portola

**Comment by gdams** [comment]
> Add separate Docker images of Alpine/x64 with OpenJDK with musl (we already have a version with glibc)

@aahlenst to this point, I think that with JDK15+ we should just ship a musl image for alpine (no glibc version).

CC @dinogun??

**Comment by gdams** [comment]
https://openjdk.java.net/jeps/386 has now been marked as a Candidate for JDK16

**Comment by gdams** [comment]
builds are now being produced: https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk/job/jdk-alpine-linux-x64-hotspot/

I'll now work with @smlambert to enable testing

**Comment by eshepelyuk** [comment]
Hi all
What is a current milestone for Docker images to be publicly available at Dockerhub ?

**Comment by karianna** [comment]
I think the TSC issue can be closed as we've created the issue on the docker repo.  Copying the checklist....
