### ISSUE TITLE
Please add me to AdoptOpenJDK Organization

### ISSUE THREAD

**Issue by sachinp97** [AdoptOpenJDK/TSC#172]

**Comment by karianna** [comment]
@sachinp97 - Hi Sachin, what area of Adopt are you looking to contribute towards?

**Comment by sachinp97** [comment]
Hi Martijn, Thanks for response, I just joined group on slack and looking to contribute towards openjdk-build and/or openjdk-infrastucture.
Please feel free to add me to the group you think is a good starting point.

**Comment by karianna** [comment]
Hi @sachinp97 - sure thing, I'll get you added to the GetOpenJDK general group to start with.  Please say Hi on Slack and we'll get you started!
