### ISSUE TITLE
Logo/Branding usage permission request

### ISSUE THREAD

**Issue by tushev** [AdoptOpenJDK/TSC#173]
Hello,

I'm going to release next version of my update tool, and for it I'd like to formally ask for permission for:

1. Use of brand colors in the app - as stated on https://adoptopenjdk.net/logos.html
2. Use of Adoptium logo in the app:
![image](https://user-images.githubusercontent.com/18406797/92939471-4a163680-f467-11ea-9218-5dca622e174c.png)
Sure, app package includes such statements as `The author is not affiliated with or endorsed by Eclipse Adoptiuum /  AdoptOpenJDK projects. 'AdoptOpenJDK' part of the name is used on fair use conditions, as this app works with Eclipse Adoptiuum / AdoptOpenJDK releases.` 
3. Partial re-use of Adoptium logo in tool's logo/icon:

![aojdk-update-watcher+ 512](https://user-images.githubusercontent.com/18406797/92939242-f7d51580-f466-11ea-99cd-405b9b8bb32e.png)

**Comment by tellison** [comment]
Hi @tushev .  Thanks for checking with us.

Use of the logo as depicted in the app screen shot (your (2) above) is fine.  That fits in with the expectations described on the project logo reuse page.

The partial reuse in your logo/icon (your (3) above) will need an ok at a TSC meeting as it is a modification of our logo.  I can add it to the next TSC agenda, and we usually meet weekly so hopefully you will get an answer soon.

**Comment by tushev** [comment]
@tellison great, thanks! Will look forward to it.

**Comment by karianna** [comment]
@tushev - No objections raised by the TSC.

Please note that once we move to the Eclipse Foundation you'd need to change again and abide by Eclipse's Branding guidelines.

**Comment by tushev** [comment]
@karianna Thank you!!

.

> Please note that once we move to the Eclipse Foundation you'd need to change again and abide by Eclipse's Branding guidelines.

Then I have one more question - despite I use AdoptOpenJDK logo, currently my updater uses `Eclipse Adoptium (AdoptOpenJDK)` or `Eclipse Adoptium` everywhere as target product name, like:
![image](https://user-images.githubusercontent.com/18406797/93562086-c98f9280-f99e-11ea-99d2-84652b7f8d57.png)
![image](https://user-images.githubusercontent.com/18406797/93562148-ef1c9c00-f99e-11ea-886c-41d91553c0c9.png)
![image](https://user-images.githubusercontent.com/18406797/93562131-e330da00-f99e-11ea-90e5-c9ed792730b7.png)

Is it OK, or currently it's better to stick to `AdoptOpenJDK` name only - until you move?

(btw, is there any deadline for transition?)

**Comment by aahlenst** [comment]
There is no product called Eclipse Adoptium, at least not yet.
