### ISSUE TITLE
Add code of conduct

### ISSUE THREAD

**Issue by M-Davies** [AdoptOpenJDK/TSC#175]
See https://adoptopenjdk.slack.com/archives/C09NLQQAV/p1600680283015200?thread_ts=1600680283.015200&cid=C09NLQQAV

At present, we don't have a clear code or conduct for contributors. We should add one to keep this repo consistent with other Adopt projects.

**Comment by hendrikebbers** [comment]
Eclipse CoC: https://www.eclipse.org/org/documents/Community_Code_of_Conduct.php

**Comment by hendrikebbers** [comment]
Eclipse CoC is based on this one: https://www.contributor-covenant.org/version/1/4/code-of-conduct/

Maybe we can just use the 1.4 version of www.contributor-covenant.org since the changes for Eclipse would be minimal or non existing.

**Comment by smlambert** [comment]
+1 to your suggestion @hendrikebbers (v1.4 of contributor-covenent due to it being the basis of the Eclipse one sounds good).

**Comment by jerboaa** [comment]
> Eclipse CoC is based on this one: https://www.contributor-covenant.org/version/1/4/code-of-conduct/
> 
> Maybe we can just use the 1.4 version of [www.contributor-covenant.org](http://www.contributor-covenant.org) since the changes for Eclipse would be minimal or non existing.

+1 @hendrikebbers 

That or the Eclipse CoC directly. I'm fine with either.

**Comment by gdams** [comment]
We will revisit when we move to Eclipse

**Comment by tellison** [comment]
Just to be clear, this is closed in terms of creating an AdoptOpenJDK-specific CoC, and we commit to adhere to [the Eclipse CoC](https://www.eclipse.org/org/documents/Community_Code_of_Conduct.php) now and in the future as we move into the Foundation proper.
