### ISSUE TITLE
Enact a policy that AdoptOpenJDK only builds from secure code streams of OpenJDK

### ISSUE THREAD

**Issue by tellison** [AdoptOpenJDK/TSC#18]
To ensure that AdoptOpenJDK is providing high quality and trusted binaries, the project should have a policy of only promoting binaries based upon **release quality**, **actively maintained** source code projects.  In particular, the source must be maintained with respect to security fixes.

Promoting binaries means making them prominent on the website, and listing them as available via the API etc.  Once a code stream is no longer being actively maintained, our builds of those code bases should be archived or moved to an area of the website that clearly identifies the builds as old (and possibly insecure).

AdoptOpenJDK will build pre-release code streams that are still in development in their source projects, and these will be identifiable on our website as "development drivers", or "non-release quality" builds.  They are to be distinguished from the promoted binaries.  These pre-release builds allow developers and early adopters to give feedback to the source projects.

Practically speaking, once OpenJDK 8, OpenJDK 9 and OpenJDK 10 etc. are no longer receiving security fixes via [the JDK Updates project](http://openjdk.java.net/projects/jdk-updates/), AdoptOpenJDK should stop building and promoting binaries from those source code streams.

**Comment by gdams** [comment]
related to https://github.com/AdoptOpenJDK/openjdk-website/issues/236

**Comment by DanHeidinga** [comment]
This seems reasonable.  If a JDK builder was willing to backport the security fixes to their own repos but wasn't able to do it through the JDK Updates project, would there still be a path for them to be promoted as secure?

**Comment by tellison** [comment]
@DanHeidinga yes.  I was trying to use enough weasel words around "source code projects" to allow for any location to be hosting the secure OpenJDK-based source code, the Eclipse OpenJ9 JVM, the DCEVM, SAP Machine's clone, etc, **and** include our dependencies too.

So, for example, if the Eclipse OpenJ9 related repositories for OpenJDK had supported secure code that was not at OpenJDK, then we'd still build and promote those binaries.

Ultimately the TSC have to decide if we believe a source code maintainer that their project is being maintained and secure, but I don't expect that will be an issue.

**Comment by karianna** [comment]
I commented on the website issue.  I'm OK with us having an unsupported category or even dropping releases back to a nightly status if they're not deemed PRD quality.  I'm definitely not OK with removing them entirely.

**Comment by tellison** [comment]
@karianna I suggest they would not be nightlies, but simply moved into our archive of previous releases, and thereby not recommended for download due to known issues (bugs & security vulnerabilities).

Some of the previous releases got into the archive because a newer release of that version was available (containing fixes to that version), some got there because the code stream became unsupported (in preference to a newer version stream).

**Comment by karianna** [comment]
@tellison That sounds reasonable to me.  We can add extra Ux/UI in that archive section for easier searching later.

**Comment by karianna** [comment]
Complete at Eclipse Adoptium
