### ISSUE TITLE
Establish criteria for inclusion / exclusion of various platform/version builds

### ISSUE THREAD

**Issue by smlambert** [AdoptOpenJDK/TSC#186]
We currently have a very broad set of platforms/versions/impls that we build and test at the project.  It will be useful to have a set of guidelines that we use to determine if we should be including or removing builds from our project.  This issue is intended to serve as an open discussion of what various criteria we may use to determine adding or removing various builds from our project.

**Criteria can include but not limited to:**
- community requests (what is the community asking for) 
- downloads (what is the community actually using/downloading) - as tracked through the API/[dashboard](https://dash.adoptopenjdk.net/)
- availability and ease of use of machine resources 
- availability of human resources for upkeep, triage, maintenance
- sponsorship (option for people to give $$ in return for builds on less 'popular' platforms that do not meet other criteria)
- state/health of the build (how many extra changes off of the src branch in order to run successfully)

We need to also take into account the intended upcoming move to Eclipse foundation, where our ability to run compliance tests on the platform needs to also be considered (re: machine/human resource and effort).

If there are other considerations that are missing, please add as comments to this discussion.

**Comment by tellison** [comment]
Thanks for laying out that set of criteria @smlambert .  They all look reasonable.

The additional one I might suggest is that we may choose to include "up and coming" platforms where there isn't a specific demonstrated usage at the moment, but fits within the "community requests" as a future platform.  Examples would be RISC-V/Linux, aarch64/Win, and M1/OSX.  They variously have interests from sponsors, community, and potential users where we may need to do some speculative work on those platforms ahead of seeing an uptake.

All these criteria are judgement calls about relative importance.  As any one of these criteria fails to be met for a platform combination it becomes increasingly costly or pointless to continue releasing on that platform.  The real challenge will be to know when to stop (or more optimistically, when to start a new one!). I think that is based upon considering our resources (money, machines, people) and seeing what we can cover with the resources we have got.  That'll just be somebody raising the red flag and saying - is it time to stop doing this? as was done for #218.

**Comment by karianna** [comment]
Adoptium has a policy in place
