### ISSUE TITLE
AdoptOpenJDK compatible with TCK 

### ISSUE THREAD

**Issue by Jan-Pleva** [AdoptOpenJDK/TSC#187]
Hello,
I have question, why AdoptOpenJDK is still not compatible with TCK (Java SE Technology Compatibility Kit )?
We would like to use AdoptOpenJDK for Liferay, but there is requirement TCK compatibility.

https://help.liferay.com/hc/en-us/articles/360028982631-Liferay-DXP-7-2-Compatibility-Matrix

@AdoptOpenJDK/tsc please can somebody +1 this request?

**Comment by aahlenst** [comment]
Oracle does not permit claiming compatibility with the TCK without running the binaries through the TCK. We are not allowed to run the TCK on our binaries.

However, I'd be suprised if Liferay doesn't work flawlessly with AdoptOpenJDK.

Eclipse Adoptium will only provide TCK-certified binaries (see https://projects.eclipse.org/projects/adoptium/governance). There is no ETA for binaries released by Eclipse Adoptium

**Comment by tellison** [comment]
@Jan-Pleva the reason that AdoptOpenJDK builds are not tested with the TCK is described on our website here (https://adoptopenjdk.net/quality.html#jck).

As part of our move to Eclipse we have been working with the Eclipse Foundation for them to become licensees of the TCK.

**Comment by Jan-Pleva** [comment]
@aahlenst The problem is that if we will run Liferay on Adopt and some problem will appear, Liferay will not give us support, because in their requirements was TCK compatibility... :/

@tellison Of course I read that website, but it still not clear to me, why Zulu or Corretto have already TCK and Adopt don't.
Is there technical problem? political? finance? priority? or why?

**Comment by tellison** [comment]
Not sure I can state it any more clearly than:

> the London Jamocha Community CIC (aka LJC) has not been able to reach an agreement with Oracle to use the Java SE Technology Compatibility Kit (TCK) under the terms of the OpenJDK Community TCK License Agreement (OCTLA)

as I say, the Eclipse Foundation is now working with Oracle on acquiring a license to their tests.

If Liferay have that as a requirement for support then you will have to discuss that with Liferay.

**Comment by Jan-Pleva** [comment]
@tellison ok. Thank you.
Hopefully it won't take too long.
I'll check the status after a while.

**Comment by vijaya-lakshmi-venkatraman** [comment]
Hi
I still see the below in their [website](https://adoptopenjdk.net/quality.html)

>the London Jamocha Community CIC (aka LJC) has not been able to reach an agreement with Oracle to use the 
> Java SE Technology Compatibility Kit (TCK) under the terms of the OpenJDK Community TCK License Agreement (OCTLA)

however, I can also see in [this](https://blog.adoptopenjdk.net/2021/08/goodbye-adoptopenjdk-hello-adoptium/) link that Temurin Binaries will pass Java SE TCK & AQAVit.

So can I assume that AdoptiumJDK is TCK compliant now?

**Comment by karianna** [comment]
@vijaya-lakshmi-venkatraman We have moved to adoptium.net as Eclipse Temurin builds which are TCK compliance yes.
