### ISSUE TITLE
Clarify role of JCK Certification in the Release process

### ISSUE THREAD

**Issue by tellison** [AdoptOpenJDK/TSC#19]
This issue is an attempt to achieve consensus on the role of the Java Compatibility Kit (JCK) at AdoptOpenJDK.

The AdoptOpenJDK project mission is to provide free, open, and audit-able resources for the community to build, test, and release OpenJDK-based implementations of Java SE.

## Openness

While it is understood that there are some secrets maintained by a subset of our community (e.g. machine administrator passwords), we aim to keep the vast majority of our resources open to everyone.

This enables and encourages broad community participation, enables scrutiny of our processes, and allows others to easily reproduce the process for themselves.

## Experimental, Nightly, and Release builds

Some of the source code streams that we build are development streams, and we publish these as nightly builds.  We also build experimental code streams (such as Amber), and publish those with sufficient caveats to end users.

When we build code streams that are declared stable, release quality source by upstream projects, we will build and test them with a view to marking the binaries as releases to our end users.

Even when using a release quality code stream we make choices that affect the final binary, such as details of the build tool chain, auxiliary libraries, supporting files, etc.  These are specific to AdoptOpenJDK, and all these choices are visible in our open build process.

There is a quality implication to the designation of experimental, nightlies, and releases that we embody in our processes and convey to our end users.

## Determining Quality

When we test our binaries, we do so using some open source tests from OpenJDK, some from Eclipse, some that we maintain within the AdoptOpenJDK project ourselves, etc.  These tests cover functional behaviour (does it do what is expected?), system behaviour (do applications run as expected on this binary?), and regressions (are bugs we fixed earlier still fixed in this binary?).   We also test (or will test) the non-functional behaviour, such as performance and memory usage etc. of our binaries.

We are [in the process of defining a pipeline of tests](https://github.com/smlambert/openjdk-tests/blob/f854db9c61fe22ff5acf12b9bb8ec19bb558f6ba/README.md) for binaries to be denoted as nightlies and releases.

Once a binary passes our definition of "release quality" it can be designated as such in our repository and on our website.  We encourage non-technical end users to pick up release quality builds.

## The JCK

The JCK is a proprietary test suite, [accessible under license from Oracle](http://openjdk.java.net/groups/conformance/JckAccess/index.html).

The role of the JCK is not to determine _quality_, but rather to provide a binary indication of compatibility with the Java SE specification.  As such, the JCK only tests functional behaviour, and only such functional behaviour that is given in the Java specification.

The [JCK license section 1.12](http://openjdk.java.net/legal/OCTLA-JDK9+.pdf) states this scope of usage as:
> [The JCK is provided] so that Licensee may determine if its Implementation is compliant with the Specification

Furthermore, licensees of the JCK cannot make any statement about comparative compatibility.  The [JCK license section 2.0 (b)](http://openjdk.java.net/legal/OCTLA-JDK9+.pdf) gives **disallowed** examples:
> for example, a claim either that the Licensee Implementation is “90% compatible” or that the Licensee Implementation is “more compatible” than another implementation

These restrictions (agreement to OCTLA terms, scope of JCK usage, openness of tests source code, reporting of partial results) means that the JCK cannot be an **open** part of the AdoptOpenJDK project.

We value the JCK compatibility mark.  Indeed, we have a private team repository, private Slack channel, and private Jenkins instance to ensure we honour our obligations under the JCK license, so that we can run the JCK and demonstrate conformance to the Java SE specification.

## Releases and the JCK

So bringing these two threads together.  AdoptOpenJDK must be able to define release quality code using our open, inclusive process.  When we declare a release we are stating that the code is ready for 'production usage' - that is to say, it behaves exactly as we would expect an OpenJDK binary to behave.

We will use our private JCK processes to indicate which releases have passed the relevant JCK check.  We are not planning on running the JCK on nightlies and experimental source streams (though we are entitled to do so) simply due to the resources required; but we do intend to run the JCK on each release.

Note the distinction between making the JCK a gating factor to declaring a release, and JCK testing a release.  At AdoptOpenJDK we avoid defining our release process to include using proprietary code, run in a hidden environment; that doesn't fit with our project ethos.

## On a Practical Note

Of course, we won't do anything to the code on our build system that we expect would jeopardise a release passing the JCK.  We want our releases to be compatible to the specification!

We will re-spin a release if it turns out that it fails the JCK, including future JCK releases for each version; and we may choose to run some JCK tests in the background, in addition to our own testing pipeline, to ensure that we are not taken by surprise.

Running the entire JCK is not trivial.  On Slack, Simon (@lumpfish) estimated that three code streams (two Long Term Support code streams, plus one Short Term Supported code stream), released monthly on seven platforms would take 3 x 12 x 7 = 252 days of effort per year for the manual tests alone!  The automated tests would take additional time.

Realistically, where users are looking for secure, supported releases we need a way to include a fix quickly from an upstream source project, and get that fix out without multiple days delay.  As mentioned above, we would evaluate any such changes to be confident that they won't break the JCK testing, and of course we will not display the conformance check mark on the binary until it has actually passed the JCK test.

**Comment by karianna** [comment]
@tellison Great summary thanks!  I'm concerned that we could (and will) confuse users by potentially providing a N.x.x release with the JCK passing, provide a N.x.x+1 release (for an emergency fix) without the JCK mark (until some arbitrary later point).  I'm still more comfortable with _"If we're JCKing a particular platform / variant / version then we should always do so for subsequent releases of that platform / variant / version"_  Yes this can delay patches going out and is an increased resource cost, but it matches what existing commercial vendors do today and therefore I think what user expectations are.

**Comment by tellison** [comment]
@karianna please can you expand upon the source of confusion?

Dear user:
- If a build is marked with the JCK check mark then we have run the JCK test on it and it has passed.
- If a build does not have the JCK check mark, then it's JCK pass status is unknown.
- We don't denote builds that are known to fail the JCK (perhaps we should!)

**Comment by sxa** [comment]
I believe @karianna's concern is whether we release an update (e.g. new quarterly level) and don't declare it JCK compliant initially, therefore we'll have superceded a JCK compliant (production ready!) release with one that isn't unless we delay til JCK testing is repeated, which wouldn't be ideal for an end user looking to run out stuff in production

**Comment by karianna** [comment]
@sxa555 That's the use case that concerns me yes.

**Comment by DanHeidinga** [comment]
This is the key point to me:

> Note the distinction between making the JCK a gating factor to declaring a release, and JCK testing a release. At AdoptOpenJDK we avoid defining our release process to include using proprietary code, run in a hidden environment; that doesn't fit with our project ethos.

We want every build to be JCK'd but with limited machines and people to run the manual tests, that isn't practical.  @tellison's suggestion to treat the JCK as an extra mark of distinction ("conformance") on builds that have passed Adopt's open quality bar is a compelling path forward.  

Separating quality from conformance allows the community to know which builds are good for production even when JCK test may lag slightly.

**Comment by tellison** [comment]
@sxa555 @karianna 

>  we'll have superceded a JCK compliant (production ready!) release with one that isn't

I'm still failing to see the fundamental problem with that scenario.  Maybe you know more about what end users read into the certification mark than I do!

Assuming the "one that isn't" refers to "JCK compliant", and not to "production ready".  As I write above, the two are distinct.  Our release *will* be production ready before being JCK compliant.

**Comment by tellison** [comment]
@DanHeidinga  Agreed.  The JCK is used for spec conformance testing, not measuring the production quality of an implementation.

**Comment by lumpfish** [comment]
I guess a user might ask "how can you assert that a build is production ready if you are not certain that it conforms to the Java spec?".

**Comment by tellison** [comment]
@lumpfish We point them to the barrage of tests that we put the binaries through that are specifically designed to determine production ready qualities.

Just to be clear, I'm not suggesting that we play fast and loose with spec compliance; but for all the reasons I wrote above, passing the JCK is not a necessary step for a binary to become a release from AdoptOpenJDK.

**Comment by karianna** [comment]
Closing for now as we at an impasse on the JCK for now.
