### ISSUE TITLE
Proposal: A formalized "new build" framework

### ISSUE THREAD

**Issue by adamfarley** [AdoptOpenJDK/TSC#191]
**Summary**
A framework to cover the addition of new builds to Adopt jenkins.

**Details**
To include an agreement on the following:
- How such a build should be proposed, including:
  - Minimum data requirements
  - Location of proposal issue
  - Template?
- The prerequisites for approval, including:
  - A list of details to be approved (platforms, versions, VMs, frequency of build, testing, total time cost by platform, POCs, implementation champion, releases if any, etc)
  - The minimum amount of testing for the build to be declared "good", or published at all each day/week.
  - Method of approval (number of approvers, collective TSC approval, etc)
- The follow-up, such as:
  - When will we review the build for usefulness?
  - Who will monitor these builds for quality, and how?

Discussion encouraged.

**Comment by aahlenst** [comment]
Context: This popped up [while discussing the addition of Amber builds](https://github.com/AdoptOpenJDK/openjdk-build/issues/251). The objective is to ensure that we can handle additional builds (no matter whether they are preview builds or some other kind of builds), that it's clear what we expect and others can expect from us.

**Comment by sxa** [comment]
At the moment I'd avoid adding anythig to the production pipelines until we have determined the rules of engagement with the move to Adoptium.

**Comment by smlambert** [comment]
Related: https://github.com/AdoptOpenJDK/TSC/issues/186

**Comment by karianna** [comment]
temurin-build docs cover this.
