### ISSUE TITLE
Migrate JDK tip mirror to skara

### ISSUE THREAD

**Issue by gdams** [AdoptOpenJDK/TSC#192]
We currently mirror jdk tip from mercurial. I propose moving the mirror to Skara (same as 15 and 16). We should archive the repo and setup a fresh mirror

**Comment by jerboaa** [comment]
+1 on using the git repo upstream as source for the mirror. Frankly, is there any other way? The [HG repo](https://hg.openjdk.java.net/jdk/jdk/) is already stale, AFAICS.
