### ISSUE TITLE
Bi-weekly Adoptium Community Call - March 8, 2021

### ISSUE THREAD

**Issue by smlambert** [AdoptOpenJDK/TSC#203]
**Time**

4-5pm GMT (11am-12pm EST/Ontario)

**Location**

https://bluejeans.com/956754991/2833?src=calendarLink

**Overall Purpose**

Mainly to make announcements regarding planned actions that affect the Adopt community
(Emphasis on non-test efforts, as those are covered in AQAvit)

Secondary purposes include debate, discussion, and community socializing.

Call to be recorded for reference, and linked in this issue afterwards.

**Proposed Meeting Agenda**

- A summary on the repo split is requested. How things are split now, any further changes required/planned for near future (@M-Davies or @gdams)

- Summary on OpenJ9 "mixed references" builds - @pshipton ?

- Update on website UX workshop / redesign, logos, marketing materials - @hendrikebbers ?

- Latest update on transition to Eclipse Foundation - @smlambert 
- Items from Adam B.
  - marketplace questions/update/discussion
  - ibm build update/issues
  - ssh cloning
  - ext repo/branch for test
- Update on calendar invites and meeting links to this call going forward 
  - Link to add this [recurring bi-weekly Adoptium Community Call ](https://calendar.google.com/event?action=TEMPLATE&tmeid=MjViajc5a3RxczFlMGNuaXN2OW5paTQ5cmhfMjAyMTAzMDhUMTYwMDAwWiBjX3Vhbm5vdW1zNWhvMG9saGprM3VsZWNka2JjQGc&tmsrc=c_uannoums5ho0olhjk3ulecdkbc%40group.calendar.google.com&scp=ALL)to your calendar
  - Booked using GMT timezone (rather than Canada EST), there is a daylight savings time mismatch coming up... Canadians be aware of the possible shifted meeting start time for the next meeting... 

- Outreachy participation & Quick review "help needed" and "[good first issue](https://github.com/orgs/AdoptOpenJDK/projects/2)" items - @smlambert 

- AOB
- JDK16 release coming up - @lumpfish
  - https://github.com/AdoptOpenJDK/TSC/issues/206
----------------

- potential other topics 
  - co-location lab update - @aahlenst
  - updates on Dragonwell builds 
  - updates on Bisheng-JDK on risc-v builds
 
Notes: 
- Going forward, we can consider hosting a less frequent 2nd call to catch folks in other timezones as needed
- Further agenda items can be added via comments below

**Comment by adamfarley** [comment]
Please can the Eclipse transition update include an update on how they'd like these meetings scheduled?

E.g. An eclipse-provided public calendar, including Google calendar invitation functionality.

P.S. If possible, it'd also be good to get this set up before the next meeting. Let me know if I can help with that.

**Comment by adamfarley** [comment]
**Minutes:**
- Recording began.
- @M-Davies has given a talk on splitting the build repo into build, pipelines, and "openjdk mirror script". "CI Build Farm" may be a 4th.
- @pshipton has given a talk on mixed refs in the openj9 vm.
- @smlambert has given a summary of repos at Adoptium.
- @hendrikebbers has given a talk on the Adoptium logo and the student work.
- @aahlenst has given a talk about the colocation lab, inc a note on Raspberry Pi's.
- @AdamBrousseau raised these topics:
  - marketplace update/discussion
  - ibm build update/issues
    - ssh cloning
    - ext repo/branch for test
- @lumpfish mentioned the upcoming jdk16 release next week (and the proposed plan in https://github.com/AdoptOpenJDK/TSC/issues/206, still looking to get answers to the open questions there)

@smlambert updates on:
- community call in a public calendar, anyone can invite themselves to add to their calendars (use this [link](https://calendar.google.com/event?action=TEMPLATE&tmeid=MjViajc5a3RxczFlMGNuaXN2OW5paTQ5cmhfMjAyMTAzMDhUMTYwMDAwWiBjX3Vhbm5vdW1zNWhvMG9saGprM3VsZWNka2JjQGc&tmsrc=c_uannoums5ho0olhjk3ulecdkbc%40group.calendar.google.com&scp=ALL))
- we are now participating in 3 different programs that brings new collaborators to the project (5 students from canosp.ca for this term, 8 students from ZHAW for 12 weeks starting this week, and we have funding for 2 interns from the Outreachy program for summer term), help wanted to get our "good first issues" list tidied up.

**Actions:** 
- Shelley: Add a discussion issue to TSC repo to discuss options/details of how to incorporate/package marketplace builds 
- all: create new "good first issues" in the repos that you are most active in... the more that candidates have to choose from the better


**Talks Requested:**
- None yet

**Comment by M-Davies** [comment]
> @M-Davies has given a talk on splitting the build repo into build, pipelines, and "openjdk mirror script". "CI Build Farm" may be a 4th.

- Proposed Repo Split Doc -> https://docs.google.com/document/d/1_n7n7yZijdBVLhQcaljogOT-Nd_JJLoCR05JSgkgfOA/edit#
- Split Jenkins Code From openjdk-build issues and tasks -> https://github.com/AdoptOpenJDK/openjdk-build/issues/2455
- Relevant PR to achieve the above -> https://github.com/AdoptOpenJDK/openjdk-build/pull/2463
- Open Issue to Split out the [build-farm](https://github.com/AdoptOpenJDK/openjdk-build/tree/master/build-farm) from openjdk-build to it's own repository (likely next step) -> https://github.com/AdoptOpenJDK/openjdk-build/issues/1108

**Comment by smlambert** [comment]
Link to [recording](https://bluejeans.com/s/k3UHcqRbCl8/) (and attendee list)

Link to next meeting's details and proposed agenda: https://github.com/AdoptOpenJDK/TSC/issues/207
