### ISSUE TITLE
Prepare initial contributions for repositories moving to Eclipse org

### ISSUE THREAD

**Issue by smlambert** [AdoptOpenJDK/TSC#205]
As identified in the [Github repo migration plan](https://docs.google.com/spreadsheets/d/1r9zslP-pZw7-KXR1h-L_BJprvoaAaMqMvRkx5NnpVrI/edit?usp=sharing), there are many repositories to move to Eclipse Foundation (EF).  Each repository requires an CQ created (as described by the [initial contribution doc](https://www.eclipse.org/projects/handbook/#ip-initial-contribution), do not look at this flowchart of [EF legal process](https://www.eclipse.org/legal/EclipseLegalProcessPoster.pdf), it will scare you off from volunteering to create CQs).  This issue is to track that effort and to help divide up the tasks amongst various project leads.

Steps to create a CQ:
1. Go to the project page where the repo will be transferred to (https://projects.eclipse.org/projects/adoptium or https://projects.eclipse.org/projects/adoptium.temurin)
2. Under the Committer Tools on the right side of the page, click on Intellectual Property -> Create a Contribution Questionnaire
3. Fill in the (very short) form, selecting `Project content`, Name: `Initial contribution of xxxxx repo`, Description: `Initial contribution of xxxxx repo and any extra info you may want to capture in the description`, Reason: `Initial contribution to a new project`, Contribution record: `<Link to original github repo>`, Cryptography: `No` (in all cases I believe), Authors: `X number of contributors listed at <link to original github repo contributors page>` (example: https://github.com/AdoptOpenJDK/openjdk-dashboard-v2/graphs/contributors).
4. Continue -> Finish
5. Click on the link to the newly created CQ
6. Attach a zip file containing the contents of the original repo

That is all that is needed to create the CQ.  Here is a [short 2 minute recording](https://drive.google.com/file/d/1_QmCUd1FHFWVOGAekqy7QnouxxYb7N18/view?usp=sharing) of the process for further clarity.  

CQs created for repos destined for projects: 
-------

**Adoptium**: (owners @gdams)
See [STATUS of Adoptium CQs](https://dev.eclipse.org/ipzilla/buglist.cgi?component=adoptium).
- [x] openjdk-website (CQ not needed) -> https://github.com/adoptium/adoptium.net - completed
- [x] blog -> https://github.com/adoptium/blog.adoptium.net - completed
- [x] API -> https://github.com/adoptium/api.adoptium.net - completed
- [ ] docker
- [x] dashboard -> https://github.com/adoptium/dash.adoptium.net - completed
- [x] api-graphql

Any private repos, like Infra-private and secrets should NOT have a CQ created for them, as CQs are public record.

-------

**AQAvit**: (owner @smlambert) 
These are all in process now, see [STATUS of AQAvit CQs](https://dev.eclipse.org/ipzilla/buglist.cgi?component=adoptium.aqavit).
- [x] AdoptOpenJDK/openjdk-tests -> moved to adoptium/aqa-tests - completed
- [x] AdoptOpenJDK/openjdk-systemtest -> moved to adoptium/aqa-systemtest - completed
- [x] AdoptOpenJDK/openjdk-test-tools -> adoptium/aqa-test-tools - completed
- [x] AdoptOpenJDK/STF -> adoptium/STF - completed
- [x] AdoptOpenJDK/TKG -> adoptium/TKG - completed
- [x] AdoptOpenJDK/run-aqa -> https://github.com/adoptium/run-aqa - completed
- [x] AdoptOpenJDK/bumblebench ->adoptium/bumblebench - completed

-------

**Temurin**: (owners @gdams @smlambert)
See [STATUS of Temurin CQs](https://dev.eclipse.org/ipzilla/buglist.cgi?component=adoptium.temurin).
- [x] openjdk-build -> https://github.com/adoptium/temurin-build - completed
- [x] openjdk-mirror-scripts -> https://github.com/adoptium/mirror-scripts - completed
- [x] ci-jenkins-pipelines -> https://github.com/adoptium/ci-jenkins-pipelines - completed
- [x] installer -> https://github.com/adoptium/installer - completed
- [x] jenkins-helper -> https://github.com/adoptium/jenkins-helper - completed
- [x] github-release-scripts -> https://github.com/adoptium/github-release-scripts - completed
- [x] support -> https://github.com/adoptium/adoptium-support - completed
- [x] build-jdk -> https://github.com/adoptium/build-jdk - completed
- [x] infrastructure -> https://github.com/adoptium/infrastructure - completed

-------

**Temurin-compliance**: (owner @smlambert sent FAQ/wiki/docs from private repo directly to Wayne B. for private EF repo)
N/A

-------

Project's PMC will be prompted to approve the CQ, needs only 1 project lead to approve.  Eclipse Foundation IP team gets to work at reviewing contents and will post questions or next actions to the CQ's IPzilla record.

**Comment by aahlenst** [comment]
Not sure it makes sense to move support to Temurin. Already now we get support requests there for almost anything. I assume this will increase with the marketplace.

**Comment by smlambert** [comment]
re: https://github.com/AdoptOpenJDK/TSC/issues/205#issuecomment-790038030, I presume the suggestion is to move the support repo to top-level Adoptium project instead.

I also wanted to discuss the Marketplace notion more, as there are some other questions around what it can become that might imply moving certain repos up to the top-level project, rather than just specific to Temurin (installer and docker as 2 examples).

**Comment by aahlenst** [comment]
> I presume the suggestion is to move the support repo to top-level Adoptium project instead.

Yes.

Rest of discussion here on are we supposed to use the mailing list?

**Comment by smlambert** [comment]
Mailing list is likely best for discussion, the [EF-transition labelled issues](https://github.com/AdoptOpenJDK/TSC/labels/EF-transition) that will be created in this repo are really a way to assign and divide up the tasks.

**Comment by smlambert** [comment]
Apparently the reason that support repo was put into Temurin list, is for ease of transferring issues from repos within a Github organization.

This was discussed in the WG transition meeting today.  There is no actual requirement to have a separate Github org for the different public projects (Adoptium/Temurin/AQAvit), so all repos can be created in an Adoptium Github organization.  This will allow for easy transition of issues across all repos (and be more like what we have today... everything under AdoptOpenJDK github organization).

**Comment by smlambert** [comment]
We will now also like to transfer https://github.com/AdoptOpenJDK/website-adoptium-documentation under the adoptium github organisation, as we will use it to develop our documentation going forward.

Suggest renaming it to documentation as part of the transition under the Eclipse Foundation.  I will initiate the CQ.

**Comment by karianna** [comment]
> We will now also like to transfer https://github.com/AdoptOpenJDK/website-adoptium-documentation under the adoptium github organisation, as we will use it to develop our documentation going forward.
> 
> Suggest renaming it to documentation as part of the transition under the Eclipse Foundation. I will initiate the CQ.

documentation is a pretty generic name - will folks maybe go there for the wrong reasons?

**Comment by smlambert** [comment]
To clarify, it will have all of the documentation for the project (from all the repos) contained within it.  In that case, I am not sure there are wrong reasons... but am open to different naming.

**Comment by karianna** [comment]
OK that makes sense

**Comment by smlambert** [comment]
CQ for website-adoptium-documentation (AsciiDoc documentation project) - https://dev.eclipse.org/ipzilla/show_bug.cgi?id=23763

**Comment by karianna** [comment]
Done
