### ISSUE TITLE
What is the idea about the document PLATFORM_COSTS.md ?

### ISSUE THREAD

**Issue by jabrena** [AdoptOpenJDK/TSC#21]
Hi,

I would like to know what is the idea with this document.

Juan Antonio

**Comment by gdams** [comment]
The main point of [PLATFORM_COSTS.md](https://github.com/AdoptOpenJDK/TSC/blob/master/PLATFORM_COSTS.md) is to give people of a rough idea of our build costs when adding new variants. We have had companies and projects approach us asking us to add their variants and so it helps give them a rough guide of the costs entailed.
