### ISSUE TITLE
Retrospective for March 2021 Releases

### ISSUE THREAD

**Issue by adamfarley** [AdoptOpenJDK/TSC#212]
This will be a Slack call after the release, with at least a week of notice in the #Release Slack channel.

A bulleted list of all proposed agenda items in this issue (whether at the top or in a comment) will be created on the day of the call, with a list of actions added at the end.

Edit: The call will take place at 4pm GMT (11:00am Ontario, Canada) on Monday the 12th of April.

**Comment by adamfarley** [comment]
**Actions from the last retrospective:**

**Adam Farley:**

- Create template for future Retrospective issues. ([PR](https://github.com/AdoptOpenJDK/TSC/pull/213))
- Raise TSC issue to discuss having a checklist for release actions. E.g. a checklist of checklists in a TSC template, or some manner of wiki. ([Issue raised](https://github.com/AdoptOpenJDK/TSC/issues/215))
- Speak with Martijn about him raising an issue for "IBM RHEL 6 machine missing some pre-reqs for language tests." (To be discussed [here](https://github.com/AdoptOpenJDK/TSC/issues/207).)
- Speak with Andreas about storing this info in an issue and encouraging folks to use it. (To be discussed [here](https://github.com/AdoptOpenJDK/TSC/issues/207).)

**Andrew Leonard:**

- Raise issue to discuss JTHarness Test Output parameter lengthening. ([Issue raised](https://github.com/AdoptOpenJDK/openjdk-tests/issues/2226))
- Raise issue to cover actions needed for inc weekly tests when testing OpenJ9 milestones. ([Issue raised](https://github.com/AdoptOpenJDK/openjdk-build/pull/2436))

**Comment by aahlenst** [comment]
https://github.com/AdoptOpenJDK/openjdk-build/issues/2524 needs to be addressed. Causes problems all the time. This time it's https://github.com/AdoptOpenJDK/openjdk-installer/pull/298. I usually get the suggestion to check for various name combinations which is just plain bad and does not address the other problems that exist apart from U yes/no.

**Comment by adamfarley** [comment]
Agenda:

- [x] Go over actions from last retrospective
- [x] Close [previous retrospective's issue](https://github.com/AdoptOpenJDK/TSC/issues/195)
- [x] (aahlenst) AdoptOpenJDK/openjdk-build#2524 needs to be addressed. Causes problems all the time. This time it's adoptium/installer#298. I usually get the suggestion to check for various name combinations which is just plain bad and does not address the other problems that exist apart from U yes/no.

**Comment by karianna** [comment]
Retro is done and issues raised so closing.
