### ISSUE TITLE
Not that it is part of this PR, but in the diagram, there is a repo called Email in the Infra section.  Does that exist?  I do not find it in the Github organization.

### ISSUE THREAD

**Issue by karianna** [AdoptOpenJDK/TSC#214]
Not that it is part of this PR, but in the diagram, there is a repo called Email in the Infra section.  Does that exist?  I do not find it in the Github organization.

_Originally posted by @smlambert in https://github.com/AdoptOpenJDK/TSC/issues/208#issuecomment-793858129_

**Comment by gdams** [comment]
it got killed when we moved to gsuite @smlambert

**Comment by smlambert** [comment]
Yep, so I think we should remove it from the [diagram](https://github.com/AdoptOpenJDK/TSC/blob/master/images/Adopt_Build_Farm_Core_Repo_Relationships.png) 
<img width="208" alt="Screen Shot 2021-03-17 at 4 58 19 PM" src="https://user-images.githubusercontent.com/2836948/111537625-0cf66e00-8742-11eb-8a68-9ba1ef17ebb5.png">

**Comment by smlambert** [comment]
maybe not relevant if we don't transfer this repo, but I believe we need something like this in Adoptium, suggestion was to transfer this repo to Adoptium/adoptium
