### ISSUE TITLE
Proposal: To Create a Tick-List Issue Template for Releases

### ISSUE THREAD

**Issue by adamfarley** [AdoptOpenJDK/TSC#215]
**The Problem**

When a release happens, people don't know what parts of a release have been handled, or by whom, unless they ask around.

**The Cause**

The release document is a read-only document, and does not allow a person to track their progress for a specific release.

**The Proposed Solution**

To create checklist/s that can be duplicated and ticked off on a per-release basis.

One option is to move the release steps in [RELEASING.md](https://github.com/AdoptOpenJDK/openjdk-build/blob/master/RELEASING.md) into issue template files in the same repo, and to put links in RELEASING.md that connect to them. 

The logic behind this is to retain information centralization in RELEASING.md, while preventing double-commits (were we to copy the release steps rather than move them).

The debate is open.

**Comment by smlambert** [comment]
Related: https://github.com/AdoptOpenJDK/TSC/issues/178

**Comment by adamfarley** [comment]
> 
> 
> Related: #178

178 looks like an ideal long-term solution to this problem. Will add both to the agenda for the next Adopt Community Call. Could be that this issue (215) would make a good short-term solution, or maybe it's just a duplicate that needs to be closed.
