### ISSUE TITLE
Proposal: Consider adding openjdk-build, ci-jenkins-pipelines and possibly more to good-first-issue initiative

### ISSUE THREAD

**Issue by M-Davies** [AdoptOpenJDK/TSC#216]
See https://github.com/deepsourcelabs/good-first-issue

The large and/or old backlogs of openjdk-build, openjdk-api-v3 and many more show that we might be a bit short on contributors to some parts of the project. To increase Adopt's presence and attract new committers, please consider adding Adopt to this project

**Comment by smlambert** [comment]
I think we should better prepare some good first issues in these repositories and then add them.  Currently we have 50 outreachy applicants looking for good first issues to take on.  Currently, very few issues contain clear enough descriptions at the moment to be able to assign them to new contributors.  

If we want help and new contributors to the project (and we desperately do), then all project leads (@AdoptOpenJDK/tsc) and regular contributors should help to create/describe good first (and second) issues for new contributors.

**Comment by M-Davies** [comment]
I added a few more good first issues to the [project](https://github.com/orgs/AdoptOpenJDK/projects/2) to see if that attracts more interest. My speciality is in openjdk-build, ci and the api (somewhat) however and those repo's are not all that friendly to newcomers at the moment.

**Comment by karianna** [comment]
Over at Adoptium
