### ISSUE TITLE
Bi-weekly Adoptium Community Call - April 5, 2021

### ISSUE THREAD

**Issue by smlambert** [AdoptOpenJDK/TSC#217]
**THIS MEETING is moved to Tuesday, April 6th** to account for Easter Monday for many attendees

**Time**

4-5pm GMT (11am-12pm EST/Ontario)

**Location**

https://bluejeans.com/956754991/2833?src=calendarLink

Add this [recurring bi-weekly Adoptium Community Call](https://calendar.google.com/event?action=TEMPLATE&tmeid=MjViajc5a3RxczFlMGNuaXN2OW5paTQ5cmhfMjAyMTAzMDhUMTYwMDAwWiBjX3Vhbm5vdW1zNWhvMG9saGprM3VsZWNka2JjQGc&tmsrc=c_uannoums5ho0olhjk3ulecdkbc%40group.calendar.google.com&scp=ALL) to your calendar, if you wish.

**Overall Purpose**

Mainly to make announcements regarding planned actions that affect the Adopt community
(Emphasis on non-test efforts, as those are covered in AQAvit call on Wednesdays)

Secondary purposes include debate, discussion, and community socializing.

Call to be recorded for reference, and linked in this issue afterwards.

**Proposed Meeting Agenda** - TBD / topics to be confirmed
- [JDK8 HS on s390 scale-back](https://github.com/AdoptOpenJDK/TSC/issues/218) discussion (5 min) - @adamfarley 
- [Website-adoptium](https://github.com/AdoptOpenJDK/website-adoptium) update (5 min) - @hendrikebbers 
- [Top Priorities](https://github.com/orgs/AdoptOpenJDK/projects/1) (15 min)
  - what issues are missing and should be tagged as top priority?  
  - review existing list 
  - new Adoptium org top-level "Top Priorities" project (related to project mgmt topic)
- Outreachy - @smlambert 
- EF transition update (5 min) - @smlambert 
  - repo transfers - [TSC/205](https://github.com/AdoptOpenJDK/TSC/issues/205)
  - marketplace discussion issue - [TSC/209](https://github.com/AdoptOpenJDK/TSC/issues/209)
  
- Adoptium [API planning](https://github.com/adoptium/api.adoptium.net/pull/1) update  (10 min) - @johnoliver 
- Project Management proposal - [TSC/220](https://github.com/AdoptOpenJDK/TSC/issues/220) (10 min) - @karianna

**Comment by adamfarley** [comment]
Agenda Item: Host a [JDK8 HS on s390 scale-back](https://github.com/AdoptOpenJDK/TSC/issues/218) debate, and find a volunteer to action it.

Also, @smlambert - Since the 5th of April is a holiday for most, what do you think about moving this to the same time on the 6th?

**Comment by adamfarley** [comment]
Agenda item: Decision on the time+day of these meetings in the future.

As the 2nd and 4th meetings after this one fall on a Monday bank holiday (like most annual bank holidays), it's worth discussing a set policy going forwards.

Note: Two suggestions thus far:
- Moving permanently to the same slot on a Tuesday.
- Moving these meetings to Tuesday, but only when the Monday is a bank holiday.

**Comment by M-Davies** [comment]
> Moving permanently to the same slot on a Tuesday.

+1 to this as I often cannot attend Monday meetings due to lectures

**Comment by smlambert** [comment]
Notes from meeting:
- Create an issue in ci-jenkins-pipeline to set test list for jdk8 hs s390x to reduce testing to only sanity.openjdk 
- API planning needs some additional input on what requirements we put on members who wish to be listed in marketplace.  Will we put a requirement that members host their binaries in a github releases repo (or not).  Action: Shelley to add note to https://github.com/AdoptOpenJDK/TSC/issues/209 to solicit more feedback
- Top Priorities list reviewed, removed some stale / not priority items, created and added one for "[Replace Jenkins server](https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/2108)" 
- Project plan proposal discussed, gather more feedback from regular contributors Action: @karianna to put details into a Google doc so people can put comments and we revise it to a set of guidelines based on community feedback
- Plan to move this meeting permanently to Tuesdays same timeslot going forward Action: Shelley to update community calendar

[Recording link](https://bluejeans.com/s/3NrZsbhvXry) for today's meeting

Link to next meeting: https://github.com/AdoptOpenJDK/TSC/issues/221
