### ISSUE TITLE
Bi-weekly Adoptium Community Call - April 20, 2021

### ISSUE THREAD

**Issue by smlambert** [AdoptOpenJDK/TSC#221]
**Time**

Tuesday April 20 4pm-5pm GMT (11am-12pm EST/Ontario)

**Location**

https://bluejeans.com/956754991/2833?src=calendarLink

Add this [recurring bi-weekly Adoptium Community Call](https://calendar.google.com/event?action=TEMPLATE&tmeid=MjViajc5a3RxczFlMGNuaXN2OW5paTQ5cmhfMjAyMTAzMDhUMTYwMDAwWiBjX3Vhbm5vdW1zNWhvMG9saGprM3VsZWNka2JjQGc&tmsrc=c_uannoums5ho0olhjk3ulecdkbc%40group.calendar.google.com&scp=ALL) to your calendar, if you wish.

**Overall Purpose**

Mainly to make announcements regarding planned actions that affect the Adopt community
(Emphasis on non-test efforts, as those are covered in AQAvit call on Wednesdays)

Secondary purposes include debate, discussion, and community socializing.

Call to be recorded for reference, and linked in this issue afterwards.

**Proposed Meeting Agenda** - TBD / topics to be confirmed
- Doodle poll for time slot for this meeting - Adam Farley
- Corporate style guidelines / logo / website look&feel / Adoptium website work with ZHAW students - Hendrik 
- 
- Release week (20 min)- status? any blockers?  Champions named, trialing the checklist template (post-release feedback requested), trialing the new "release summary report" feature in TRSS (post-release feedback requested)
- [Top Priorities](https://github.com/orgs/AdoptOpenJDK/projects/1) review (10 min) - all
  - Usefulness of the current list?  In its current form is it useful?  Urgent items are addressed immediately and do not make it to top priorities.  Top Priorities exists as a way to indicate which non-urgent items are most important to the project.  Do the current issues reflect that?  Are all issues in the top priorities project described well and achievable?

**Comment by adamfarley** [comment]
Proposed Agenda item: To select a time slot for this meeting that people can make.

I've identified three time slots that seem to work for some people, and I've created a Doodle poll around them.

https://doodle.com/poll/397tvu3xkzn2tw64?utm_source=poll&utm_medium=link

I encourage anyone that hasn't chosen an option on the poll to do so. Will add the link to Slack as well.

Note: If we don't find a single time slot that works for everyone, perhaps we can alternate? Either way, please choose all options you can make.

**Comment by smlambert** [comment]
Minutes:
- [Doodle poll](https://doodle.com/poll/397tvu3xkzn2tw64?utm_source=poll&utm_medium=link) for time slot for this meeting - Adam Farley
- Corporate style guidelines / logo / website look&feel / Adoptium website work with ZHAW students, see draft keynote template in community Slack channel, upcoming meeting with Eclipse creative to discuss website design - Hendrik 
- API / maven artifacts - nothing currently blocking ZHAW students - John
- [Top Priorities](https://github.com/orgs/AdoptOpenJDK/projects/1) - how to identify important (not necessarily urgent) issues
  - Usefulness of the current top priorities list in question?  In its current form is it useful?  Urgent items are addressed immediately and do not make it to top priorities.  Top Priorities exists as a way to indicate which non-urgent items are most important to the project.  Do the current issues reflect that?  Are all issues in the top priorities project described well and achievable?  Are pinned issues at the top of each repo more reflective of top priorities?  Should those be reflected in the list?
  - Are there other preferred ways of identifying these issues?  Related to project management.  Let's come back in 2 weeks to the community call with some thoughts regarding best way to manage various components of the project.
  - Other organization level projects include "Good First Issues" which is now actively used for the Outreachy candidates, some work from previous Hacktoberfest to tag "good first issues candidates".  Perhaps can use part of a future community call to identify more and repopulate the "good first issues" list.  We have successfully engaged with various programs to assist in bringing new contributors to the project (CanOSP, Outreachy, Hacktoberfest, ZHAW program and possibly upcoming iJug initiative).  We will continue to seek new programs and to grow our community and contributor base.  So, putting some effort into a set of good first issues and having mentors at the ready will be a good investment.
- Release week - Champions named (Andrew/[openj9](https://github.com/AdoptOpenJDK/TSC/issues/226), George/[hotspot](https://github.com/AdoptOpenJDK/TSC/issues/227)), trialing the checklist template (post-release feedback requested), trialing the new "release summary report" feature in TRSS (post-release feedback requested).  Lot's of prep work has been done.  Still test failures in extended.openjdk, extended.perf though many have been excluded or fixed.  

Meeting [recording link](https://bluejeans.com/s/M7AHUg0OGEh)

Link to next Adoptium community call: https://github.com/AdoptOpenJDK/TSC/issues/228
