### ISSUE TITLE
Test TSC issue assignee editing

### ISSUE THREAD

**Issue by andrew-m-leonard** [AdoptOpenJDK/TSC#223]
Can any assignee edit this issue?
I can edit this!

**Comment by smlambert** [comment]
Assign me

**Comment by smlambert** [comment]
I am release champignon ;)

**Comment by sxa** [comment]
Congratulations

**Comment by lumpfish** [comment]
I can add comments but edit neither the description nor anyone else's comments.

**Comment by tellison** [comment]
The permissions may be different when this migrates from AdoptOpenJDK -> Adoptium

**Comment by sxa** [comment]
@lumpfish Can you now (since I've made you an assignee)?

**Comment by sxa** [comment]
> The permissions may be different when this migrates from AdoptOpenJDK -> Adoptium

Indeed, although the tests will still be useful for next week's release :-)

**Comment by lumpfish** [comment]
I still can't edit the description or the comments.

**Comment by sxa** [comment]
@smlambert Hmmm lumpfish commenting hasn't allowed me to assign him this time.

**Comment by sxa** [comment]
This appears to have reached a conclusion - closing ;-)
