### ISSUE TITLE
Bi-weekly Adoptium Community Call - May 4, 2021

### ISSUE THREAD

**Issue by smlambert** [AdoptOpenJDK/TSC#228]
**Time**

Tuesday May 4, 2021 4pm-5pm GMT (11am-12pm EST/Ontario)

**Location**

https://bluejeans.com/956754991/2833?src=calendarLink

Add this [recurring bi-weekly Adoptium Community Call](https://calendar.google.com/event?action=TEMPLATE&tmeid=MjViajc5a3RxczFlMGNuaXN2OW5paTQ5cmhfMjAyMTAzMDhUMTYwMDAwWiBjX3Vhbm5vdW1zNWhvMG9saGprM3VsZWNka2JjQGc&tmsrc=c_uannoums5ho0olhjk3ulecdkbc%40group.calendar.google.com&scp=ALL) to your calendar, if you wish.

**Overall Purpose**

Mainly to make announcements regarding planned actions that affect the Adopt community
(Emphasis on non-test efforts, as those are covered in AQAvit call on Wednesdays)

Secondary purposes include debate, discussion, and community socializing.

Call to be recorded for reference, and linked in this issue afterwards.

**Proposed Meeting Agenda** - TBD / topics to be confirmed

- Installers - Work from https://github.com/aahlenst/adoptium-packages-linux, and future plans for using this approach

- [The Linter Issue](https://github.com/adoptium/temurin-build/issues/2581) - @M-Davies has been updating (see https://github.com/adoptium/temurin-build/pull/2609)

- [The Alpine Linux Freetype PR](https://github.com/adoptium/temurin-build/pull/2587) - We should ask the community if anyone wants Alpine Linux to continue including a bundled Freetype (which xLinux does not). If nobody has strong opinions here, then this can be a simple notification; future Alpine Linux builds at Adopt will not include a bundled Freetype.

- [The "Reschedule this Meeting" Doodle](https://doodle.com/poll/397tvu3xkzn2tw64?utm_source=poll&utm_medium=link) - Right now it seems that Wednesdays, 3pm-4pm BST (10am-11am Ontario) is the best slot, as almost everyone can attend. However, Vani Chitkara might not be able to make it, and Adam Brousseau is an "if need be". One option is to accept this and hope the affected individuals are able to make it, and another option is to alternate between the Monday and Wednesday slots on the Doodle, ensuring everyone that voted has the opportunity to attend at least once a month. Please debate.

- Eclipse Temurin - Activities to prepare for [first release](https://github.com/adoptium/adoptium/projects/1)

**Comment by gdams** [comment]
@smlambert shall I transfer this to adoptium/adoptium?

**Comment by smlambert** [comment]
@gdam, yes please - we will continue to use this method for organizing/sharing the Community call

**Comment by adamfarley** [comment]
Three items issues recommended for discussion:

- [The Linter Issue](https://github.com/adoptium/temurin-build/issues/2581) - We should discuss this issue to gather any further recommendations for linter modification, so that we can resolve the issue confident that every chance has been given for people to offer their thoughts.

- [The Alpine Linux Freetype PR](https://github.com/adoptium/temurin-build/pull/2587) - We should ask the community if anyone wants Alpine Linux to continue including a bundled Freetype (which xLinux does not). If nobody has strong opinions here, then this can be a simple notification; future Alpine Linux builds at Adopt will not include a bundled Freetype.

- [The "Reschedule this Meeting" Doodle](https://doodle.com/poll/397tvu3xkzn2tw64?utm_source=poll&utm_medium=link) - Right now it seems that Wednesdays, 3pm-4pm BST (10am-11am Ontario) is the best slot, as almost everyone can attend. However, Vani Chitkara might not be able to make it, and Adam Brousseau is an "if need be". One option is to accept this and hope the affected individuals are able to make it, and another option is to alternate between the Monday and Wednesday slots on the Doodle, ensuring everyone that voted has the opportunity to attend at least once a month. Please debate.

**Comment by AdamBrousseau** [comment]
I was wondering if we could talk about installers. Preferably in the first half hour as I'll have to drop at half-past.
https://github.com/aahlenst/adoptium-packages-linux
cc @aahlenst @jerboaa

**Comment by smlambert** [comment]
re: https://github.com/AdoptOpenJDK/TSC/issues/228#issuecomment-830263728 sure thing, will add to top of agenda
FYI @sophia-guo (you may want to also join this meeting for the discusssion)

**Comment by jerboaa** [comment]
@AdamBrousseau Sounds fine to me.

**Comment by smlambert** [comment]
Minutes:

- Linux Installers 
  - @sophia-guo incorporating https://github.com/aahlenst/adoptium-packages-linux into the installer repo (addressing https://github.com/adoptium/installer/issues/311), and creating Jenkins job to run the new installer piece
  - @jerboaa to incorporate his portion (of creating srpm's for OpenJ9), once Sophia's PR is in
  - @sxa @smlambert - following up with package hosting companies (that Andreas had connected with), to bring options/pricing to WG call in order to publish new installer piece to non-artifactory solution

- [The Linter Issue](https://github.com/adoptium/temurin-build/issues/2581) - @M-Davies has been updating (see https://github.com/adoptium/temurin-build/pull/2609), has the go-ahead to remove an old mercurial script, which was causing many linter errors, should make his PR ready for review/merge (Morgan also mentioned he is in his last month at school and wants us to distract him with many petty issues... no wait, I may have misheard that...)

- [The Alpine Linux Freetype PR](https://github.com/adoptium/temurin-build/pull/2587) - Announcing that to align with all other linux platforms, we changed no longer bundle freetype with alpine linux builds

- [The "Reschedule this Meeting" Doodle](https://doodle.com/poll/397tvu3xkzn2tw64?utm_source=poll&utm_medium=link) - Right now it seems that Wednesdays, 3pm-4pm BST (10am-11am Ontario) is the best slot, as almost everyone can attend. 
  - given that Adam B. can attend the first 30min (and we can prioritize items of interest to the top of the agenda), and no one else is urgently requesting a different time slot, we will leave the meeting time as is

- Smoke test documentation - Shelley will add doc to temurin-build on how to run smoke tests after the run-aqa PR, https://github.com/adoptium/run-aqa/pull/82 is merged (where we can then also incorporate smoke tests into a github workflow in the temurin-build repo using run-aqa)

- Adam B. to make updates to smoke tests for OpenJ9 once vendor system properties are known/updated (and for sure by the time we merge the PR that will make the smoke tests block other testing, see https://github.com/adoptium/ci-jenkins-pipelines/pull/126)

- Eclipse Temurin - Activities to prepare for [first release](https://github.com/adoptium/adoptium/projects/1) - see that project for the issues being worked to lift up the first Temurin release.  It also includes [milestones](https://github.com/adoptium/adoptium/milestones) (which are laid out, but some things outside of our direct control may block us... milestones will then be updated if that is the case)

------------------

Meeting [recording link](https://bluejeans.com/s/8BtMbOvzt8x)

Link to next community call: https://github.com/adoptium/adoptium/issues/13
