### ISSUE TITLE
Please build Valhalla to allow community testing of Nestmates

### ISSUE THREAD

**Issue by kittylyst** [AdoptOpenJDK/TSC#24]
As per:  https://www.infoq.com/news/2018/03/Nestmates

and the spec update:  http://cr.openjdk.java.net/~dlsmith/nestmates.html

and  http://cr.openjdk.java.net/~dlsmith/nestmates-jls.html

that have just been published, Nestmates is being primed for inclusion in JDK 11.

The merge to mainline is expected in the next month, so it would help to have community-ready binaries to allow widespread testing of this new feature.

Valhalla mainline for Linux & Mac seems like the appropriate repo to build to expose this feature.

**Comment by karianna** [comment]
@kittylyst I might pull you in for a quick bash script fix around our git-hg mechanism, it's currently blocking pulling in projects like Valhalla as quickly as we'd like.

**Comment by kittylyst** [comment]
@karianna I have some time over the next week. Ping me on Slack / by mail & let me know what you need.

**Comment by kittylyst** [comment]
As Nestmates arrived in 11, I think we can close this one.
