### ISSUE TITLE
openjdk build version breaks maven-enforcer java version check & perhaps other tools

### ISSUE THREAD

**Issue by planetf1** [AdoptOpenJDK/TSC#26]
Summary - request version strings from adoptopenjdk builds are more similar to existing java builds and work properly with the maven enforcer plugin...

Detail.....

I have been working on Apache Atlas, and our work has now moved to the Linux Foundation->ODPi->egeria project. In both cases the code is java based and makes use of the maven enforcer plugin to check the Java level being used to build the code. This helps us with consistency and making sure developers are not using the wrong JDK version, and to a lesser extent, very back level update.

Until now most developers have been using the Oracle JDK on macOS/Windows, and the distribution provided openjdk variations under Linux (in some cases Oracle too). However with Oracle charging for 1.8 support soon, and not being ready to move we have decided to move to openjdk throughout as our recommended version, and ideally obtained from adoptopenjdk

Our top level maven pom is at https://github.com/odpi/egeria/blob/master/pom.xml - and you'll see at the base of this some enforcer rules including
<requireJavaVersion>
<level>ERROR</level>
<version>[1.8.0-151,)</version>

which means use JDK 1.8 update 151 or above

Docs on the maven enforcer plugin are at https://maven.apache.org/enforcer/enforcer-rules/requireJavaVersion.html

However when using an adoptopenjdk jdk for macos/windows, this tool is not allowing us to pass the version check. Indeed when I run java version I find something interesting:

From OpenJDK8_x64_Mac_jdk8u172-b11.tar.gz I seem to get:

15:43 $ java -version
openjdk version “1.8.0-adoptopenjdk”
OpenJDK Runtime Environment (build 1.8.0-adoptopenjdk-jenkins_2018_05_19_02_01-b00)
OpenJDK 64-Bit Server VM (build 25.71-b00, mixed mode)

Whilst oracle gives me

15:43 $ java -version
java version “1.8.0_172"
Java(TM) SE Runtime Environment (build 1.8.0_172-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.172-b11, mixed mode)
and an existing openjdk build from ubuntu:
meanwhile the openjdk install from my friendly ubuntu system (from their repo - not adoptopenjdk) - albeit u171 - is reporting:
14:59 $ java -version
openjdk version “1.8.0_171”
OpenJDK Runtime Environment (build 1.8.0_171-8u171-b11-0ubuntu0.16.04.1-b11)
OpenJDK 64-Bit Server VM (build 25.171-b11, mixed mode)

Both pass the checks fine!

It's alo worth noting that if I look at actual java properties, the oracle jdk has:
   java.vm.version = 25.171-b11
Whilst the adoptopenjdk build has
   java.vm.version = 25.71-b00

The IMPACT of this is that I cannot use adoptopenjdk builds as a 'slot in' replacement for this project - which was our plan! I *could* write a custom java version checker, but my questions would be

a) Why is the version string so different, and why in particular does it not include the update level (ie 171 or 172)
b) Why is the java.vm.version seemingly missing an entire digit

What I would LIKE is for the openjdk build to work properly with the maven-enforcer plugin out of the box - be it by updating that tool (we could contribute a patch if we have good reason) or by changing the version string openjdk provides and ensuring it can be parsed by the existing algorithm

I'll look at providing a simple test case/git (basically just that pom fragment & dependency & then running it with mvn enforcer:display-info) [note I'm using maven 3.5.3]

(Ref: original discussion at https://adoptopenjdk.slack.com/archives/C09NLQQAV/p1529678802000497 )

**Comment by planetf1** [comment]
Test repo is at https://github.com/planetf1/adoptopenjdk-mvntest.git

Use maven 3.5.0 or above

Note that the .171/172 info is lost - and so the check will fail

✔ ~/src/adoptopenjdk-mvntest [master|●1✚ 1…5]
23:20 $ mvn enforcer:display-info
[INFO] Scanning for projects...
[INFO]
[INFO] ----------------------< org.acme.tester:mvntest >-----------------------
[INFO] Building Adoptopenjdktest 0.1-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- maven-enforcer-plugin:3.0.0-M1:display-info (default-cli) @ mvntest ---
[INFO] Maven Version: 3.5.3
[INFO] JDK Version: 1.8.0_172 normalized as: 1.8.0-172
[INFO] OS Info: Arch: x86_64 Family: mac Name: mac os x Version: 10.13.6
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.535 s
[INFO] Finished at: 2018-06-22T23:20:42+01:00
[INFO] ------------------------------------------------------------------------
✔ ~/src/adoptopenjdk-mvntest [master|●1✚ 1…5]
23:20 $ java -version
java version "1.8.0_172"
Java(TM) SE Runtime Environment (build 1.8.0_172-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.172-b11, mixed mode)
✔ ~/src/adoptopenjdk-mvntest [master|●1✚ 1…5]
23:20 $ jenv versions
  system
  1.8
  1.8.0-adoptopenjdk
  1.8.0.172
  10.0
  10.0.1
  10.0.1-adoptopenjdk
  9.0
  9.0.4
  openjdk64-1.8.0-adoptopenjdk
  openjdk64-10.0.1-adoptopenjdk
* oracle64-1.8.0.172 (set by /Users/jonesn/.jenv/version)
  oracle64-10.0.1
  oracle64-9.0.4
✔ ~/src/adoptopenjdk-mvntest [master|●1✚ 1…5]
23:21 $ jenv global 1.8
✔ ~/src/adoptopenjdk-mvntest [master|●1✚ 1…5]
23:21 $ java -version
openjdk version "1.8.0-adoptopenjdk"
OpenJDK Runtime Environment (build 1.8.0-adoptopenjdk-jenkins_2018_05_19_02_01-b00)
OpenJDK 64-Bit Server VM (build 25.71-b00, mixed mode)
✔ ~/src/adoptopenjdk-mvntest [master|●1✚ 1…5]
23:21 $ cd adoptopenjdk-mvntest/
✔ ~/src/adoptopenjdk-mvntest [master|●1✚ 1…5]
23:21 $ mvn enforcer:display-info
[INFO] Scanning for projects...
[INFO]
[INFO] ----------------------< org.acme.tester:mvntest >-----------------------
[INFO] Building Adoptopenjdktest 0.1-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- maven-enforcer-plugin:3.0.0-M1:display-info (default-cli) @ mvntest ---
[INFO] Maven Version: 3.5.3
[INFO] JDK Version: 1.8.0-adoptopenjdk normalized as: 1.8.0
[INFO] OS Info: Arch: x86_64 Family: mac Name: mac os x Version: 10.13.6
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.480 s
[INFO] Finished at: 2018-06-22T23:22:08+01:00
[INFO] ------------------------------------------------------------------------
✔ ~/src/adoptopenjdk-mvntest [master|●1✚ 1…5]

**Comment by karianna** [comment]
https://github.com/AdoptOpenJDK/openjdk-build/issues/387
