### ISSUE TITLE
Legal information concerning redistubution of embedded JRE

### ISSUE THREAD

**Issue by chiflux** [AdoptOpenJDK/TSC#28]
Currently it is more or less unclear, if the **JRE** contained in OpenJDK can be redistributed with proprietary software **without** running into copyleft issues for the proprietary parts. A positive and well-founded statement on this topic could improve acceptance for OpenJDK for commercial purposes.

There seem to be no clear consensus about this issue. One particular phrase is common to all comments, though: "**I am not a lawyer**, but I think...". Unfortunately, the information following the dots is not too helpful, if you seriously want to advocate for an OpenJDK based JRE in proprietary software.

Request: AdoptOpenJDK should release a unambiguous and for everybody understandable statement (in everyday language) about possible use-cases (as many as possible) of the embedded JRE in OpenJDK.

(I opened this issue, because it was suggested by martijnverburg in Slack to do this)

**Comment by tellison** [comment]
Hi @chiflux .  I understand what you are requesting, but here's the problem...

The binaries we produce all come with a LICENSE file, and supporting information such as notices, that precisely describe your rights and obligations when using the code.

Writing a license takes *many* hours of work from people who are used to thinking about the benefits and the consequences of the text that is written - often drawing upon past examples that have been tested by the community or in law.

We do not own all the code in the binaries we distribute; we provide such code under license.  So any statement we make about how a binary can be used would be a non-authoritative opinion, that is, you would not be able to point at our statement as a defense if somebody told you that your usage was not in accordance with the terms of the license of their code.

By way of interpretation we really couldn't do any better than [the extensive GPL FAQ hosted at gnu.org](https://www.gnu.org/licenses/gpl-faq.html), plus point you at the short classpath exception text -- all contained in the LICENSE file.

If you still have questions about legitimate usage of an OpenJDK JRE in embedded situations after reading the license in the context of your proposed usage, you will need to find somebody you can trust to advise you.  I hope you understand that we cannot advise people directly about their individual usage propositions.  You might also consider taking an OpenJDK distribution from a vendor who is willing to indemnify your usage.  In each case, getting professional advice or an indemnity is typically not free of cost.

HTH

**Comment by karianna** [comment]
I'm closing this as AdoptOpenJDK (via the LJC) is currently not going to provide commercially backed, indemnified binaries.  Tim's explanation covers the rest extremely well.
