### ISSUE TITLE
Create a PPA for AdoptOpenJDK releases

### ISSUE THREAD

**Issue by Iteratrix** [AdoptOpenJDK/TSC#34]
If this is the wrong project for this issue, let me know where it should be opened and I can close this.

It looks like AdoptOpenJDK offers downloads from its website of JDK releases, and also offers a Homebrew tap for command line installation. However, I haven't been able to find a PPA that provides releases of AdoptOpenJDK binaries. Does one already exist, and if not then how about creating one for easy installation on Ubuntu servers?

Thanks.

**Comment by karianna** [comment]
There's not PPA at the moment.  The openjdk-installers repo is the place to go to raise the issue!

**Comment by Iteratrix** [comment]
@karianna Ah, got it. I also noticed that there's a related request in openjdk-build for packaging as a DEB: https://github.com/AdoptOpenJDK/openjdk-build/issues/458

Should I close this issue and open a new one in openjdk-installers?

**Comment by karianna** [comment]
Yes please!

**Comment by Iteratrix** [comment]
Alright. I've opened a new issue in openjdk-installer at https://github.com/AdoptOpenJDK/openjdk-installer/issues/10, so I'll close this out. Thanks.
