### ISSUE TITLE
Add a README to all legacy release and nightly repos to redirect them to binaries repos

### ISSUE THREAD

**Issue by karianna** [AdoptOpenJDK/TSC#35]
Check for all the following repos and add a README telling folks to go to `openjdk<version>-binaries` instead.

- [x] openjdk8-nightly
- [x] openjdk9-nightly
- [x] openjdk10-nightly
- [x] openjdk8-releases
- [x] openjdk9-releases
- [x] openjdk10-releases
- [x] openjdk8-openj9-nightly
- [x] openjdk9-openj9-nightly
- [x] openjdk10-openj9-nightly
- [x] openjdk8-openj9-releases
- [x] openjdk9-openj9-releases
- [x] openjdk10-openj9-releases

**Comment by xtbe** [comment]
All repos checked and adapted where needed.
PRs submitted
