### ISSUE TITLE
Complete the Wikipedia article

### ISSUE THREAD

**Issue by karianna** [AdoptOpenJDK/TSC#36]

**Comment by gdams** [comment]
I'm going to talk to the folks who wrote the OpenJ9 article to see if they have any tips for me

**Comment by federicoculloca** [comment]
Are you talking about the OpenJDK article or the draft AdoptOpenJDK article? Because if it's the latter I'm slowly working on it and it would help if anyone could provide some sources to integrate in that article.

**Comment by karianna** [comment]
> Are you talking about the OpenJDK article or the draft AdoptOpenJDK article? Because if it's the latter I'm slowly working on it and it would help if anyone could provide some sources to integrate in that article.

We need assistance with the draft AdoptOpenJDK article - we've fallen foul of the Wikipedia rules on multiple occasions now.

**Comment by federicoculloca** [comment]
> We need assistance with the draft AdoptOpenJDK article - we've fallen foul of the Wikipedia rules on multiple occasions now.

I now see it was started by @gdams. I added some stuff, if you guys could please check it. Also, I added a section to the talk page that you may want to check and add an answer to.

**Comment by gdams** [comment]
@federicoculloca thanks for the tweaks!

> Since AdoptOpenJDK is not software, but a community effort to provide builds of software written by others, does it make sense to use the `Software` infobox?

@karianna and I discussed this before. We felt that software was probably the best fit because it aligned with pages from openjdk and azul etc.

> Furthermore, does it make sense to list developers in that box, especially when some of those are sponsors of the initiative but not strictly developers? Why cite those 5 and not the others mentioned in the referenced page?

Agreed, changing it to just say `Various` like the Node,js wiki page.

**Comment by gdams** [comment]
for those that want to make edits the article is here: https://en.wikipedia.org/wiki/Draft:AdoptOpenJDK

**Comment by karianna** [comment]
Done
