### ISSUE TITLE
Investigate using Travis for testing PRs

### ISSUE THREAD

**Issue by karianna** [AdoptOpenJDK/TSC#38]

**Comment by smlambert** [comment]
Somewhat related, we had looked at PR testing in https://github.com/AdoptOpenJDK/openjdk-tests/issues/20, (triggering test jobs in Jenkins via both pipelines and git issue comments, but recall that we did not get a webhook setup to allow for it (and I can't find a corresponding infrastructure request, if we made one, @sophia-guo do you recall any other relevant details?).

**Comment by sophia-guo** [comment]
I actually happened to play a little bit of travis-ci build recently in a very simple scenario:
Whenever a pull request is opened on GitHub, Travis CI builds it and updates the status icon on the pull request page.

https://github.com/sophia-guo/example-c/pull/2

<img width="841" alt="screen shot 2018-11-29 at 5 04 19 pm" src="https://user-images.githubusercontent.com/18030625/49255170-336d2f80-f3f9-11e8-82c8-029a3b3e1639.png">

And there will be more detail at travis-ci. https://travis-ci.com/sophia-guo/example-c/builds/92326015

The only thing need to do is 'Accept the Authorization of Travis CI' and add .travis.yml file.

**Comment by lasombra** [comment]
I think this is worth a try, but from experience with other projects, we need to be aware of the duration of the tests or have an option to skip. Submitting a PR for a change on a shell file shouldn't trigger the whole CI and make you wait 4 hours to make sure all is well.

Travis, as mentioned by @sophia-guo, should be trivial enough to get going :-)

Just my 2¢.

**Comment by karianna** [comment]
> I actually happened to play a little bit of travis-ci build recently in a very simple scenario:
> Whenever a pull request is opened on GitHub, Travis CI builds it and updates the status icon on the pull request page.
> 
> [sophia-guo/example-c#2](https://github.com/sophia-guo/example-c/pull/2)
> 
> <img alt="screen shot 2018-11-29 at 5 04 19 pm" width="841" src="https://user-images.githubusercontent.com/18030625/49255170-336d2f80-f3f9-11e8-82c8-029a3b3e1639.png">
> 
> And there will be more detail at travis-ci. https://travis-ci.com/sophia-guo/example-c/builds/92326015
> 
> The only thing need to do is 'Accept the Authorization of Travis CI' and add .travis.yml file.

Yeah, that's really nice.  It's a little tricky with say the build scripts because as single change could kick off lots and lots of platform builds to 'check' if that change was good.  But I think if we just left it to the major platforms even that might be OK.

**Comment by gdams** [comment]
@sophia-guo what's left to do here? did travis get enabled?

**Comment by smlambert** [comment]
Sophia should be back from vacation soon and can correct me if needed.

I think I can summarize, we did not enable travis, we were just sharing our experience with it.

I would like to clarify, what PRs are to be tested?  Changes in which repos (adopt build or test repos)?  Is this issue related to https://github.com/AdoptOpenJDK/TSC/issues/48 (which I believe is the issue to enable PR testing for OpenJDK patches/changes)?

**Comment by aahlenst** [comment]
We won't use Travis CI in the future because https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1668.

**Comment by smlambert** [comment]
(and we have [run-aqa](https://github.com/AdoptOpenJDK/run-aqa) and [build-jdk](https://github.com/AdoptOpenJDK/build-jdk) github actions that can be utilized for testing branches and patch testing now)
