### ISSUE TITLE
RFE: Add new build variants for OpenJDK 11 (LTS) / HotSpot for Solaris 10 U9 or later (both x86 and SPARC)

### ISSUE THREAD

**Issue by basil** [AdoptOpenJDK/TSC#40]
Exactly what it says on the tin. I am interested in OpenJDK 11 (LTS) / Hotspot builds for Solaris. In particular, I am interested in both x86 and SPARC builds, and I am interested in support for Solaris 10 Update 9 or later in both cases. Ideally, I’d love to have these builds by early 2019.

Relates to AdoptOpenJDK/openjdk-build#100 and AdoptOpenJDK/openjdk-build#113; this issue should track the high-level deliverables. Please let me know if I should split this into separate RFEs for x86 and SPARC.

See also [prior work toward a Solaris 10 x86 build of OpenJDK 11](http://pkgs.tribblix.org/openjdk/) by Peter Tribble.

**Comment by karianna** [comment]
ACK - we are racking a Sparc box in a data center and we should have enough sponsorship to cover x86 as well.  We are resource constrained a little on infrastructure and build experience with those platforms so any engineering support for those would be helpful!  You can join our slack at adoptopenjdk.net/slack.net to join the various teams

**Comment by gdams** [comment]
@basil we now have sparc builds of jdk8 and are working on sparc builds of jdk11 atm

**Comment by eFFecTM** [comment]
Is there any update on or any estimate when OpenJDK 11 builds will be available for Solaris (SPARC)?

**Comment by karianna** [comment]
I've opened a build issue - we can close this as TSC approves in principle.
