### ISSUE TITLE
Build and test IcedTea-Web browser plug-in code

### ISSUE THREAD

**Issue by tellison** [AdoptOpenJDK/TSC#41]
IcedTea-Web is an applet web browser plugin and Java Web Start (JNLP) project.  Although this technology is being superseded, it is currently in general usage on the desktop in a number of installations and therefore would be useful to OpenJDK users.

There is no equivalent available in OpenJDK, so I proposed that AdoptOpenJDK mirrors [the IcedTea-Web Mercurial source repository](http://icedtea.classpath.org/hg/icedtea-web/file/) into our Github organisation, and builds/tests/distributes binaries for general usage.  Any bugs found should be reported to the [IcedTea Bugzilla](https://icedtea.classpath.org/bugzilla/index.cgi) system, and potentially discussed on the [distro-pkg-dev](http://mail.openjdk.java.net/mailman/listinfo/distro-pkg-dev) mailing list.

Build instructions and links are available via the [README](http://icedtea.classpath.org/hg/icedtea-web/file/99b77a265f54/README).

The resulting binary should be available as a separate download rather than an integral part of the current Java SE downloads, if for no other reason than IcedTea-Web is provided on a separate release schedule to the OpenJDK SE release schedule.  However, we should consider making Icedtea-Web an installable component in our installers (especially on Windows) as these are most likely to be used in the desktop environment where JNLP and the browser plug-in are most used.

The precise details of the code licensing may need some scrutiny, as a quick glance at [the LICENSE file](http://icedtea.classpath.org/hg/icedtea-web/file/99b77a265f54/LICENSE) shows.

**Comment by karianna** [comment]
ITW is part of the Adopt Family now :-)
