### ISSUE TITLE
Initial TSC Meeting

### ISSUE THREAD

**Issue by gdams** [AdoptOpenJDK/TSC#45]
Time/Date: Friday 18th Jan 14:00-15:00 GMT
Meeting URL: https://ibm.webex.com/meet/george.adams

Invited: @AdoptOpenJDK/tsc 

### AdoptOpenJDK/openjdk-build

* Add Amazon Corretto Build to the pipeline [#785](https://github.com/AdoptOpenJDK/openjdk-build/issues/785)
* Add linux 32bit x86 release [#774](https://github.com/AdoptOpenJDK/openjdk-build/issues/774)

### AdoptOpenJDK/openjdk-website

* Logo Change? [#378](https://github.com/AdoptOpenJDK/openjdk-website/issues/378)

### AdoptOpenJDK/openjdk-infrastructure

* Get a more powerful ARM 32 box [#630](https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/630)
* Gaps in machine availability vs ability to run more tests?

### AdoptOpenJDK/TSC

* Build and test IcedTea-Web browser plug-in code [#41](https://github.com/AdoptOpenJDK/TSC/issues/41)
* Add Amazon Corretto as an OpenJDK distribution in the AdoptOpenJDK 'marketplace' [#39](https://github.com/AdoptOpenJDK/TSC/issues/39)
* Implement a 2-reviewer PR review system for PRs in critical repos [#37](https://github.com/AdoptOpenJDK/TSC/issues/37)
* Create a mailing list for announcements [#32](https://github.com/AdoptOpenJDK/TSC/issues/32)
* Add JavaFX to the build farm and distribute results via adoptopenjdk website [#27](https://github.com/AdoptOpenJDK/TSC/issues/27)

### Other
* Additional Intel server hosted by Inspira
* Slack premium
* Stickers
* Conference software

**Comment by cmdc0de** [comment]
Would like to add a discussion on how can we train up team members to help.  EG: I would like to pickup an issue from one of our boards, but can't because I don't have good visibility servers, usernames, passwords, etc.

**Comment by vielmetti** [comment]
Do we have a meeting URL for this? I don't see it anywhere...

**Comment by gdams** [comment]
meeting URL: https://ibm.webex.com/meet/george.adams

**Comment by vielmetti** [comment]
I've followed up with @sxa555 re ARM 32.
