### ISSUE TITLE
Using GitHub Checks API to coordinate test runs

### ISSUE THREAD

**Issue by akashche** [AdoptOpenJDK/TSC#48]
For patches submitted to upstream jdk8u after January 2019 Red Hat is going to run internal testing for each such patch. I propose to implement the facilities to be able to additionally run the existing AdopOpenJDK test suites (on existing Jenkins infra) for these patches.

The idea is to use [AdoptOpenJDK/openjdk-jdk8u](https://github.com/AdoptOpenJDK/openjdk-jdk8u) repository to track the testing of the patches the following way (all steps are automatic):

1. Change is pushed to AdoptOpenJDK/openjdk-jdk8u into a new branch

2. PR is created for this branch

3. A set of [Checks Runs](https://developer.github.com/v3/checks/runs/) is created for this PR, each check corresponds to a sings test-suite that runs on a AdoptOpenJDK Jenkins

4. Checks stated are updated accordingly after the tests-suites finished

Please note, that PR is created only to allow to use Checks UI, there are no intentions to actually merge these changes into the master branch of AdoptOpenJDK/openjdk-jdk8u.

To work with Checks API it is required to implement a "Github App", I wrote a [prototype of such app](https://github.com/apps/aojdk-check-test), example of Check Runs created though it (please note that you need to be logged into GitHub to see the full UI):

 - https://github.com/akashche/pr-checks-test/pull/1
 - https://github.com/akashche/pr-checks-test/pull/1/checks

Please let me know what do you think about the possible use of GitHub Checks and about the possibilities of their integration with AdoptOpenJDK testing infra.

Thanks!

PS: I am omitting most of the technicalities from this proposal, generally all technical details related to GitHub interaction are understood.

**Comment by karianna** [comment]
Added to the next Agenda.

**Comment by jerboaa** [comment]
@akashche This has been approved by the TSC in principle. It's depending on additional hardware resources for Windows/Mac testing for which sponsors are going to be needed. Right now, development can start with a small pool of Linux intel hardware. Then we can farm in more platforms as they become available. Please coordinate with the testing team at Adopt to get you started. Thanks!

**Comment by karianna** [comment]
This will also require a separate set-up (Jenkins etc). @akashche - Are you able to join the Adoptopenjdk.net/slack group?

**Comment by tellison** [comment]
I don't see enough detail to know if the "Github App" preserves the identity of the user who is creating the PR, which would be required for team membership/whitelisting - as clearly we don't want everyone in the world to be able to send 'random' code to run on the AdoptOpenJDK infrastructure.

**Comment by akashche** [comment]
@tellison , in initial proposal "github app" was expected to obtain patches only from Red Hat (once patch is coming for RH internal testing - it is also submitted to Adopt infra). In that scenario "github app" is deployed on RH server and RH-controlled domain (publicly-available domain is required for "github apps" to be able to receive "web hook" notifications from GitHub) and only a narrow circle of people from RH Java team can submit patches.

If it is desired to have a general-use patch submission service for Adopt build farm, I can think of the two scenarios with "github app", when it can be done relatively safe:

1. patch must be published on `cr.openjdk.java.net` before being processed by "github app":

 - user creates an issue inside AdoptOpenJDK/openjdk-jdk8u repo and puts a URL into issue body pointing directly to the patch on `cr.openjdk.java.net` (like this one - http://cr.openjdk.java.net/~akasko/jdk8u/8035653/webrev.00/jdk.patch )
 - "github app" receives a webhook from github about new issue, fetches the patch using specified URL, applies the patch locally to the new branch
 - "github app" pushes the branch to the AdoptOpenJDK/openjdk-jdk8u repo, creates a PR for the branch and proceeds with calling Adopt infra and creating/updating Checks for this PR
 - initial issue (one with URL) is used for logging the progress about this patch - "github app" adds the comment there after each step and adds the error message there if something went wrong

2. patch can be submitted by any user (through github or some dedicated form), branch and PR are created automatically, but at some point manual confirmation from the "known user" is required (for example, in a form of a comment to the tracking issue in a specific format)


Of course,  there may be scenarios for patch submission service for Adopt without using "github app"/PRs/Checks (some web form on adoptopenjdk.net etc). In this case, once the patch submission is implemented, we can try to use "github app" as a bridge between Red Hat internal infra and such new patch submission service (github repo with checks in that case may be used as a "middle ground" between RH and Adopt infras).

**Comment by smlambert** [comment]
hi @akashche - I would love to see https://github.com/apps/aojdk-check-test if you are ready to share it, it is currently private :)

**Comment by akashche** [comment]
@smlambert , m, I think the "GitHub App" itself should remain "private". As I understand, such apps can be [installed for the user/organization repo](https://developer.github.com/apps/installing-github-apps/#installing-your-private-github-app-on-your-repository) without advertising them on a [GitHub Marketplace](https://github.com/marketplace). Non-testing version (without "-test" label) probably should be registered with AdoptOpenJDK GitHub org at some point (and perhaps the source repo moved to that org too).

Currently this "GitHub App" contains various bits to work with GitHub API and with local git repo, but lacks the integration with AdoptOpenJDK build farm. The process a bit stalled at this point: to be able to start jobs on a build farm some publicly available HTTP API is required - to submit patches and to check the jobs status. I think there should be some general decisions from TSC on - who is allowed to submit/approve patches, which Jenkins instance to use, whether to use Jenkins HTTP API directly or have a specific patch submission frontend on adoptopenjdk.net etc. And based on that I can work out the details.

**Comment by karianna** [comment]
Added TSC label to this - I suspect for stability/security of our release binary pipelines we'll likely have a separate Jenkins master for this purpose, but let's discuss that tactical step all together after the TSC decides when we start with the patch submission feature of Adopt!

**Comment by karianna** [comment]
For jdk8u, create a job which can:

1. Point to a webrev
1. Pull down down the patch file(s)
1. Apply to the HEAD of the master branch of jdk8u (of the AdoptOpenJDK git mono-repository)
1. Then build binary on a Linux x86 box
1. If successful trigger nightly pipeline tests

We should Docker the builds and also make sure only qualified people can execute the build.

**Comment by jerboaa** [comment]
We discussed this at the TSC meeting today. To get a clearer picture about answers we need to prototype this. First iteration is not going to be automated, but manually triggered.

**Comment by akashche** [comment]
> For jdk8u, create a job which can:
> 
>     1. Point to a webrev
> 
>     2. Pull down down the patch file(s)
> 
>     3. Apply to the HEAD of the master branch of jdk8u (of the AdoptOpenJDK git mono-repository)
> 
>     4. Then build binary on a Linux x86 box
> 
>     5. If successful trigger nightly pipeline tests
> 
> 
> We should Docker the builds and also make sure only qualified people can execute the build.

If I understand this correctly, "job" here is a job on a "separate Jenkins master". And the most of the logic, initially intended to be implemented inside the GitHub App, now goes into that new Jenkins job.

I cannot participate in Jenkins-based implementation directly - I don't work with Jenkins. But to use GitHub Checks API it is still required to have a publicly available HTTP(S) server (GitHub App - that will receive webhooks from GitHub). If it would be preferred to have such HTTP server outside of Jenkins - I can help with implementing it (based on the existing working prototype linked in the first post). With the most of the logic moved out of it, I think such server can be simplified to the Python script (behind Nginx) or something like that.

**Comment by karianna** [comment]
Superseded by Aqavit test frameworks at Adoptium
