### ISSUE TITLE
Commercial Support Awareness of AdoptOpenJDK binaries

### ISSUE THREAD

**Issue by karianna** [AdoptOpenJDK/TSC#50]
IBM commercially support AdoptOpenJDK OpenJ9 binaries as part of their IBM Runtimes support offering.

jClarity is going to start offering commercial support for AdoptOpenJDK starting in February 2019.

How should AdoptOpenJDK deal with these commercial support offerings in an open, transparent and unbiased manner?  A guiding principle should be that any legitimate community member should be able to provide and 'advertise' commercial support.

The initial request is that we add a commercial support section in the support.html page that we can steer end users towards.

**Comment by karianna** [comment]
https://github.com/AdoptOpenJDK/openjdk-website/pull/410

**Comment by karianna** [comment]
A very poor example of logo usage

<img width="1748" alt="support" src="https://user-images.githubusercontent.com/180840/52862486-4d332e80-312d-11e9-9225-53a82ebf1100.png">

**Comment by johnoliver** [comment]
Don't modify the logo. Currently this looks like the `Support` text is added by modifying the logo itself and added in the same font/colour style, maybe making this look like it is an official logo of Adopt itself.

Also make sure we are using the official unmodified svg

**Comment by karianna** [comment]
Hi all - this is using the official un altered logo.

<img width="1748" alt="adoptopemnjdk_logo_usage" src="https://user-images.githubusercontent.com/180840/52976066-e24d5600-33bf-11e9-8670-c3badc0fe56a.png">

**Comment by tellison** [comment]
LGTM

**Comment by karianna** [comment]
OK, closing this, the other piece to this is in the website repo PR
