### ISSUE TITLE
Create an independent AdoptOpenJDK legal entity from the London Java Community

### ISSUE THREAD

**Issue by karianna** [AdoptOpenJDK/TSC#51]
As AdoptOpenJDK continues to mature the LJC would like to spin off AdoptOpenJDK into its own legal entity so it completely controls its own legal and financial destiny (as guided by the TSC).

My current suggestion is to use a UK Community Interest Company (much like the LJC) and appoint 3 directors of which at least one will be on the TSC.

**Comment by smlambert** [comment]
Given the move to Eclipse, this can be closed.
