### ISSUE TITLE
FreeBSD 12 Builds for OpenJDK

### ISSUE THREAD

**Issue by aashiks** [AdoptOpenJDK/TSC#53]
There aren't any builds for OpenJDK available for FreeBSD past JDK 8. Is there a way work on this front could be pushed forward ?

**Comment by aashiks** [comment]
An update : https://lists.freebsd.org/pipermail/freebsd-java/2019-March/012684.html

Basically, there is a port that works in FreeBSD 11.x (and apparently FreeBSD 12), it is still preliminary, but it is very good news. There will be a proper port soonish.

**Comment by karianna** [comment]
> An update : https://lists.freebsd.org/pipermail/freebsd-java/2019-March/012684.html
> 
> Basically, there is a port that works in FreeBSD 11.x (and apparently FreeBSD 12), it is still preliminary, but it is very good news. There will be a proper port soonish.

@aashiks Are you able to get those folks to pop over to Adopt and see if we can help them?

**Comment by gdams** [comment]
We do have access to some FreeBSD hardware so if somebody is happy to champion this then in principle I'm happy. (My view doesn't necessarily represent that of the TSC though)

**Comment by aashiks** [comment]
I am not subscribed to that mailing list (yet), but as soon as I am, I will point them to Adopt and this particular issue. But the fact that an initial port exists is in itself good news, and I think only a matter of months or weeks before it shows up in FreeBSD ports.

EDIT: I have sent an email to the list, and hopefully this will result in some collaboration - and in the end me being able to continue to use FreeBSD + JVM in production.

**Comment by lapo-luchini** [comment]
@karianna AFAICT the port is built from [battleblow/openjdk-jdk11u](https://github.com/battleblow/openjdk-jdk11u) which is a fork of Adopt already.

**Comment by gdams** [comment]
I will close this issue if nobody comes forward to champion FreeBSD builds at AdoptOpenJDK. Leaving this open for another week.

**Comment by ari** [comment]
There has been a port on FreeBSD for about three months now: https://svnweb.freebsd.org/ports/head/java/openjdk12/

The code is coming from here: https://github.com/AdoptOpenJDK/openjdk-jdk12u/compare/master...battleblow:bsd-port  I'm guessing you are already aware of that effort.

Are you looking to upstream those patches? Or something else? If you want to run test suites, its pretty easy to launch FreeBSD AMIs in EC2 (if that's your infrastructure).

**Comment by gdams** [comment]
I guess I'm primarily looking for some folks to help us get some freebsd hardware (we've lost ours with the shutdown of Joyent Triton and then some freebsd folks who have built openjdk to help us get the scripts implemented.

**Comment by ari** [comment]
I'm happy to help. About 20 years experience managing FreeBSD servers in a business environment, and about the same working in open source communities and projects.

When you say "get hardware" are you looking for a donation of some hardware or help setting up instances in some virtual server/jail? The later is easy enough and I can help or give it as a exercise for sometime on my team.

The starting point for any script is the FreeBSD port Makefile I pointed to in an earlier comment.

Do you have a Java TCK licensed which you want to run? I know there was difficulty getting that from sun/oracle way back in the project Harmony days at Apache.

**Comment by gdams** [comment]
@ari I can probably get some hardware from somewhere if you are happy to setup the machines using an ansible playbook or something. Maybe you've got time for a call next week and we can go through the next steps?

**Comment by ari** [comment]
Sure. Don't know ansible at all. But I've used salt extensively. Let's chat in a more suitable forum next week. I'm +1000.

**Comment by gdams** [comment]
What day/time works best for you? I'm in British Summer Time (+1)

**Comment by battleblow** [comment]
I've been having an email discussion with @karianna about this over the last couple of days and he suggested creating an issue so that it could be discussed at a TSC meeting.  Since this was already open I'm instead adding a comment into this one.

To add a bit of detail, the FreeBSD Foundation and I are very interested in seeing FreeBSD builds and releases of AdoptOpenJDK.  I maintain the repo mentioned earlier in the thread and there are currently repos for openjdk8, openjdk11, openjdk12 and openjdk13 with a bsd-port branch that is used for BSD support.  These repos are used as the source for corresponding ports in the FreeBSD ports system.  While most of the focus is on amd64 and i386, there is support for powerpc64 and relatively new support for aarch64 as well (although the latter is still undergoing some work).  I would be remiss if I didn't mention that OpenBSD is also supported for amd64 and i386.

**Comment by karianna** [comment]
We could potentially host the sources here at Adopt as a fully-fledged port project (although I'd prefer it to be hosted upstream).  Let's discuss.

**Comment by karianna** [comment]
Unfortunately we cannot build freeBSD supported binaries at our new home in Eclipse Adoptium.  You'll need to get a port accepted upstream at OpenJDK for us to be able to add this.
