### ISSUE TITLE
TSC Meeting - 2019-03-01

### ISSUE THREAD

**Issue by gdams** [AdoptOpenJDK/TSC#55]
Invited: @AdoptOpenJDK/tsc 

### adoptopenjdk/openjdk-build

* Build IcedTea-Web at AdoptOpenJDK [#898](https://github.com/AdoptOpenJDK/openjdk-build/issues/898)

### adoptopenjdk/openjdk-website

* Serve JRE or JDK by default on homepage [#412](https://github.com/AdoptOpenJDK/openjdk-website/issues/412)
* Amazon Corretto Distribution - please see Trademark policy before working on this ticket. [#399](https://github.com/AdoptOpenJDK/openjdk-website/issues/399)
* Add an FAQ for AdoptOpenJDK to answer common support questions [#371](https://github.com/AdoptOpenJDK/openjdk-website/issues/371)

### adoptopenjdk/TSC

* FreeBSD 12 Builds for OpenJDK [#53](https://github.com/AdoptOpenJDK/TSC/issues/53)
* Using GitHub Checks API to coordinate test runs [#48](https://github.com/AdoptOpenJDK/TSC/issues/48)
* Build and test IcedTea-Web browser plug-in code [#41](https://github.com/AdoptOpenJDK/TSC/issues/41)
* Implement a 2-reviewer PR review system for PRs in critical repos [#37](https://github.com/AdoptOpenJDK/TSC/issues/37)

### adoptopenjdk/openjdk-docker

* Docker image for IBM Health Center [#104](https://github.com/AdoptOpenJDK/openjdk-docker/issues/104)

**Comment by smlambert** [comment]
Would add adoptopenjdk/openjdk-infrastructure section, more infrastructure support needed at the project, and/or a push to simplify so less skilled can help too.  Should probably define some goals for infra, so not just a fire-fighting effort.  Understand there has been some kubernetes investigation, some discussion on dynamic machine allocation, etc.  It will be good to lay out expected requirements over the next few weeks of what this project will need going forward.  I will help gather some numbers from a test perspective.

**Comment by smlambert** [comment]
Closing this one.
