### ISSUE TITLE
Promote 11.0.2+9 hotspot on aarch64/arm/ppc64le/s390x

### ISSUE THREAD

**Issue by johnoliver** [AdoptOpenJDK/TSC#56]
11.0.2+9 builds for hotspot, on aarch64/arm/ppc64le/s390x still need to be released.

Builds ran successfully at: https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk11-pipeline/328/

Assets need to be checked and published to github.

**Comment by gdams** [comment]
+1 from me

**Comment by karianna** [comment]
Good opportunity to webinar this and show others how to release
