### ISSUE TITLE
Delete Archived Repositories

### ISSUE THREAD

**Issue by karianna** [AdoptOpenJDK/TSC#58]
- [ ] - openjdk-jdk8u-backup-31-oct-2018
- [ ] - openjdk-aarch64-jdk8u-backup-06-Nov-2018
- [ ] - openjdk-jdk8u-backup-06-sep-2018
- [ ] - openjdk10-test-nightly
- [ ] - openjdk-jdk9u-backup-03-sep-2018
- [ ] - openjdk-jdk8u-backup

**Comment by gdams** [comment]
TSC feels this does nor make sense
