### ISSUE TITLE
Archive Legacy Nightly and Release repos?

### ISSUE THREAD

**Issue by karianna** [AdoptOpenJDK/TSC#59]
All *-nightly and *-release repos should be superseded by *-binaries repos.  Archiving should still allow the API to pick up legacy binaries but we can test that one by one.

Need to make a decision on deletion as well as that may impact download / API.

**Comment by gdams** [comment]
archive but not delete

**Comment by karianna** [comment]
Transferred to Eclipse Adoptium.
