### ISSUE TITLE
Request for mac test servers

### ISSUE THREAD

**Issue by gdams** [AdoptOpenJDK/TSC#62]
@smlambert has requested some macs for test use.

requesting the following servers:

2x10.11, 2x10.12, 2x10.13 and 2x10.14

each server needs to be 4CPU and 8GB ram with 100gb disk.

cost per server is £67.75 p/m

total cost per month is £542 p/m

**Comment by smlambert** [comment]
I will try to add some 'execution time' data that will help justify this request/expenditure before tomorrow's meeting.  Thanks @gdams !

**Comment by sxa** [comment]
Do we need to have full coverage across all of the OS versions?

**Comment by gdams** [comment]
I think that for a major platform such as macOS we should aim for that

**Comment by gdams** [comment]
recent twitter poll: https://twitter.com/adoptopenjdk/status/1107693960707932160

**Comment by gdams** [comment]
TSC has agreed to fund 4 x 10.13 and 4 x 10.14 mac VM's. We will try and find a sponsor to cover this.

**Comment by gdams** [comment]
purchased. work happening in https://github.com/AdoptOpenJDK/openjdk-infrastructure/pull/826
