### ISSUE TITLE
Placeholder - Promote AdoptOpenJDK 12 Builds

### ISSUE THREAD

**Issue by karianna** [AdoptOpenJDK/TSC#68]
- [x] OpenJ9
- [x] Hotspot

**Comment by johnoliver** [comment]
Initial set of binaries at: https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk12-pipeline/87/

Provides Openj9:
Linux x86 and ppc64le
Mac
Windows

**Comment by sxa** [comment]
I approve promoting the Openj9 builds from 87 (and 88/89 when available for the other platforms)

**Comment by gdams** [comment]
@sxa555 are you happy to champion this release going forwards?

**Comment by andrew-m-leonard** [comment]
Test results:

**Comment by andrew-m-leonard** [comment]
https://ci.adoptopenjdk.net/view/Test_openjdk/job/openjdk12_j9_openjdktest_ppc64le_linux/19/
https://ci.adoptopenjdk.net/view/Test_openjdk/job/openjdk12_j9_openjdktest_x86-64_linux/25/
https://ci.adoptopenjdk.net/view/Test_openjdk/job/openjdk12_j9_openjdktest_x86-64_linux_linuxXL/20/
https://ci.adoptopenjdk.net/view/Test_openjdk/job/openjdk12_j9_openjdktest_x86-64_macos/16/
https://ci.adoptopenjdk.net/view/Test_openjdk/job/openjdk12_j9_openjdktest_x86-64_macos_macosXL/15/
https://ci.adoptopenjdk.net/view/Test_openjdk/job/openjdk12_j9_openjdktest_x86-64_windows/17/
https://ci.adoptopenjdk.net/view/Test_system/job/openjdk12_j9_systemtest_ppc64le_linux/14/
https://ci.adoptopenjdk.net/view/Test_system/job/openjdk12_j9_systemtest_x86-64_linux/22/
https://ci.adoptopenjdk.net/view/Test_system/job/openjdk12_j9_systemtest_x86-64_linux_linuxXL/18/
https://ci.adoptopenjdk.net/view/Test_system/job/openjdk12_j9_systemtest_x86-64_macos/14/
https://ci.adoptopenjdk.net/view/Test_system/job/openjdk12_j9_systemtest_x86-64_macos_macosXL/14/
https://ci.adoptopenjdk.net/view/Test_system/job/openjdk12_j9_systemtest_x86-64_windows/
https://ci.adoptopenjdk.net/view/Test_perf/job/openjdk12_j9_perftest_x86-64_linux/14/

**Comment by sxa** [comment]
> @sxa555 are you happy to champion this release going forwards?

Yes

**Comment by smlambert** [comment]
https://ci.adoptopenjdk.net/view/Test_openjdk/job/openjdk12_j9_openjdktest_ppc64_aix/

**Comment by karianna** [comment]
https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk12u/job/jdk12u-linux-x64-hotspot/26/
https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk12u/job/jdk12u-windows-x64-hotspot/28/
https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk12u/job/jdk12u-mac-x64-hotspot/32/

**Comment by jerboaa** [comment]
> https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk12u/job/jdk12u-linux-x64-hotspot/26/

```
$ ./bin/java -XX:+UnlockExperimentalVMOptions -XX:+UseShenandoahGC -version
openjdk version "12" 2019-03-19
OpenJDK Runtime Environment AdoptOpenJDK (build 12+33)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 12+33, mixed mode, sharing)
$ ./bin/java -XX:+UnlockExperimentalVMOptions -XX:+UseZGC -version
openjdk version "12" 2019-03-19
OpenJDK Runtime Environment AdoptOpenJDK (build 12+33)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 12+33, mixed mode)
```
Includes expected new GCs. Nice! That's how it should be done.

**Comment by johnoliver** [comment]
Tests for linux, windows, mac:

### Linux
[![Build Status](https://ci.adoptopenjdk.net/job/openjdk12_hs_openjdktest_x86-64_linux/14/badge/icon)](https://ci.adoptopenjdk.net/job/openjdk12_hs_openjdktest_x86-64_linux/14/)
[![Build Status](https://ci.adoptopenjdk.net/job/openjdk12_hs_perftest_x86-64_linux/14/badge/icon)](https://ci.adoptopenjdk.net/job/openjdk12_hs_perftest_x86-64_linux/14/)
[![Build Status](https://ci.adoptopenjdk.net/job/openjdk12_hs_systemtest_x86-64_linux/14/badge/icon)](https://ci.adoptopenjdk.net/job/openjdk12_hs_systemtest_x86-64_linux/14/)

### Windows
[![Build Status](https://ci.adoptopenjdk.net/job/openjdk12_hs_openjdktest_x86-64_windows/14/badge/icon)](https://ci.adoptopenjdk.net/job/openjdk12_hs_openjdktest_x86-64_windows/14/)
[![Build Status](https://ci.adoptopenjdk.net/job/openjdk12_hs_systemtest_x86-64_windows/14/badge/icon)](https://ci.adoptopenjdk.net/job/openjdk12_hs_systemtest_x86-64_windows/14/)

### Mac
[![Build Status](https://ci.adoptopenjdk.net/job/openjdk12_hs_openjdktest_x86-64_macos/15/badge/icon)](https://ci.adoptopenjdk.net/job/openjdk12_hs_openjdktest_x86-64_macos/15/)
[![Build Status](https://ci.adoptopenjdk.net/job/openjdk12_hs_systemtest_x86-64_macos/15/badge/icon)](https://ci.adoptopenjdk.net/job/openjdk12_hs_systemtest_x86-64_macos/15/)

**Comment by johnoliver** [comment]
Our failed tests are:
- `jdk_lang_0` 
- `jdk_rmi_0`
- `MauveSingleThreadLoadTest_HS_0`
- `MauveSingleInvocationLoadTest_HS_0`

**Comment by karianna** [comment]
I've released the 3 main hotspot platforms

**Comment by smlambert** [comment]
Note: test targets that are failing are actually groups of tests

Mac:  jdk_lang target contains 3455 tests, [1 test fails](https://ci.adoptopenjdk.net/job/openjdk12_hs_openjdktest_x86-64_macos/15/testReport/)
- 1 test is failing on Mac and should be excluded until https://github.com/AdoptOpenJDK/openjdk-build/issues/248 is addressed (we need native test libs to be built and provided to test jobs)

Windows: jdk_lang and jdk_rmi targets, [3 tests fail](https://ci.adoptopenjdk.net/job/openjdk12_hs_openjdktest_x86-64_windows/14/testReport/), all appear to be issues with cleaning up after these module tests on Windows

Mauve tests are newly running on jdk12, so we will take a closer look at these to understand the failures which are consistent across both JDK implementations (so suspect test issue), some details below:

MauveThreadLoadTest:
LT  FAIL: gnu.testlet.javax.swing.DefaultListSelectionModel.setSelectionInterval: SINGLE_SELECTION_X (number 7)
LT  got 2 but expected 4

LT  11:54:42.961 - Load test completed
LT  11:54:42.962 -   Ran     : 18926
LT  11:54:42.962 -   Passed  : 18916
LT  11:54:42.962 -   Failed  : 10
LT  11:54:42.962 -   Result  : FAILED

MauveSingleInvocationLoadTest (same issue as MauveThreadLoadTest):
LT  FAIL: gnu.testlet.javax.swing.DefaultListSelectionModel.setSelectionInterval: SINGLE_SELECTION_X (number 7)
LT  got 2 but expected 4

LT  11:55:04.583 - Load test completed
LT  11:55:04.583 -   Ran     : 3861
LT  11:55:04.583 -   Passed  : 3859
LT  11:55:04.583 -   Failed  : 2
LT  11:55:04.584 -   Result  : FAILED

**Comment by johnoliver** [comment]
https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk12-pipeline/94

Provides:

```
{
    "x32Windows": [
        "hotspot"
    ],
    "ppc64leLinux": [
        "hotspot"
    ]
}
```

Some other platforms failed, will re-run

**Comment by karianna** [comment]
> https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk12-pipeline/94
> 
> Provides:
> 
> ```
> {
>     "x32Windows": [
>         "hotspot"
>     ],
>     "ppc64leLinux": [
>         "hotspot"
>     ]
> }
> ```
> Some other platforms failed, will re-run

I;ll promote those two

**Comment by johnoliver** [comment]
https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk12-pipeline/95/

s390x

**Comment by karianna** [comment]
> https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk12-pipeline/95/
> 
> s390x

Promoting....   I think next time I'll have a checkbox list we can use in the main body of the issue.

**Comment by gdams** [comment]
@karianna feel free to edit https://github.com/AdoptOpenJDK/TSC/blob/master/.github/ISSUE_TEMPLATE/promote-release.md

**Comment by karianna** [comment]
Promoting https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk12-pipeline/96/ and https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk12-pipeline/97/ that should be the last of them
