### ISSUE TITLE
Promote AdoptOpenJDK Version 8u212 (GA)

### ISSUE THREAD

**Issue by karianna** [AdoptOpenJDK/TSC#76]
*Java Version:* `jdk8u212-b0x` (we'll know the final number in a few days time)

Release order:

OpenJ9 JVM:
- [x] Linux x64
- [x] Mac x64
- [x] Windows x64

Hotspot JVM:
- [x] Linux x64
- [x] Mac x64
- [x] Windows x64

OpenJ9 JVM:
- [x] x32Windows
- [x] ppc64Aix
- [x] ppc64leLinux
- [x] 390xLinux
- [x] linuxXL
- [x] x64MacXL

Hotspot JVM:
- [x] x32Windows
- [x] ppc64Aix
- [x] ppc64leLinux
- [x] s390xLinux
- [ ] aarch64Linux - decided not to release.
- [x] sparcv9Solaris

**Comment by karianna** [comment]
aarch64Linux has source code issues which @johnoliver and I need to look at carefully next week.

**Comment by gdams** [comment]
@karianna can this be closed now?
