### ISSUE TITLE
Promote AdoptOpenJDK Version 12.0.1+12

### ISSUE THREAD

**Issue by karianna** [AdoptOpenJDK/TSC#80]
OpenJ9 JVM:
- [x] Linux x64
- [x] Mac x64
- [x] Windows x64

Hotspot JVM:
- [x] Linux x64
- [x] Mac x64
- [x] Windows x64

OpenJ9 JVM:
- [x] ppc64Aix
- [x] ppc64leLinux
- [x] 390xLinux
- [x] linuxXL
- [x] x64MacXL

Hotspot JVM:
- [x] x32Windows
- [x] ppc64Aix
- [x] ppc64leLinux
- [x] s390xLinux
- [x] aarch64Linux
- [x] linuxArm32

**Comment by gdams** [comment]
looks like all of these got published, closing
