### ISSUE TITLE
OpenJ9 on SPARC

### ISSUE THREAD

**Issue by shawnhisaw** [AdoptOpenJDK/TSC#81]
Please advise on the availability of OpenJ9 on SPARC. Are there any plans to make it available on that platform? Is there a reason it is not available there currently?

**Comment by DanHeidinga** [comment]
OpenJ9 hasn't been ported to SPARC and there are no current plans to do so.  

Having said that, if you're interested in doing the port I'm sure the community would be willing to help guide you.  As existence proofs, there are porting efforts currently underway including both aarch64 and risc-v which are receiving guidance and help from the community.

**Comment by karianna** [comment]
@shawnhisaw Join us at adoptopenjdk.net/slack.html for more details
