### ISSUE TITLE
AdoptOpenJDK - a place for AdoptOpenJDK binaries or a vendor neutral home (+ the adopt binary)

### ISSUE THREAD

**Issue by karianna** [AdoptOpenJDK/TSC#86]
Should the AdoptOpenJDK home page (in particular) list all of the vendors/providers that folks can go to (including the adopt binary) or continue to focus on the adopt binary.

**Comment by karianna** [comment]
There's a lot of devil in the detail on this - so hence it needs a long discussion.

**Comment by jerboaa** [comment]
This could be an opportunity for the AdoptOpenJDK project. More OpenJDK vendors collaborating in one (additional) place[1] will IMO benefit the project overall. It could help prevent further fragmentation of the OpenJDK space where multiple vendors produce open source binaries, integration and testing in addition to their supported bits.

The project could benefit from this indirectly via several angles:

* Avoid discriminating any particular OpenJDK build
* Be the "go-to" place for getting the latest, secure, vetted, OpenJDK binary (from any vendor).
* Extend and maintain an open test framework which can be run on any OpenJDK binary on any platform.  As the test code is open source it can get re-used in-house.
* Collaborate on various integration points, like installers, JNLP, openjfx and others

[1] Beyond the OpenJDK source code base upstream.

**Comment by karianna** [comment]
Was discussed at the latest TSC meeting - we're going to come up with a list of requirements for OpenJDK providers to feature (evenly) in the AdoptOpenJDK community.  More on this next week!

**Comment by sxa** [comment]
Also:
- Makes people aware of what the options are, in a place which will be kept up to date with the options

**Comment by smlambert** [comment]
It can also be helpful to have all vendors assess their internal tests to determine whether they can be open-sourced (if not already).  If they complement (not duplicate), what is already included in [AQA](https://github.com/AdoptOpenJDK/openjdk-tests/issues/965), will be good to include them, collaborate where there is community-wide benefit.

**Comment by karianna** [comment]
https://github.com/AdoptOpenJDK/openjdk-website/issues/502

**Comment by karianna** [comment]
As a reference http://www.jchoice.eu

**Comment by hendrikebbers** [comment]
Should this be done "by hand" or do you want to define an API that vendors can implement (like an open REST endpoint) to receive a list of available builds?

**Comment by karianna** [comment]
Hearts and minds manual version first, backed by our API later I'd guess.

**Comment by karianna** [comment]
From a Java Champions Open Discussion:

* Would like to see an Openjdkwatch like distrowatch
* Feature chart to compare providers as opposed to a quality bar?
* Have a wizard to choose OpenJDK
* Random picklist would be fairest?

**Comment by karianna** [comment]
Eclipse Adoptium marketplace will fulfil this purpose.
