### ISSUE TITLE
CUDA license acceptance

### ISSUE THREAD

**Issue by karianna** [AdoptOpenJDK/TSC#88]
-----

I went through a similar kind of thing with the Eclipse Foundation a while back.

@keithc-ca wll correct me if I'm wrong, but as I understand it, the CUDA native library support built into the OpenJ9 binaries is merely the ability to load the native CUDA library and program against the external interface of that library. Building Eclipse OpenJ9 with CUDA compiles a lot of extra code in OpenJ9 but nothing from the actual library is built into an OpenJ9 binary. The user of those binaries then needs to install the CUDA library (and accept the EULA, since they're the real "EU"s here). After discussion with the Eclipse Foundation's IP team, our project chose to accept the EULA for our CI machines only for use in our pipelines so that we would be able to build CUDA support and run CUDA tests (which obviously require the library to be installed). I believe that's very similar to what other projects do when they have a dependency on this library.

My (non legal) suggestion is that AdoptOpenJDK should consider a similar arrangement: accept the EULA in order to install the CUDA libraries onto build machines (and test machines to enable running CUDA tests of this capability). But (IMO) AdoptOpenJDK binaries should not bundle the CUDA library; rather, the user should be expected to provide that library after accepting the license terms.
Hope that helps!

_Originally posted by @mstoodle in https://github.com/AdoptOpenJDK/openjdk-infrastructure/pull/792#issuecomment-496937057_

**Comment by karianna** [comment]
So I'm personally OK with Mark Stoodle's assessment here.

**Comment by karianna** [comment]
@AdoptOpenJDK/tsc I believe we're good here but please reopen if you have concerns

**Comment by keithc-ca** [comment]
Was the decision made to enable CUDA in OpenJ9 builds? Is there an issue I can follow? (I looked at https://github.com/AdoptOpenJDK/openjdk-build but couldn't find anything CUDA-related.)

**Comment by sxa** [comment]
Not to my knowledge - it was gated on having the cuda SDK installed. It came up in a discussion a few weeks ago because I hadn't realised it wasn't already enabled.

**Comment by keithc-ca** [comment]
Is someone else working on changes necessary to *enable* CUDA in OpenJ9 builds, or would a contribution from me be welcome?

**Comment by karianna** [comment]
Contribution would be welcome assuming our builds don't already include what's required
