### ISSUE TITLE
Initial TSC Board

### ISSUE THREAD

**Issue by gdams** [AdoptOpenJDK/TSC#9]
I'm going to start a new issue here and try and get things running. I would suggest that the initial board should contain 2-3 members from each core team (build, test, infrastructure, website/api)

please check out https://github.com/AdoptOpenJDK/TSC#proposed-list-of-tsc-responsibilities for more information about what the TSC is going to be doing :)

**Comment by gdams** [comment]
There are a few people that I'm going to nominate (please don't be offended if I miss you out! there are a lot of people here now!)

### Build
@karianna 
@neomatrix369
@tellison

### Test
@smlambert 
@lumpfish
@sxa555 

### Infrastructure
@bblondin 
@gdams (self nomination)

**Comment by smlambert** [comment]
Thanks for the nomination @gdams (and I in fact nominate you for infra on top of your self-nomination).  

I would be very happy to be part of the test core team.  I can expand further on the direction and goals that would be good to target over the next year if need be, some are already captured in the ["Testing Java: Help Me Count the Ways" blog post](https://blog.adoptopenjdk.net/2017/12/testing-java-help-count-ways).

**Comment by sxa** [comment]
Seems like a reasonable initial list, however I would also nominate @imifos who is tasked with leading up the security team.

**Comment by smlambert** [comment]
Security team
@imifos

**Comment by karianna** [comment]
I’m self nominating as the chairperson (if we need / want one). Reasoning is that I/we as the LJC have the current legal responsibility for the JCK and the security group and I’m the current liaison with the OpenJDK adoption group.

**Comment by karianna** [comment]
Do we want separate representation for the JCK team from testing?

**Comment by karianna** [comment]
Ideally we’d also have representation from one / some of (RH, SAP, Oracle etc) on the TSC.

**Comment by smlambert** [comment]
To the question of JCK separate from Testing, you could go either way.  Everyone in the suggested test list also have an keen interest in Compliance and are members of the private JCK group.  

But, to round out the TSC, you could split it out (@lumpfish @sxa555 in Compliance with Jiri or Volker who both have experience and spoken on the topic of JCKs at hangouts, and perhaps Muneer or Rory in Test, as they have been involved ).

**Comment by karianna** [comment]
I'd love to have Jiri (RH), Volker (SAP) and Muneer and Joshy (Oracle) join.  Everyone has different levels of hands on day-to-day participation, but I believe that the TSC should be as much about different perspectives and broad representation as anything else.  The rest of the community / project has already set the culture for "Quickly discuss first and then get things done", without too much hierarchy etc so I think we should also make that clear about role of the TSC.  It's not there to act as a barrier or checkbox for every issue and PR that goes through.  In terms of Cathedral vs Bazaar I'd prefer leaning towards Bazaar (unless it's legal or security and in that case we bring out the formalities).

**Comment by tellison** [comment]
Whoa that escalated quickly! I've not seen any discussions about what
structure is *required* to support the goals of the project, so committee
nominations and a self appointed chairperson seems far too early.

The excellent work so far has been led by a "do-ocracy" of those who are
providing the time and effort. I'd like to hear more about what the scope
of the TSC would be (and it should support not direct the people actually
doing the work).

Currently on the plane so apologies for the short response.

Tim

**Comment by karianna** [comment]
@tellison - Strawman reasoning is at https://github.com/AdoptOpenJDK/TSC#proposed-list-of-tsc-responsibilities - and we're in no rush on this so everyone can take their time, weigh in until we get consensus :-)

**Comment by karianna** [comment]
Would it be better if I temporarily transposed the https://github.com/AdoptOpenJDK/TSC#proposed-list-of-tsc-responsibilities to a Google doc so people can comment / discuss inline?

**Comment by sxa** [comment]
For reference (given the nominations are somewhat biased towards members from one company at present) the Node.js TSC limit any one company to 1/4 of the membership. I suspect it may be difficult to reasonably make the proportion quite so low if we chose to implement such a restriction for the AdoptOpenJDK project however diversity of input to the decision making processes is a good thing to encourage. Here is the wording of the current Node.js policy:

`No more than one-fourth of the TSC members may be affiliated with the same employer. If removal or resignation of a TSC member, or a change of employment by a TSC member, creates a situation where more than one-fourth of the TSC membership shares an employer, then the situation must be immediately remedied by the resignation or removal of one or more TSC members affiliated with the over-represented employer(s)`

Reference: https://github.com/nodejs/TSC/blob/master/TSC-Charter.md

**Comment by adoptopenjdk-admin** [comment]
Hi all - current [TSC Discussion Google Doc](https://docs.google.com/document/d/15-0w7AU_NXwk4WgxCOTyqFWUlednVIKohiS5H4kJZ9M/edit?usp=sharing)

**Comment by gdams** [comment]
closing
