### ISSUE TITLE
Promote AdoptOpenJDK Version 1.8.0_212-b04 (HotSpot) Windows, Linux, Mac

### ISSUE THREAD

**Issue by karianna** [AdoptOpenJDK/TSC#90]
Java Version:
1.8.0_212-b04

JVM:
- [x] Hotspot

Platforms:
- [x] Windows x86
- [x] Mac OS X
- [x] Linux x86

@AdoptOpenJDK/tsc please can somebody +1 this request?

**Comment by tellison** [comment]
+1
