### ISSUE TITLE
Publish JMC core libraries in the AdoptOpenJDK (JFrog) artifactory

### ISSUE THREAD

**Issue by thegreystone** [AdoptOpenJDK/TSC#91]
It would be great if the JMC core libraries could be published in the AdoptOpenJDK artifactory.

**Comment by reinhapa** [comment]
I can do the setup if needed..

**Comment by thegreystone** [comment]
@reinhapa do you know if a decision has been reached yet?

**Comment by gdams** [comment]
@thegreystone this was postponed on the TSC call last week because there weren't enough people to discuss. We're going to try and sort this in this weeks call.

**Comment by thegreystone** [comment]
Super! Thank you for the update!

**Comment by thegreystone** [comment]
Any news?

**Comment by karianna** [comment]
We haven't been able to reach a consensus on this yet - I still have to relay some info back to the TSC before our next meeting on Friday.

**Comment by tellison** [comment]
@karianna there's nothing sensitive about that topic, and to save you being a messenger back and forth, I'd like to suggest Marcus (and anyone else interested) participates directly in the discussion.  He's clearly the expert in this space, and it will be better to ensure we are all aligned on our goals if we simply all talk together.

**Comment by thegreystone** [comment]
Happy to talk! :) When and where?

**Comment by tellison** [comment]
@thegreystone Are you on [the project Slack workspace](https://adoptopenjdk.net/slack.html)?  We can talk over the details there.

**Comment by thegreystone** [comment]
I am now. :)

**Comment by reinhapa** [comment]
@tellison @thegreystone did you already had any discussions yet?

**Comment by thegreystone** [comment]
Nope! But I have pinged @tellison in a DM in the slack. ;)

**Comment by thegreystone** [comment]
@tellison is not replying. 😢

**Comment by jerboaa** [comment]
@thegreystone I'll be sure to bring this up at tommorow's TSC call.

**Comment by karianna** [comment]
TSC voted unanimously to support this effort - work will get co-ordinated in the #jmc channel on Slack.  Welcome aboard :-D
