### ISSUE TITLE
Publish JMC update sites

### ISSUE THREAD

**Issue by thegreystone** [AdoptOpenJDK/TSC#92]
It would be great if the two JMC update sites could be published by AdoptOpenJDK (the Eclipse one and the RCP one).

**Comment by thegreystone** [comment]
The URL paths that were considered by Oracle were:
updatesites/openjdk/7.0.0/eclipse/
updatesites/openjdk/7.0.0/rcp/

**Comment by karianna** [comment]
See #91

**Comment by jerboaa** [comment]
Removing TSC-Agenda as this has been approved.
