### ISSUE TITLE
Public JMC RCP builds for all platforms

### ISSUE THREAD

**Issue by thegreystone** [AdoptOpenJDK/TSC#93]
It would also be great if the JMC RCP builds could be published for the three platform (Windows, Linux, Mac OS X). If done, the file with the links to update sites (jmc/application/org.openjdk.jmc.rcp.application/src/main/resources/updatesites.properties) should be updated to point to the (RCP) update site mentioned in #92.

**Comment by karianna** [comment]
See #91

**Comment by jerboaa** [comment]
Removing TSC-Agenda as this has been approved.
