### ISSUE TITLE
Promote AdoptOpenJDK Version 1.8.0_212-b04 (Minor Platforms / Hotspot)

### ISSUE THREAD

**Issue by karianna** [AdoptOpenJDK/TSC#94]
Java Version:
1.8.0_212-b04

JVM:
- [x] Hotspot

Platforms:
- [x] Windows x32
- [x] Linux PPC LE
- [x] Aix PPC
- [x] Linux s390
- [x] Solaris Sparc
- [x] Solaris Intel

@AdoptOpenJDK/tsc please can somebody +1 this request?

**Comment by tellison** [comment]
+1

**Comment by jerboaa** [comment]
+1

**Comment by gdams** [comment]
+1

**Comment by gdams** [comment]
@karianna I can't see solaris intel yet? Is this still in progress?

**Comment by karianna** [comment]
Completed according to the pipeline

**Comment by gdams** [comment]
ahh yes I see it now
