### ISSUE TITLE
Promote AdoptOpenJDK Version 10.0.2+13.1

### ISSUE THREAD

**Issue by gdams** [AdoptOpenJDK/TSC#95]
Java Version:
10.0.2+13 (adopt build number 1)

Link: https://github.com/AdoptOpenJDK/openjdk10-binaries/releases/tag/jdk-10.0.2%2B13.1

JVM:
- [x] Hotspot

@AdoptOpenJDK/tsc please can somebody +1 this request?

A little background to this.

JDK10u had some weird directory layout discrepancies which were causing issues when we used them as a boot jdk for 11. Seeing as 11u is an LTS release, it makes sense to re-build jdk10u for hotspot so that we have an updated boot JDK with the correct directory layout.

**Comment by johnoliver** [comment]
:+1:

**Comment by sxa** [comment]
+2

**Comment by gdams** [comment]
+1 from @karianna

**Comment by gdams** [comment]
promoted
