### ISSUE TITLE
Pay for SwaggerHub for collaborative API development

### ISSUE THREAD

**Issue by karianna** [AdoptOpenJDK/TSC#96]
Swagger is pretty much the defacto std for hosting public API definitions.  We're evaluating Swaggerhub pro for the API V3 development. It will cost $75p/m if we pay annually or $90p/m if we may monthly.

This is so we can have multiple developers working on the Swagger definition.   Else we are locked down to only one developer being able to work on this at a time.

There is also the benefit of being on the Swagger Hub (a bit like being on Docker hub).

**Comment by jerboaa** [comment]
Perhaps we can limit this for the time where the API is in active development? So perhaps per month pay and go the route of self-hosting the swagger API via [swagger-ui](https://github.com/swagger-api/swagger-ui)

**Comment by karianna** [comment]
> Perhaps we can limit this for the time where the API is in active development? So perhaps per month pay and go the route of self-hosting the swagger API via [swagger-ui](https://github.com/swagger-api/swagger-ui)

Could do - so perhaps we go for the monthly pricing and switch on and off as need be.

**Comment by sxa** [comment]
Based on https://swagger.io/tools/swaggerhub/pricing/ this would mean we'd be restricting ourselves to having 5 people able to work on the API at any given time for those prices - is that correct? It does seem that it would make the project a little less open that would be ideal based on our normal philosophies, but if it provides significant benefits it's probably worth it.

**Comment by karianna** [comment]
> Based on https://swagger.io/tools/swaggerhub/pricing/ this would mean we'd be restricting ourselves to having 5 people able to work on the API at any given time for those prices - is that correct? It does seem that it would make the project a little less open that would be ideal based on our normal philosophies, but if it provides significant benefits it's probably worth it.

Yes but I think it's fair to say it's unlikely we'll have more than 5.  It's Really John and George and possibly tiny bits from myself and other power users.

**Comment by gdams** [comment]
closing out for now, this has gone quiet
