### ISSUE TITLE
TSC Meeting: 2019-07-12

### ISSUE THREAD

**Issue by karianna** [AdoptOpenJDK/TSC#98]
Invited: @AdoptOpenJDK/tsc

Present:

Severin Gehwolf (Red Hat)
Tim Ellison (IBM)
Stewart Addison (IBM)
Martijn Verburg (jClarity)
John Oliver (jClarity)
Shelley Lambert (IBM)

Guests:

Mario Torre (Red Hat)
Marcus Hirt (Datadog)
Hendrik ? (Datadog)

Resignations:

Ed Vielmetti from Packet has resigned from the TSC due to time commitments

### adoptopenjdk/TSC

* Public JMC RCP builds for all platforms [#93](https://github.com/AdoptOpenJDK/TSC/issues/93)
* Publish JMC update sites [#92](https://github.com/AdoptOpenJDK/TSC/issues/92)
* Publish JMC core libraries in the AdoptOpenJDK (JFrog) artifactory [#91](https://github.com/AdoptOpenJDK/TSC/issues/91)

Marcus Hirt (project lead of JMC at OpenJDK) - Explained the history of JMC and how it's currently being distributed (both in source and binary form).  He explained that the unbranded 'canonical' version of JMC does not have a distribution home and Marcus wanted to explore the idea of having AdoptOpenJDK as that home.  Severin added that we do something similar for the 8u and 11u releases.

There was some discussion over who should distribute the JMC artifacts, and where. The broad consensus was that Marcus (as project lead) is empowered to make that choice (under the OpenJDK bylaws).

Tim asked about the various components that would be built and whether JMC would be a separate download or be part of our installers etc.  The suggestion was that JMC should be built standalone and the plugins etc could be distributed through AdoptOpenJDK’s Artifactory.

Tim asked whether Marcus wanted AdoptOpenJDK to build from source and to run tests as well, Marcus hoped that would be possible but that the binaries were the most important parts.  Tim noted that it is AdoptOpenJDK’s preference to distribute binaries that we have openly built from the source at the project.

TSC members unanimously voted to invite JMC to AdoptOpenJDK and to build from source, test and produce the robust binaries that our users expect.

AI: Martijn to create JMC channel, invite selected parties and facilitate onboarding - DONE.

### Finance
Update sent and discussed, separate meeting to be held on how we should spend/hold in reserve, etc.

### Google Products
George set this up, TSC members are onboarding

### Release planning

Martijn to co-ordinate starting on the 16th
One of the Macstadiums is slow - Martijn to investigate
More Macs required - Martijn and George to resolve
More Windows machines required - Stewart and Ali? To resolve
Git-hg job bugs - John and Andree Leonard to resolve
New #release channel set up

**Comment by smlambert** [comment]
Closing.
